### PR TITLE
Implement touch interactions in 3D subplots

### PR DESCRIPTION
**Pull request by etpinard**
Brings in @dfcreative 's https://github.com/mikolalysenko/3d-view-controls/pull/1 (via https://github.com/gl-vis/gl-plot3d/pull/7).

This PR partly resolves https://github.com/plotly/plotly.js/issues/480.

Test it on your mobile devices with http://codepen.io/etpinard/full/aJOMzZ/

### CODE REVIEW

**Comment by alexdoso** [comment]
the sample in codepen takes forever to load and doesn't rotate in chrome browser on mobile android 5, though panning and zooming of the whole page works. 
I also with to have the possibility to zoom and pan so the 'canvas' remains in the same place but the x and Y axes adapt accordingly to the zoom and the pan.

**Comment by etpinard** [comment]
@dfcreative can you confirm https://github.com/plotly/plotly.js/pull/1424#issuecomment-285626572

It would be nice to wrap this one up.

**Comment by dfcreative** [comment]
@etpinard yeah, touch interactions are going to be covered by [scatter-lasso PR](https://github.com/plotly/plotly.js/pull/1657/files#diff-bc0836e44761269187215283db7a6fa6R187).

**Comment by etpinard** [comment]
Even in 3d?

**Comment by dfcreative** [comment]
@etpinard yes, it includes unmerged [3d-touch-interactions](https://github.com/dfcreative/plotly.js/tree/3d-touch-interactions) branch

**Pull request closed without merging**
