### PR TITLE
Fix waterfall 'closest' hover when cursor is below the size axis

### PR DESCRIPTION
**Pull request by etpinard**
fixes https://github.com/plotly/plotly.js/issues/4524 - essentially a followup on https://github.com/plotly/plotly.js/pull/3778/

before: https://codepen.io/etpinard/pen/dyPBwPJ
after: https://codepen.io/etpinard/pen/povXqJv

cc @archmoj

### CODE REVIEW

**Comment by archmoj** [comment]
@etpinard thanks for the PR!
Any idea why the hover does not show up on the very first bar?

**Comment by etpinard** [comment]
Try now: https://codepen.io/etpinard/pen/oNgrJYq

**Comment by archmoj** [comment]
Nicely done.
:dancer:

**Comment by etpinard** [comment]
Ok thanks for the review. I'll wait before you have a look at the `treemap_coffee` problem before merging.

**Pull request merged**
