### PR TITLE
Rebased esbuild PR

### PR DESCRIPTION
**Pull request by birkskyum**
Rebased version of
- #6909

### CODE REVIEW

**Comment by birkskyum** [comment]
Merge didn't go well

**Comment by archmoj** [comment]
I prefer not to rebase this PR to get Alex's contributions; but if you could resolve merge conflicts in a PR targeting that branch; it would be perfect.
I could also resolve these conflicts.

**Comment by alexcjohnson** [comment]
@archmoj don’t worry about my contributions, I just kicked it off but the vast majority of the work is from you guys - do whatever gets the PR done quickest 😎

**Comment by archmoj** [comment]
> @archmoj don’t worry about my contributions, I just kicked it off but the vast majority of the work is from you guys - do whatever gets the PR done quickest 😎

Hi Alex,
We managed to resolve the conflicts on the original PR.

**Pull request closed without merging**
