### PR TITLE
use new jasmine pattern for catching errors in async code

### PR DESCRIPTION
**Pull request by archmoj**
Addressing https://github.com/plotly/plotly.js/pull/5340#discussion_r547545206
The first pass to retire `failTest`.

@plotly/plotly_js

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Have you verified that `done.fail` gives similar feedback to what we got from `failTest` when an exception is thrown? And is there a reason that pattern is preferable to `.then(done, done)` that the [docs imply](https://jasmine.github.io/tutorials/async#failing-with-callbacks) should do the same thing in Jasmine 3?

**Comment by archmoj** [comment]
> Have you verified that `done.fail` gives similar feedback to what we got from `failTest` when an exception is thrown? And is there a reason that pattern is preferable to `.then(done, done)` that the [docs imply](https://jasmine.github.io/tutorials/async#failing-with-callbacks) should do the same thing in Jasmine 3?

RE1:
I verified and it prints out the error in case of exception.

RE2:
It looks like we could use the `.then(don, done)` instead but then this case would be confusing:
https://github.com/plotly/plotly.js/blob/444be40d01f37be5e18556fd43daefa2b1ef424a/test/jasmine/tests/animate_test.js#L183
So it seems preferable to keep `done.fail` as is.

**Comment by alexcjohnson** [comment]
True, `done.fail` is more explicit. Also possibly `.then(done, done)` would look like a pass if we (or any dep) ever throw a non-error, ie `throw 'whoops!'` rather than `throw new Error('whoops!')`

So great, let's keep `done.fail`.

That `Plotly.animate` test is certainly confusing in any case, and it makes me wonder whether we're really rejecting the way we want to. Looks like it's this one:

https://github.com/plotly/plotly.js/blob/444be40d01f37be5e18556fd43daefa2b1ef424a/src/plot_api/plot_api.js#L3471-L3474

Most people seem to [recommend rejecting with an `Error`](https://masteringjs.io/tutorials/fundamentals/promise-reject) which seems like it would be more useful, but if we did that we'd need to change the test to something like:
```js
Plotly.animate(gd, ['foobar'], animOpts).then(done.fail, () => { done() });
```

Anyway not worth spending time on now, `Plotly.animate` is no longer something we're recommending people use anymore. But if we have a future need to reject a promise I think we should do so with an `Error`.

**Comment by archmoj** [comment]
> After this PR are there any uses of `failTest` left, or can we delete it entirely?

There are just a few cases. But let's attempt drop `failTest` in another PR.

**Review by alexcjohnson — APPROVED** [review]
💃

**Pull request merged**
