### PR TITLE
Boxpoints no range

### LINKED ISSUE #725: Boxplot points not drawn when data has no whiskers and jitter is not 0
When the data to be plotted has such a distribution that there are no whiskers to be drawn, plotly fails to draw boxpoints if jitter is set to anything but 0. I.e. if jitter is 0, the points are drawn, but they overlap. Example at:

http://codepen.io/anon/pen/OXjgNP

### PR DESCRIPTION
**Pull request by alexcjohnson**
Fixes #725 - problems with the box plot jitter algorithm when there's no interquartile range (or even no range at all) - by falling back on a fraction of the total range or, barring that, just disabling the adaptive jitter.

screen shot 2016-09-07 at 7 54 20 pm

screen shot 2016-09-07 at 8 09 11 pm

@etpinard OK?

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Fixes #574 as well.

Using the data from https://jsfiddle.net/cf4j5vxz/ -
screen shot 2016-09-07 at 8 30 37 pm

**Comment by etpinard** [comment]
Looks good, Thanks!

Are you all set to add a couple image tests? If you're too busy, I can take it from here and make this PR part of `v1.17.0` to be released tomorrow.

**Comment by alexcjohnson** [comment]
@etpinard + test image expanding on #725

**Comment by etpinard** [comment]
beautifully done :dancer:

**Pull request merged**
