### PR TITLE
Fix scattergl select -> dblclick -> pan bug

### PR DESCRIPTION
**Pull request by etpinard**
fixes https://github.com/plotly/plotly.js/issues/2767 

Can't stop won't stop fixing bugs this week.

peek 2018-07-13 16-09

I'm not 100% this is the best to fix this bug (@dy would you mind reviewing this?), but the new test case should be a good starting point if ever there's a better solution out there.

cc @alexcjohnson

### CODE REVIEW

**Comment by alexcjohnson** [comment]
So the bug isn't manifest in the figure JSON at all, just on screen? The test looks great, but I agree, @dy should review the actual code change.

**Comment by etpinard** [comment]
> So the bug isn't manifest in the figure JSON at all, just on screen?

correct.

**Comment by etpinard** [comment]
Ping @dy !

Would be nice to include this in 1.39.3

**Comment by alexcjohnson** [comment]
💃

**Comment by dy** [comment]
Lgtm :dancer:!

**Pull request merged**
