### PR TITLE
Add 'nancolor' heatmap attribute

### PR DESCRIPTION
**Pull request by etpinard**
resolves https://github.com/plotly/plotly.js/issues/975

... if we agree this is a good addition.

gifrecord_2016-11-18_164917

@alexcjohnson @cldougl  @chriddyp @rreusser

### CODE REVIEW

**Comment by alexcjohnson** [comment]
I like it. One related thing people may want to do is set missing bricks to a certain *data value* - often 0 but I can imagine cases where you'd want to use other values. That way it automatically takes that value from the colorscale.

These two effects are a bit different - which you can see most clearly when you think about smoothed heatmaps or contour maps (which should also get this feature!) setting nan to a specific *color* should not attempt to interpolate it, or its color, to its neighbor, but setting nan to a specific *value* **should** interpolate. Also setting a nan value could extend the auto range of the color scale, depending on whether there's a nan in the data or not.

So we could attempt to specify these by the same attribute, which has the advantage that it's impossible for folks to specify both, and one less attribute to learn - something like `nanfill=0` vs `nanfill='red'`... or to better distinguish their behaviors we could keep them separate, handle `nancolor` as you have it and add another like `nanvalue`, then we need to decide which takes precedence. I don't have a strong preference between these options, anyone?

**Comment by nzjrs** [comment]
any reason why this got dropped?

**Comment by etpinard** [comment]
> any reason why this got dropped?

Not enough hours in a day.

**Comment by etpinard** [comment]
Closing this thing. We're still planning on adding this feature, but this should happen in another PR.

Devs should refer back to https://github.com/plotly/plotly.js/issues/975 and keep in mind https://github.com/plotly/plotly.js/issues/2142 during future development.

**Pull request closed without merging**
