### PR TITLE
Rangeslider style on select fix

### PR DESCRIPTION
**Pull request by etpinard**
@plotly/plotly_js - tweaking a few things in selection / rangeslider land.

fixes https://github.com/plotly/plotly.js/issues/3957

before: https://codepen.io/mbkupfer/pen/zVGwoZ
after: https://codepen.io/etpinard/pen/KjxWzZ (try selecting the bars)

### CODE REVIEW

**Comment by etpinard** [comment]
Pinging @mbkupfer who seems to be very good at noticing rangeslider/selection bugs

Could you try https://codepen.io/etpinard/pen/KjxWzZ - if you get the chance? Thanks very much!

**Comment by archmoj** [comment]
Looking good to my eyes.
@etpinard would you like to include this in 1.49.0?

**Comment by etpinard** [comment]
> would you like to include this in 1.49.0?

Yeah, that would be nice.

**Comment by mbkupfer** [comment]
Excellent. I tried to test out many different scenarios including click events and multiple series and didn't see any sync problems.
Thanks for the fix @etpinard, can't wait for the upgrade!

**Comment by archmoj** [comment]
@mbkupfer your review is much appreciated.

@etpinard thanks for the fix.
:dancer:

**Pull request merged**
