### PR TITLE
Orthographic projection for 3D plots

### LINKED ISSUE #2611: Orthographic projection for 3D plots
Hello,

I would like to know if 'orthographic' projection could be added as an option to plotly 3D plots.
Indeed, this option is available in [Matlab](https://fr.mathworks.com/help/matlab/ref/camproj.html), and in [matplotlib ](https://matplotlib.org/users/prev_whats_new/whats_new_2.1.0.html#orthographic-projection-for-mplot3d) since version 2.1.

image

As explained [here](https://fr.mathworks.com/help/matlab/visualize/understanding-view-projections.html), such a projection maintains parallelism and distances, and is therefore sometimes better suited when plotting data. For example, a camera looking along the z axis (top view) would directly give you a perfect xy plane projection, which it does not do on Plotly right now,
 as can be seen on that [example](https://plot.ly/javascript/3d-axes/#camera-controls).

### PR DESCRIPTION
**Pull request by archmoj**
Fixes #2611. 
A new attribute `ortho` is defined on the camera object and passed to various modules.
The scene initialisation is now uses the camera init variables and `createCamera` is centralised in a separate module (i.e. `3d-view`) as it was used by `plotly.js` as well as `3d-view-controls` & `gl-plot3d` modules.  
This is a work in progress and some functions such as zooming and restyle require improvements.
Hint: to quickly test the functionality of this feature with existing 3-D mocks, one may change the `dflt` of `ortho` to be equal to `true`.
@etpinard

### CODE REVIEW

**Comment by etpinard** [comment]
@archmoj how close is this one to being `reviewable`?

**Comment by archmoj** [comment]
> @archmoj how close is this one to being `reviewable`?

@etpinard Please let me resolve the conflicts & clean up the commits in a new PR possibly tomorrow.

**Comment by etpinard** [comment]
> & clean up the commits in a new PR possibly tomorrow.

Wanna try to merge master and resolve the conflict instead? Keeping just one PR in our github history. Thanks!

**Comment by archmoj** [comment]
Now in #3550 
Closed.

**Pull request closed without merging**
