### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by ghtmtt**
Thanks for your interest in plotly.js!

Italian translation for plotly. Not complete (yet)

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Thanks @ghtmtt - looks like you're almost there! Comparing with https://github.com/plotly/plotly.js/blob/master/dist/translation-keys.txt there are just a few more to add. Can you suggest one or two other Italian speakers to review once the last items are added?

**Comment by ghtmtt** [comment]
@alexcjohnson here we go. All the translations should be updated now

**Comment by alexcjohnson** [comment]
Great! I just tweaked a little of the punctuation and code reference comments. Perhaps I can convince @giulioungaretti to give a quick review of these translations? 🙏

**Comment by alexcjohnson** [comment]
Thanks @giulioungaretti ! And thank you @ghtmtt for your contribution! 💃

**Comment by ghtmtt** [comment]
I'm using plotly in my https://github.com/ghtmtt/DataPlotly plugin. That's the minimum I can do for you guys ;-)

**Pull request merged**
