### PR TITLE
bar transitions: support object constancy

### PR DESCRIPTION
**Pull request by antoinerg**
Add support for object constancy to bar transitions!

[Codepen](https://codepen.io/antoinerg/pen/vYBjREv)

### CODE REVIEW

**Comment by etpinard** [comment]
Awesome!

Next stop: let's try to find a nice way to test this.

**Comment by etpinard** [comment]
Moreover, can anyone else detect that the text font color transition before the bars' positions are swapped?

**Comment by antoinerg** [comment]
> Moreover, can anyone else detect that the text font color transition before the bars' positions are swapped?

I confirm that is the case. The reason is that we don't have transitions for text size/color but only for its `transform`...

**Comment by etpinard** [comment]
> The reason is that we don't have transitions for text size/color but only for its `transform`... I could definitely add those in before 1.50.

Cool. If you don't have the time to add it for 1.50.0, no big deal. Just make sure to add to the TODO list in https://github.com/plotly/plotly.js/issues/3456

**Comment by etpinard** [comment]
@antoinerg ok to merge?

**Comment by antoinerg** [comment]
@etpinard It looks good to me. I will add text color and font-size tweening in a separate PR

:dancer:

**Comment by etpinard** [comment]
No problem @antoinerg I updated https://github.com/plotly/plotly.js/issues/3456 accordingly. Thanks!!

**Pull request merged**
