### PR TITLE
Add remove-headers transform

### PR DESCRIPTION
**Pull request by etpinard**
@mdtusz quick PR removing a bytes in the un-minified `dist` files.

The `remove_headers` tranforms parses through each bundle file and removes the src license found in each src fiile.

### CODE REVIEW

**Comment by mdtusz** [comment]
If we're removing the headers, why not all the comments? Surely there's even a few more bytes of comments in there.

**Comment by etpinard** [comment]
@mdtusz good point. 

I guess it depends what we want out of the un-minified dist plotly.js bundle.

- Is it meant to allow users to minified plotly.js using other minifiers or other uglify-js options than we do? In this case, removing all comments makes sense.

- Is it meant to allow for better troubleshooting for folks using the cdn links? In this case, I'd argue that the comment in the code could make troubleshooting easier.

cc @bpostlethwaite 

Is it supposed to be an all-in-one bundle used for debugging

**Comment by mdtusz** [comment]
If we want the unminified version to be good for debugging and troubleshooting, shouldn't we leave the header in to preserve accurate line numbers? I'm fine with either option, but I think we should either remove everything that's not code, or leave it all.

**Comment by etpinard** [comment]
> If we want the unminified version to be good for debugging and troubleshooting, shouldn't we leave the header in to preserve accurate line numbers?

@mdtusz you got me convinced. Closing.

**Comment by mdtusz** [comment]
:blush:

**Pull request closed without merging**
