### PR TITLE
Welsh UK locale formats type:translation

### PR DESCRIPTION
**Pull request by HywelMJ**
Welsh UK locale formats

References: http://www.comisiynyddygymraeg.cymru/English/Part%203/10%20Locales%20alphabets%20and%20character%20sets/10.1%20Locales/Pages/10-1-3-Differences-between-British-English-and-British-Welsh-locales.aspx
http://www.unicode.org/cldr/charts/28/verify/dates/cy.html

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Very nice @HywelMJ, thanks! I just linted a couple of whitespace issues. (though it's still complaining "incorrect header information" - @etpinard I don't see what's wrong, do you?)

@HywelMJ do you want to try translating the text as well, or are you OK leaving this in English? There are examples [here](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aclosed+label%3A%22type%3A+translation%22)

**Comment by etpinard** [comment]
> @etpinard I don't see what's wrong, do you?

Something was up when comparing newline characters `\r\n` vs `\n`, https://github.com/plotly/plotly.js/commit/ac28c3469aaf09cb442e14c9dee594c8343c2797 fixes that.

Now I can't seem to be able to push `HywelMJ:master`. Can someone either cherry-pick ac28c3469aaf09cb442e14c9dee594c8343c2797 or open another PR from https://github.com/plotly/plotly.js/commit/ac28c3469aaf09cb442e14c9dee594c8343c2797?

**Comment by alexcjohnson** [comment]
> do you want to try translating the text as well

Thanks very much @HywelMJ! Can you recommend another Welsh speaker who's able to review these?

> Now I can't seem to be able to push `HywelMJ:master`. Can someone either cherry-pick ac28c34 or open another PR from ac28c34?

Huh, now github seems confused about where this is coming from altogether, just says:

> **HywelMJ** wants to merge 4 commits into `plotly:master` from `unknown repository`

Might be easiest to just remake this as a PR from a local branch. I'm happy to do this (also the new dictionary needs indentation and some other whitespace) but lets see if we can find a reviewer for the dictionary first in this PR.

**Comment by HywelMJ** [comment]
Sorry, I'm getting a bit lost. I tried commenting:
"I couldn't manage to merge PR #2877 so I forked again but I've added translation of chart term now.
Left translation of 'Pan' as 'Pan' as not sure how to translate. Some other terms are tentative but hopefully intelligible to Welsh speakers. @carlmorris @illtud @meigwilym may be able to help in reviewing"

Here's the script I tried merging:
[cy.txt](https://github.com/plotly/plotly.js/files/2284665/cy.txt)

**Comment by alexcjohnson** [comment]
No problem @HywelMJ - I'm happy to manage the mechanics. Not sure if I'll be able to do it in a way that preserves your authorship in the git history but I'll try!

@carlmorris @illtud @meigwilym if one of you would review and the items in `dictionary` here I'd be grateful - then I'll fix up the indentation and such and make a new PR.

**Comment by illtud** [comment]
Looks good to me. I may have used 'olin' for 'trace' rather than 'tres', but it's not a hill I'd die on.

**Comment by alexcjohnson** [comment]
Thanks @illtud, really appreciate you taking the time to review! @HywelMJ let me know if you'd like to swap in 'olin' or keep 'tres', and then I'll make a new PR.

**Comment by alexcjohnson** [comment]
superseded by #2945

**Pull request closed without merging**
