### PR TITLE
Include transforms in partial bundles

### LINKED ISSUE #5378: Missing transforms on partial bundles
[codepen](https://codepen.io/MojtabaSamimi/pen/abmKBYZ?editors=1000)

### PR DESCRIPTION
**Pull request by archmoj**
Fixes #5378 | [Before](https://codepen.io/MojtabaSamimi/pen/abmKBYZ?editors=1000) vs [After](https://codepen.io/MojtabaSamimi/pen/WNGyRre?editors=1000).

@plotly/plotly_js

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Can you regenerate `dist/README.md` and post the diff here? Just curious how much size this adds to each bundle, as minified and gzipped.

**Comment by archmoj** [comment]
This PR somehow fixes #5382 as well!

**Comment by archmoj** [comment]
> Can you regenerate `dist/README.md` and post the diff here? Just curious how much size this adds to each bundle, as minified and gzipped.

diff-1
diff-2

**Review by alexcjohnson — APPROVED** [review]
💃 That seems like a small enough cost that it's worthwhile in all the bundles.

**Pull request merged**
