### PR TITLE
Implement attributes base, offset and width in bar traces (issue 80)

### PR DESCRIPTION
**Pull request by n-riesco**
This PR implements attributes base, offset and width as discussed in plotly#80 .

This PR's review can be found [here](https://github.com/n-riesco/plotly.js/pull/3).

### CODE REVIEW

**Comment by etpinard** [comment]
@n-riesco great. I'll give this PR one last test drive tomorrow morning (UTC-4)

**Comment by n-riesco** [comment]
@etpinard 

`plotschema_test.js` fails because of attribute `base`. `base` can take a data value (`valType: 'any'`) or a data array (`valType: 'data_array'`). 

I guess the easiest workaround would be to use `valType: 'any'` and remove `arrayOk`.

**Comment by etpinard** [comment]
Can `base` be anything other than a number or an array of numbers?

If so, then it should be `valType: 'number'` with `arrayOk: true`.

**Comment by n-riesco** [comment]
In principle, `base` could be any value taken by the corresponding axis. I can't think of any meaningful bar plot, where the size axis isn't a number, though.

@alexcjohnson How do you think? Did you have anything in mind in #80 that would require `base` to be `any`?

**Comment by alexcjohnson** [comment]
In general if there's no concept of zero on an axis then bar charts don't make sense. Though interestingly I guess with `base` we could relax that requirement and say distance must be meaningful (and the size data would be expressed as such a distance) but you don't need a zero. Date axes match that description, and the corresponding chart is a Gantt chart (cc @jackparmer ) so if we want to support that I guess base would need to be 'any' but size would still be a number (milliseconds)

**Comment by n-riesco** [comment]
@etpinard @alexcjohnson  Here's a crazy idea. At the moment, plotly classifies as `valType: 'number'` anything that `isNumeric` says it's a number. If `isNumeric` would consider `Date` values as numbers, then `base` declared as `{valType: 'number', arrayOk: true}`  would also accept date values. Do you think this would work?

**Comment by etpinard** [comment]
> If isNumeric would consider Date values as numbers, then base declared as {valType: 'number', arrayOk: true} would also accept date values. Do you think this would work?

Hmm. I afraid that patching `isNumeric` will lead to some issues downstream. I'm thinking we should add a new `valType` called `coordinate` for attributes of the likes - in a future PR.

So, let's go with `{ valType: 'any', arrayOk: true }` in this PR.

Thanks for the heads-up @n-riesco !

**Comment by n-riesco** [comment]
@etpinard Do you want me to add `arrayOk` to https://github.com/plotly/plotly.js/blob/ec0b0a49326f689dee01b228704dfb9ac1c9ea78/src/lib/coerce.js#L231 so that `plotschema_test.js` doesn't fail?

**Comment by alexcjohnson** [comment]
`coordinate` is an interesting idea... though you could say categories are coordinates too so it doesn't specify much.  but yeah, dates and numbers are generally not interchangeable so we need to manage them separately. 

I wonder if there would be value in valType unions, so you could specify number or date string, for example.

**Comment by etpinard** [comment]
> Do you want me to add arrayOk to https://github.com/plotly/plotly.js/blob/ec0b0a49326f689dee01b228704dfb9ac1c9ea78/src/lib/coerce.js#L231 so that plotschema_test.js doesn't fail?

yes please.

**Comment by etpinard** [comment]
Oh @n-riesco I forgot about something ... `Plotly.restyle` !

We (unfortunately - see https://github.com/plotly/plotly.js/issues/648) need to manually list which attributes require going through the calc / set-position on updates. That list is getting really ugly, but luckily the patch is easy to make:

image

should be all you need.

While doing so, maybe you can add one `restyle` test in `bar_test.js`. Requiring one test mock e.g `require('@mocks/bar_attrs_relative')`, together with a few `Plotly.restyle` calls and a few `expect(gd.calcdata)` should be all you need.

Sorry about the late notice.

**Comment by n-riesco** [comment]
@etpinard While writing the`restyle` test, I noticed a bug in the calculation of the bar centers and the corresponding tests (bar centers have to be computed after applying `offset` and `width`). This is now fixed.

**Comment by etpinard** [comment]
@n-riesco you win the PR of week :trophy: 

Thanks very much. This should make a bunch of people :smile:

**Comment by liuyingh** [comment]
histwsaf
newplot 1

**Comment by AdnanBoota** [comment]
Can i increase the bar widths with the x axis type as "date"?

The idea is to have a single bar value (with large width) for multiple hours on time series.

Right now i am doing it on the numerical values, but i want to implement it on time series. Please check and let me know what is best solution for this implementation.

imagen

**Pull request merged**
