### PR TITLE
Speed up selection

### PR DESCRIPTION
**Pull request by dfcreative**
This fixes multimarker selection error (@bpostlethwaite discussion) and speeds up entering selection mode (up to ×3 times).

* [x] add test

### CODE REVIEW

**Comment by dfcreative** [comment]
@alexcjohnson please take a look.

**Comment by alexcjohnson** [comment]
Nice, can't argue with the 🐎 ! Only suggestion would be 🌴  something like
```js
selectedOptions = makeModifiedMarkerOptions(trace.selected.marker, markerOpts);
unselectedOptions = makeModifiedMarkerOptions(trace.unselected.marker, markerOpts);
```

**Comment by dfcreative** [comment]
@alexcjohnson done, thank you for the good point!

**Comment by dfcreative** [comment]
@alexcjohnson should that be a good-to-go?

**Comment by alexcjohnson** [comment]
💃

**Pull request merged**
