### PR TITLE
Finalist - Improve rendering of lines in 3D (against disappearing in certain angles) issue #691

### PR DESCRIPTION
**Pull request by archmoj**
This PR is the continuation of PR #3128 where the master is fetched and conflicts are resolved to facilitate the merge process.
Previously the angles computed in the gl-plot3d module necessary to match rectangle shapes towards camera point were not accurate. Therefore 2D representations of 3D lines were not oriented properly in various perspective angles. Disappearing and tininess impacts resulted from the bug could be clearly observed namely when the thicknesses of lines using scatter3d were increased. Please refer to the issue #691 for more information.
This PR improves rendering of lines in 3D scenes by performing proper 3D/2D calculations within the webgl vertex shader of the module.
@alexcjohnson
@etpinard

### CODE REVIEW

**Comment by etpinard** [comment]
Nice work @archmoj 

So if I understand correctly, issue https://github.com/plotly/plotly.js/issues/691 was visible in the `plot_types` mock 

peek 2018-10-26 09-26

and is now fixed?

**Comment by archmoj** [comment]
Yes it was visible. And it should be fixed now. 
FYI @etpinard I also created a new mock in this PR to better highlight this issue namely with 3D lines with greater thicknesses.

**Comment by etpinard** [comment]
Great! Well done :dancer:

**Comment by etpinard** [comment]
... after you publish a new `gl-line3d` patch of course.

**Comment by archmoj** [comment]
Hey wait, 
Still need to address @alexcjohnson comment concerning `gl3d_set-ranges` here
https://github.com/plotly/plotly.js/pull/3163/files?short_path=17cbbc9#diff-17cbbc97019f5b261179c860f0dcef28

**Comment by archmoj** [comment]
With the latest changes the difference between old image baselines (on current master) & new image baselines is much reduced. The `gl3d_set-ranges` is actually removed from the list of changed files. So we should be good to continue with merging the [PR on gl-vis](https://github.com/gl-vis/gl-line3d/pull/7/) then this branch. What do you think @etpinard ? Would you give me two dancers to merge one after the other?

**Comment by etpinard** [comment]
> new image baselines is much reduced.
> The `gl3d_set-ranges` is actually removed from the list of changed files

That's great news. I say :dancer: (unless @alexcjohnson find other suspicious things from the diff images)

**Comment by alexcjohnson** [comment]
💃

**Pull request merged**
