### PR TITLE
add instruction for TypeScript usage

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by etpinard** [comment]
First off, thanks for the PR.

Hmm, I'm not 100% sure we should include this in our Readme as we have no control over the [typescript](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/plotly.js) definitions (cf https://github.com/plotly/plotly.js/issues/28). 

Furthermore, no current plotly.js team member has any experience using typescript, so we can't really put our stamp-of-approval on them.

At the very least, I don't think we include typescript info in the "Quick start options" section. Personally, I think this belongs in a new section below "Building plotly.js".

cc @plotly/plotly_js @nicolaskruchten

**Comment by nicolaskruchten** [comment]
We could add a section that says something like "Related third-party projects" or something and list the TS thing there? I agree we don't want to stamp our approval to the TS typings at this time, not because they're bad, but because we can't commit to maintaining them.

**Comment by simon04** [comment]
Thank you, @etpinard and @nicolaskruchten, for your review and comments. I agree that having a separate section for 3rd party contribution is more adequate, and addressed this in the commit https://github.com/plotly/plotly.js/pull/4255/commits/f5e332983d7155b54e1fcc7c85bee1f5308c01b6.

**Comment by archmoj** [comment]
@simon04 could you please merge master into this branch and resolve the conflict?

**Pull request closed without merging**
