### PR TITLE
SDF strategy for 'fancy' scattergl traces

### PR DESCRIPTION
**Pull request by etpinard**
fixes https://github.com/plotly/plotly.js/issues/566

See details in https://github.com/gl-vis/gl-scatter2d-fancy/pull/5

@dfcreative is the man!

### CODE REVIEW

**Comment by dfcreative** [comment]
@etpinard looking at baselines I've tuned up rendering a bit in gl-scatter2d-sdf@1.3.1, border size should be more consistent. But still rendering in Ubuntu seems to be a bit off

**Comment by etpinard** [comment]
@dfcreative done in https://github.com/plotly/plotly.js/pull/1398/commits/18fae278697231963f1598aee6493fe672c2b5f7

**Comment by etpinard** [comment]
Waiting on more thorough feedback from https://github.com/plotly/plotly.js/issues/566 authors; dropping from the `1.24.0` milestone.

**Comment by etpinard** [comment]
I noticed something. Looks like something is up with the zoom box:

Current `master`:

gifrecord_2017-03-03_173257

Off this branch:

gifrecord_2017-03-03_173416

the shaded area used to be transparent, and now it appears to be opaque. I'll investigate next week.

**Comment by dfcreative** [comment]
@etpinard fixed with https://github.com/gl-vis/gl-scatter2d-sdf/commit/6ebe332ebd56fed99a9225886fc4850f5de172d6

**Comment by etpinard** [comment]
@dfcreative thanks for the fix!

The new patch affect the gl2d_17 baseline:

image

Can you comment on that?

**Comment by dfcreative** [comment]
@etpinard thanks, fixed with https://github.com/gl-vis/gl-scatter2d-sdf/commit/1c9ec60b129f28258c355231bafc4dcbdd795354
Not the best solution, but persistent across @gl-vis.

**Comment by etpinard** [comment]
@dfcreative much better!

gifrecord_2017-03-06_142330


Ok. Well, this PR is ready to be merged once the latest `gl-scatter2d-sdf` patch is published :tada: 

This PR should be part of the next **minor** release `v1.25.0` set for early next week.

**Comment by dfcreative** [comment]
@etpinard published!

**Comment by etpinard** [comment]
Amazing job @dfcreative ... merging :tada:

**Pull request merged**
