### PR TITLE
Allow clickable legend group titles when group has no pie-like traces

### LINKED ISSUE #5765: Clickable legend group title
_Originally posted by @rithwikjc in https://github.com/plotly/plotly.js/issues/5260#issuecomment-860032962_

I'd like to request that the additional functionality of the `legendgrouptitle` having the clickable behavior of toggling the whole group, be added along with this feature introduction.

### PR DESCRIPTION
**Pull request by archmoj**
Resolves #5765.

@plotly/plotly_js

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
The title-clicking is fine, but actually if you look at this pen https://codepen.io/nicolaskruchten/pen/LYyPvMq you'll see that when you have a mixture of pies and scatters we already have some weird bug where the pie disappears and leaves a black square.

My vote would be to have clicking on a title behave exactly like clicking on a non-pie legend item, including when pies are present, and then to log a bug for the weird black-square behaviour and solve it all at once. Let's not introduce new behaviour for the title, let's just follow the current (buggy) pattern.

**Comment by nicolaskruchten** [comment]
(note: the black-square behaviour exists in 2.1.0 also, so it's not new here)

**Comment by archmoj** [comment]
So you suggest that when a legend group has a title, 
1. clicking on the group title show/hide all traces within that group, and
2. clicking on the trace legend show/hide only that trace.
Right?

**Comment by nicolaskruchten** [comment]
No, I'm saying that clicking on the title should have the same effect as clicking on a non-pie trace marker.

**Comment by rithwikjc** [comment]
>     2. clicking on the trace legend show/hide only that trace.
Since the `legendgrouptitle` would be a toggle for the whole group, it would be really really awesome if the individual trace legends now act as independent toggles for that trace only, instead of an all-traces-within-group toggle. 👀

**Comment by nicolaskruchten** [comment]
@rithwikjc yes, your enthusiasm for this feature is noted :) That specific behaviour change request is tracked in this issue https://github.com/plotly/plotly.js/issues/3135 and once implemented it will not be on by default, rather it will be opt-in with a specific attribute in `layout`.

**Comment by rithwikjc** [comment]
Thank you so much @nicolaskruchten. I am a student and hence by no means capable of sponsoring anything. But I do program, but am yet to venture deep into JS. And once I am capable I hope to contribute to this and other open source projects.
And although this would be a neat feature addition to have on a project I am working on, it is far from required. I'm also just enthusiastic about making this newly added feature set intuitive and well rounded. :)

**Comment by alexcjohnson** [comment]
This works great for non-pie traces. But for pie-only situations this makes the bug much worse so I'm not really in favor of merging this as is. Either we should exclude pies entirely for now or we should sort it all out at once.

For example if I hide both of the slices in Third Group I get this:
Screen Shot 2021-07-16 at 7 05 35 PM
But if I hide the group, the item names and colors disappear, I just see a black square (which isn't even faded) and no label:
Screen Shot 2021-07-16 at 7 09 44 PM
Worse, if I hide the first group, its title disappears and I can't get the group back:
Screen Shot 2021-07-16 at 7 11 52 PM


When we do fix this, I'd think hiding all slices in a group should be exactly equivalent to hiding the whole group, such that in both cases the group title fades, all slices are still in the legend but faded as well, and in both cases you can click a single slice to bring just that one back (which unfades the title). When you've hidden one slice in a group, clicking the title should hide them all (Because it's not faded when you click it) but then clicking it again should show all slices, not bring you back to one hidden slice.

**Comment by nicolaskruchten** [comment]
I agree this behaviour is bad but I'm very skeptical that anyone is using pies and legend groups in the wild.

**Comment by alexcjohnson** [comment]
Then can we just disable clicking the group title when there are any pies in the plot?

**Comment by nicolaskruchten** [comment]
That was the original implementation in this PR... I can live with it.

**Review by alexcjohnson — APPROVED** [review]
💃 Thanks @archmoj, looks great. And @nicolaskruchten my apologies for not digging into this earlier, could have saved some of this whiplash.

**Pull request merged**
