### PR TITLE
Catch unexpected chars at build time

### PR DESCRIPTION
**Pull request by archmoj**
Guard against issue #5382.

@plotly/plotly_js

### CODE REVIEW

**Comment by archmoj** [comment]
Also noticed in https://github.com/plotly/plotly.js/pull/5416#issuecomment-761556093.

**Comment by alexcjohnson** [comment]
I'm not quite sure I understand this rule, it looks like it only applies to regular expressions in the code. Can you verify that this command fails prior to the fix in #5382?

**Comment by archmoj** [comment]
> I'm not quite sure I understand this rule, it looks like it only applies to regular expressions in the code. Can you verify that this command fails prior to the fix in #5382?

Yes I did verify that. Eslint catched the problem. But I am not 100% sure about that rule. Maybe we could just run eslint with an empty rule?

**Review by alexcjohnson — APPROVED** [review]
> Maybe we could just run eslint with an empty rule?

Haha interesting concept - yes, I suppose if eslint is simply unable to parse the file it would fail even without a rule. Anyway since you've shown this is a valuable check, let's go with it as is. 💃

**Pull request merged**
