### PR TITLE
clickable text in legend

### PR DESCRIPTION
**Pull request by suhas-gavas**
Thanks for your interest in plotly.js!

Developers are strongly encouraged to first make a PR to their own plotly.js fork and ask one of the maintainers to review the modifications there. Once the pull request is deemed satisfactory, the developer will be asked to make a pull request to the main plotly.js repo and may be asked to squash some commits before doing so.

Developers should `git rebase` their local branch off the latest `master` before opening a pull request.

Note that it is forbidden to force push (i.e. `git push -f`) to remote branches associated with opened pull requests. Force pushes make it hard for maintainers to keep track of updates. Therefore, if required, please `git merge master` into your PR branch instead of `git rebase master`.

### CODE REVIEW

**Comment by etpinard** [comment]
Hi. Thanks for the PR. What does it do?

**Comment by suhas-gavas** [comment]
Hello,

A very minor change is added to current PlotlyJS version.

I had a requirement in which a partial legend text should be clickable and can act as a href. So I made a code change to legend section(draw.js) in which user can have a text partially href and still user can toggle legend. Basically setting a text href support

Example:

My series now can have a name as “text 1 <a href = “#” onclick = “some action”>click here</a>”

And then in legend “click here” will take user to desire page set in href or event action set in onclick.

Hope this helps with the explanation.

Suhas Gavas
Lead Software Engineer - Mobile
High Impact Innovation - GE Digital

**Comment by suhas-gavas** [comment]
Thanks for the response. Sure to scrap if something gives buggy behavior. I hope someday there will be support for that.

Suhas Gavas
Lead Software Engineer - Mobile
High Impact Innovation - GE Digital

**Comment by etpinard** [comment]
Closed due to lack of of activity.

**Comment by etpinard** [comment]
@suhas-gavas feel free to open up an [issue](https://github.com/plotly/plotly.js/issues/new) explaining your rationale about this feature request.

**Pull request closed without merging**
