### PR TITLE
Fixing the non-fancy scattergl 'single data point' infinite loop

### PR DESCRIPTION
**Pull request by monfera**
Purports to fix https://github.com/plotly/plotly.js/issues/1164

### CODE REVIEW

**Comment by etpinard** [comment]
@monfera looks good!

Wanna add a test for it in https://github.com/plotly/plotly.js/blob/master/test/jasmine/tests/gl2d_scatterplot_contour_test.js ?

**Comment by monfera** [comment]
@etpinard absolutely! Planning to do so over the weekend.

**Comment by monfera** [comment]
@etpinard I ended up putting the single-point case into a preexisting image test, because both the fixed calculation edge case and (potential) rendering edge cases can be detected this way. For example, the `gl.drawArrays` call is constrained to the visible `x` domain, and zero-domains established by a single point may trigger issues.

**Comment by etpinard** [comment]
Beautifully done. Thanks very much @monfera !!

**Pull request merged**
