### PR TITLE
Add clustering to scattermapbox

### PR DESCRIPTION
**Pull request by elben10**
Supersedes #5147.

I've added a trace that allow one to use [mapbox clustering layer](https://docs.mapbox.com/mapbox-gl-js/example/cluster/).

Currently it doesn't support the fill, selection and text features.

TODO: 
 - [ ] add jasmine test for `hover`
 - [ ] add jasmine tests to ensure `Plotly.react` can switch between modes i.e. with/without `cluster`
 - [ ] add second mock & baseline using new attributes e.g. `step` and `opacity`

### CODE REVIEW

**Comment by archmoj** [comment]
Thanks @elben10 for opening this PR.
I updated the description and added various test to the TODO list mainly to ensure the correct functionality would be maintained in future.

**Comment by archmoj** [comment]
@elben10 Before adding tests please [sync](https://digitaldrummerj.me/git-sync-fork-to-master/) the master branch of your fork with plotly/plotly.js. 
Then run ```git merge upstream/master``` into your branch.
Thank you!

**Comment by nicolaskruchten** [comment]
A small update on timing: our team is working hard on releasing v2.0 of Plotly.js, which we anticipate will happen in early April. This PR would be a good candidate to land in the library in v2.1 or later, so with apologies for the delay, we will likely not be able to give much feedback on this PR for the next few weeks :)

**Comment by archmoj** [comment]
There is a conflict in test/jasmine/tests/mock_test.js
@elben10 Wondering if you could possibly pull upstream/master and resolve the conflict by accepting incoming changes please?

**Comment by archmoj** [comment]
@elben10 Are you planning to reopen this interesting PR after resolving that little conflict?
If needed I'd be happy to help : )

**Comment by elben10** [comment]
Sure

**Comment by archmoj** [comment]
:dancer:
Merging into `finalist-cluster-scattermapbox` dev branch.
Thanks @elben10 for the hard work :trophy: :1st_place_medal: 
I'll reopen a PR to target `master` after resolving the conflicts and adjusting the tests.

**Comment by elben10** [comment]
Sounds great. Thanks for the guidance and support! 🥇 👍

**Pull request merged**
