### PR TITLE
Bump has-hover

### PR DESCRIPTION
**Pull request by dfcreative**
Enable better hover detection

resolves https://github.com/plotly/plotly.js/issues/1889

@etpinard

### CODE REVIEW

**Comment by etpinard** [comment]
@dfcreative Thanks for fix! :tada: 

Can you make a standalone page with patch so that we can test it on browserstack?

**Comment by rreusser** [comment]
At risk of interfering, does this work? https://codepen.io/rsreusser/full/qjGvxN/

**Comment by dfcreative** [comment]
@rreusser yep.
Here is the standalone page https://dfcreative.github.io/plotly-contrib/has-hover

**Comment by alexcjohnson** [comment]
Can someone with an android phone try this out? It fails for me for Chrome on the android devices I tried on browserstack, but works on my wife's google pixel. Everywhere else I've tried it seems to work great.

**Comment by etpinard** [comment]
`hasHover` works for me on Android Chrome 59.0.3071.125

**Comment by alexcjohnson** [comment]
Alright - I'm willing to assume there's something funny going on with browserstack in that regard, since it seems to work on all the devices we can actually get our hands on. Thanks @rreusser and @dfcreative ! 💃

**Comment by etpinard** [comment]
@dfcreative by the way :dancer: means: you're free to merge. We let plotly dev merge their own PRs. That means more commits on `master` for you :checkered_flag:

**Pull request merged**
