### PR TITLE
Handle NaN positions in funnel & waterfall and skip connectors over rangebreaks 

### LINKED ISSUE #4631: Bars with NaNs as positions lead to console errors
Go to https://codepen.io/etpinard/pen/YzXeooZ?editors=0010 open the console, you should see:

```
Error: <path> attribute d: Expected number, "MNaN,620V620HNaNV…".
```

As detected in https://github.com/plotly/plotly.js/pull/4614#issuecomment-597253006 (but this happens w/o setting axis breaks!)

----

From @archmoj https://github.com/plotly/plotly.js/pull/4614#issuecomment-597263534 :

Something went wrong in [v1.50.0](https://github.com/plotly/plotly.js/releases/tag/v1.50.0) | [demo-console-error](https://codepen.io/MojtabaSamimi/pen/abOEerE?editors=1000).
Possibly a side effect of `Add transition support to bar trace length, width, on-graph text positioning,
marker style and error bars` [#4180, #4186]

https://github.com/plotly/plotly.js/pull/4614#issuecomment-597266796 - It could be related to 

Screenshot from 2020-03-10 15-18-07

in https://github.com/plotly/plotly.js/pull/4180/commits/f49828a05fdf593097083842b31cbc2f8f777c11

### PR DESCRIPTION
**Pull request by archmoj**
Follow up of #4614, 
this PR fixes #4631 for `funnel` & `waterfall`.
As well it fixes error in drawing a `connector` over a `rangebreak`.

[Before](https://codepen.io/MojtabaSamimi/pen/GRJGwBR?editors=0010) | [After](https://codepen.io/MojtabaSamimi/pen/OJVErmm?editors=0010).

TODO:
- [x] fix `waterfall` and add test
- [x] fix `funnel` and add test

@plotly/plotly_js

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Looks good, nice find! This is for when the connector enters or exits the break, what if the connector completely crosses the break? Does that already work?

**Comment by archmoj** [comment]
> Looks good, nice find! This is for when the connector enters or exits the break, what if the connector completely crosses the break? Does that already work?

Already works: [before](https://codepen.io/MojtabaSamimi/pen/eYNjJXo?editors=1000) | [after](https://codepen.io/MojtabaSamimi/pen/eYNjJXo?editors=0010)

**Comment by archmoj** [comment]
Please wait. 
Still there is an error in this [demo](https://codepen.io/MojtabaSamimi/pen/NWqBrWK?editors=0010).

**Comment by archmoj** [comment]
> Please wait.
> Still there is an error in this [demo](https://codepen.io/MojtabaSamimi/pen/NWqBrWK?editors=0010).

Resolved. I was using the old bundle!

**Comment by archmoj** [comment]
@alexcjohnson this is PR is ready for second review.

**Pull request merged**
