### PR TITLE
Add support for multiple subplots to fx.hover()

### PR DESCRIPTION
**Pull request by john-soklaski**

### CODE REVIEW

**Comment by etpinard** [comment]
@john-soklaski thanks for this very impressive PR. :beers: 

I think you've got every detail right.

I did found some unexpected behavior when `layout.hovermode` is set to `'y'`, but it may just be the result of an existing bug not introduced by your patch. I'll investigate a little more next week.

To see what I'm referring to, paste the following in the test dashboard:

```js
var gd = Tabs.fresh();

Plotly.plot(gd, [{
    x: [1,2,3]
}, {
    x: [2.1,2],
    xaxis: 'x2'
}, {
    x: [3,2,1],
    xaxis: 'x3'
}], {
    xaxis: {
        domain: [0,0.3],
    },
    xaxis2: {
        domain: [0.35, 0.65]
    },
    xaxis3: {
        domain: [0.7, 1]
    },
    hovermode: 'y'
});

gd.on('plotly_hover', function(d) {
    Plotly.Fx.hover(gd, { yvals: d.yvals[0] }, ['xy', 'x2y', 'x3y']);
});
```

Berfore merging this we'll need to add some tests in [`test/jasmine/tests/hover_label_test.js`]
(https://github.com/plotly/plotly.js/blob/master/test/jasmine/tests/hover_label_test.js). Let us know if you need help with our testing framework.

**Comment by john-soklaski** [comment]
Thanks for reviewing!

I think the issue in your example may be due to a typo. I ran your example, and it only hovered on the middle points of the graph no matter where I placed my mouse. But, after debugging a bit, I found `fx.hover` selects the center of the x / y axis if no other points / values are specified: 

https://github.com/plotly/plotly.js/blob/dd1547992013505889ac6ff3294546db79c9f882/src/plots/cartesian/graph_interact.js#L404-L416

It wasn't using the provided `yvals` property. Once I changed `yvals` to `yval`, the `'y'` hovermode seemed to work:
`{ yvals: d.yvals[0] }` -> `{ yval: d.yvals[0] }`

|  

|  

|   


I added some unit tests for both stacked subplots with a shared x-axis and a shared y-axis.
Do they seem sufficient? 

I'd also like to test that the hover labels appear in each of their corresponding subplots. The positioning of these was an issue earlier on and it's something I could see regressing. What do you think is the most stable way to test this?

I took your example from above and added it as a mock so I could use it in a unit test.
The integration is failing due to a missing baseline image, because of the new mock. Is there a way to grab the generated image from the CI server?

**Comment by etpinard** [comment]
> Is there a way to grab the generated image from the CI server?

Yes. Find the artefact tab on your latest commit's CircleCI [page](https://circleci.com/gh/plotly/plotly.js/744):

image

Download the new baseline and commit it in [`test/image/baselines`](https://github.com/plotly/plotly.js/tree/master/test/image/baselines).

**Comment by john-soklaski** [comment]
Thanks! Didn't realize I had to login in order to access the artifacts. I added the baseline and it all seems to be working now.

**Comment by etpinard** [comment]
An early candidate for PR of year. Thank you very much.

**Comment by deechiw** [comment]
Does this hover work for plotly with python on subplots of different types as in the issue [2114](https://github.com/plotly/plotly.js/issues/2114)

**Comment by drypatrick** [comment]
> Thanks for reviewing!
> 
> I think the issue in your example may be due to a typo. I ran your example, and it only hovered on the middle points of the graph no matter where I placed my mouse. But, after debugging a bit, I found `fx.hover` selects the center of the x / y axis if no other points / values are specified:
> 
> https://github.com/plotly/plotly.js/blob/dd1547992013505889ac6ff3294546db79c9f882/src/plots/cartesian/graph_interact.js#L404-L416
> 
> It wasn't using the provided `yvals` property. Once I changed `yvals` to `yval`, the `'y'` hovermode seemed to work: `{ yvals: d.yvals[0] }` -> `{ yval: d.yvals[0] }`
> 
> | | |
> 
> | |
> 
> I added some unit tests for both stacked subplots with a shared x-axis and a shared y-axis. Do they seem sufficient?
> 
> I'd also like to test that the hover labels appear in each of their corresponding subplots. The positioning of these was an issue earlier on and it's something I could see regressing. What do you think is the most stable way to test this?
> 
> I took your example from above and added it as a mock so I could use it in a unit test. The integration is failing due to a missing baseline image, because of the new mock. Is there a way to grab the generated image from the CI server?

Thanks both @etpinard @john-soklaski, I had been looking for this feature for months

**Pull request merged**
