### PR TITLE
load maki icon

### PR DESCRIPTION
**Pull request by birkskyum**
@archmoj, links to icons/sprites are usually inside the style.json itself, but for compatibility if a [maki icon](https://labs.mapbox.com/maki-icons/) (gh [repo](https://github.com/mapbox/maki)) is detected as missing, this PR will make sure it's downloaded and rendered. 

Screenshot 2024-07-26 at 19 02 23

### CODE REVIEW

**Comment by archmoj** [comment]
Thanks very much for the PR.
Please download & update new baselines from https://app.circleci.com/pipelines/github/plotly/plotly.js/10929/workflows/4bdb5573-f32a-4762-97d1-054c349c9dfd/jobs/240837/artifacts

**Comment by birkskyum** [comment]
You're very welcome. They are update now.

**Comment by birkskyum** [comment]
@archmoj setting  `marker.color: '#ffff00',` (yellow) appear to change the color of the line between the icons for both mapbox/maplibre.

**Comment by birkskyum** [comment]
This is an area where both mapbox/maplibre are too strict. We're planning to add proper SVG support, which would make things easier to style and improve in other areas too - https://github.com/maplibre/maplibre/discussions/175.

**Comment by archmoj** [comment]
Please add `'map_angles'` to `isOtherFlaky` list in `test/image/compare_pixels_test.js`.
Thank you!

**Comment by archmoj** [comment]
:dancer:
Thanks very much.
FYI  I'll fix the `b64` image test on my PR.

**Pull request merged**
