### PR TITLE
Drop contourgl and pointcloud traces from the code and API

### LINKED ISSUE #4962: Any support for contourgl?
I have a feature on my app that could display up to 10+ different contour plots. Once it hits about 10+, the performance is affected. I know that there is a `contourgl` plot option, but after looking through some of the other issues, it seems that it is not very supported and has many bugs.

I have tried to use it as well and ran into some issues (think it was something to do with the shader). I'm wondering if there has been any improvements to `contourgl` or if there is another solution to getting faster performance while using `contour` (maybe via canvas instead of svg)?

### LINKED ISSUE #5092: There are three heatmapgl in the submap, but only one is shown
1. There are three heatmapgl in the subplots, but only one is shown
2. Heatmapgl and scattergl cannot coexist in the subplots, heatmap can, but I need to use heatmapgl

**TypeError: Cannot read property 'select' of undefined**

### PR DESCRIPTION
**Pull request by archmoj**
Closes #4962 while addressing #5395 & #897.

The first commit https://github.com/plotly/plotly.js/pull/5398/commits/881c41791f59fb9699380c522bdc7d497666a0c9
cleaned up `pointcloud`, `contourgl`, `heatmapgl` traces as well as `gl2d` subplots.

The second commit https://github.com/plotly/plotly.js/pull/5398/commits/530281a439a51896167b3c9a01c9ec86b5ff7a83 re-implemented `heatmapgl` while adding notes considering that `heatmapgl` is the only trace left using `plots/gl2d` and not `plots/cartesian`.

So I won't be surprised if one could optimize files in `plots/gl2d` or modules e.g. `gl-plot2d v1.4.5`, `gl-select-box v^1.0.4` and `gl-spikes2d v1.0.2`.

@plotly/plotly_js

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
This PR is dropping `heatmapgl`, which we had discussed not doing, right?

**Comment by archmoj** [comment]
> This PR is dropping `heatmapgl`, which we had discussed not doing, right?

In the following commits, we could attempt maintaining `pointcloud` and `heatmapgl` APIs via `scattergl` and `image` and use `plots/cartesian` instead of `plots/gl2d` as we already do for `scattergl`. Keeping `plots/gl2d` just for `heatmapgl` which does not even support two subplots in v2 make little sense.

**Comment by nicolaskruchten** [comment]
> attempt maintaining pointcloud and heatmapgl APIs via scattergl and image 

Please let us not do this. We should be dropping `pointcloud` and `contourgl` today and not reimplementing pointcloud in terms of scattergl, and not dropping heatmapgl. 

We can talk about dropping heatmapgl in the meeting tomorrow if you like.

**Review by alexcjohnson — APPROVED** [review]
Beautiful! 💃

**Pull request merged**
