### PR TITLE
JOSS submission for whole ecosystem

### PR DESCRIPTION
**Pull request by nicolaskruchten**
I am preparing a submission to the Journal of Open Source Software (JOSS) for the whole Plotly visualization ecosystem (Javascript, Python, R, Julia). Their process is outlined here https://joss.readthedocs.io/en/latest/submitting.html and I've kicked off the conversation here https://github.com/openjournals/joss/issues/928 to validate this "one big paper" approach.

Here's an example of what the final output could look like https://joss.theoj.org/papers/10.21105/joss.01057 and the corresponding artifacts in the repo that led to it https://github.com/altair-viz/altair/tree/master/paper.

This PR is currently a stub and eventually should be merged to master when everyone involved is happy with what the paper looks like, how their name/affiliation etc is represented, and then I'll make the JOSS submission as the "corresponding author" unless anyone objects. @alexcjohnson will be looking after the order of the author list.

I'll work on the body of the paper in the next little bit and ask for comments once I'm done, but I'm kicking things off here so as to notify all the potential co-authors below and start getting everyone comfortable with the process and opting in to authorship :)

Since this paper will cover the whole ecosystem for the four languages mentioned, I propose the following folks as co-authors (in no particular order, and with sincere apologies if I've left anyone out!)... everyone will have to opt IN and anyone can nominate any other major contributors:

* [x] @etpinard 
* [x] @archmoj 
* [x] @alexcjohnson 
* [x] @chriddyp 
* [x] @jackparmer 
* [x] @cpsievert
* [x] @sglyon
* [x] @theengineear
* [x] @antoinerg 
* [x] @jonmmease
* [x] @emmanuelle 
* [x] @Kully 
* [x] @cldougl 
* [x] @mdtusz
* [x] @bpostlethwaite 
* [x] @monfera
* [x] @nicolaskruchten 
* [x] @mikolalysenko
* [x] @kig 
* [ ] @nicholas-esterer 
* [ ] @rreusser
* [ ] @dy 
* [ ] @n-riesco

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Ah drat, I forgot to set up a process for opting in... If you want in on this, please comment on this PR or suggest a change to the `paper.md` adding your name and affiliation the way you'd like it to look.

**Comment by bpostlethwaite** [comment]
Sure please add me! 

Ben Postlethwaite https://github.com/bpostlethwaite

is fine.

**Comment by Kully** [comment]
Yes, good with me too!

Adam Kulidjian https://github.com/kully

**Comment by mdtusz** [comment]
Happy to be included as well.

Miklós Tusz https://github.com/mdtusz

**Comment by monfera** [comment]
Thanks for the inclusion!

Robert Monfera https://github.com/monfera

**Comment by mikolalysenko** [comment]
Sounds good to me

**Comment by antoinerg** [comment]
Happy to be included as well!

**Comment by cldougl** [comment]
sure :) 
Chelsea Douglas https://github.com/cldougl

**Comment by archmoj** [comment]
@kig :arrow_up:  
Ilmari Heikkinen https://github.com/kig

**Comment by jonmmease** [comment]
:+1: 
Jon Mease - @jonmmease

**Comment by emmanuelle** [comment]
Thanks, happy to be included as well!

**Comment by kig** [comment]
@archmoj Thanks, would be delighted!

**Comment by theengineear** [comment]
While I haven't contributed in while, I'd love to be included as well. Thanks!

**Comment by nicolaskruchten** [comment]
Thanks all! Now that I've got buy-in from everyone I actually need to write this thing so you'll have something to comment on... stay tuned :)

**Comment by Kully** [comment]
> Thanks all! Now that I've got buy-in from everyone I actually need to write this thing so you'll have something to comment on... stay tuned :)

Hey @nicolaskruchten , just (re)found this PR 😅 (you can ignore my email question to you haha)

I'm curious what the status is for the paper writing (`stable-image`). Excited to hear back.

Hope everyone else in here is doing very well. 🙏

- Adam

**Comment by nicolaskruchten** [comment]
Hey @Kully ! I still want to do this but I continue to not find the time :)

**Comment by Kully** [comment]
> Hey @Kully ! I still want to do this but I continue to not find the time :)

Is there any way I can help with the drafting? I've been in "writing mode" recently with clients/personal projects, so I might be of help.

Best,

**Comment by gvwilson** [comment]
can this one be closed now?

**Comment by nicolaskruchten** [comment]
Yes, despite best intentions, I never got around to this and it doesn't seem like I'll be able to any time soon :(

**Pull request closed without merging**
