### PR TITLE
Scatterpolargl

### PR DESCRIPTION
**Pull request by dfcreative**
Replaces #2200 and #1869

### CODE REVIEW

**Comment by dfcreative** [comment]
@etpinard may I ask you to run the tests in Ubuntu machine, I cannot reproduce the CI errors locally.

**Comment by etpinard** [comment]
@dfcreative sure, I'll give it a shot at some point today.

But back in https://github.com/plotly/plotly.js/pull/1869/commits/25fd2e4dde786b9524d371507e8438d1e893c322 from https://github.com/plotly/plotly.js/pull/2200, the tests passed on CI. Something must have happened since?

**Comment by dfcreative** [comment]
@etpinard merged master in case. Except for switching to regl nothing changed for the matter. Not sure why I cannot reproduce these errors on windows/Chrome.

**Comment by etpinard** [comment]
Well something _must_ have changed. I'll looked into it.

**Comment by etpinard** [comment]
@dfcreative don't push to this branch anymore. It is non-trivially behind `master`. 

Please use https://github.com/plotly/plotly.js/tree/scatterpolargl-2018

**Pull request closed without merging**
