### PR TITLE
Bar: fix issue #372 - bar widths with nonnumeric sizes

### PR DESCRIPTION
**Pull request by seibs**
PR for seibs#1
Fixes issue #372

Bars were being filtered out too soon when they had a non-numeric size. This change leaves them in so the bar width/placement calculations take them into account, and leaves filtering them out to the logic already in src/traces/bar/plot.js.

### CODE REVIEW

**Comment by etpinard** [comment]
Great. 

As mentioned in https://github.com/plotly/plotly.js/issues/539, your patch also fixes a very old bug that made it through our image test mocks.

Before merging this PR, you'll have to update the [`benchmark.png`](https://github.com/plotly/plotly.js/blob/master/test/image/baselines/benchmarks.png) image baseline.

To do so, (1) go to https://circleci.com/gh/plotly/plotly.js/1457 and click on the _Artifact_ tab:

image

(2) navigate to the `test_images` folder: 

image

(3) download the `benchmark.png` image and (4) finally replace `test/image/baselines/benchmarks.png` with it

**Comment by seibs** [comment]
Whoops, missed you're comment in #539.

The only tabs visible on circleci were "Test Summary", "circle.yml", and "Build Timing" so I generated the png following the directions in the test/image/README.md.

**Comment by n-riesco** [comment]
I had the same problem and I noticed that you need to log into CircleCI for the Artifacts tab to be visible.

**Comment by etpinard** [comment]
@seibs Thanks! You get my vote for PR of the week :trophy: .

**Pull request merged**
