### PR TITLE
fix and test annotations with mathjax

### LINKED ISSUE #1787: annotations with mathjax are misaligned
for example, in the annotations mock, do `Plotly.relayout(gd,{'annotations[14].text':'$x+y+z+q$'})`
on 1.27.1 we get the expected:
screen shot 2017-06-14 at 11 41 53 am
But current master is broken:
screen shot 2017-06-14 at 11 47 31 am

### PR DESCRIPTION
**Pull request by alexcjohnson**
fixes #1787 - the bug came in when we simplified the class structure of annotation elements.
@etpinard another quick fix - lets hope the test image works consistently on CI. If it does, I'll probably add some more mathjax image tests (for elements other than annotations) when I tweak `drawing.bBox` for #1782

### CODE REVIEW

**Comment by etpinard** [comment]
image

Hmm. Looks like CI doesn't like MathJax intermittently.

**Comment by alexcjohnson** [comment]
> Hmm. Looks like CI doesn't like MathJax intermittently.

Annoying. I guess this is probably the same sporadic delay we saw in https://github.com/plotly/streambed/issues/9508

I guess what I'll do is take MathJax out of the annotations mock, and make one MathJax mock that we skip in CI for now but tries to cover *everywhere* we support MathJax at present.

**Comment by etpinard** [comment]
> I guess what I'll do is take MathJax out of the annotations mock, and make one MathJax mock that we skip in CI for now but tries to cover everywhere we support MathJax at present.

Very good idea, until we have more time to investigate plotly/streambed#9508

To do so, just add one expression to this [filter](https://github.com/plotly/plotly.js/blob/master/test/image/compare_pixels_test.js#L104) function.

**Comment by alexcjohnson** [comment]
Actually I made a mistake in 033bee3 - fixed in b0d1af2 - that means it's likely MathJax will work fine on CI after all. But I found a bunch of other issues when developing a more complete MathJax test mock so I'm going to defer that to a separate PR if you don't mind.

**Comment by etpinard** [comment]
> so I'm going to defer that to a separate PR if you don't mind.

Sounds good.

**Comment by etpinard** [comment]
:dancer: :dancer: :dancer:

**Pull request merged**
