### PR TITLE
Revise textposition default for bar, histogram and waterfall

### LINKED ISSUE #5624: Text position defaults in v2
When setting `text` or `texttemplate` in `bar`-likes one should not also have to set `textposition` in principle, right?

### PR DESCRIPTION
**Pull request by archmoj**
Resolves #5624.

@plotly/plotly_js

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
> But if text is a string, that was probably meant only to show in hover

I can see what you mean, but this seems like really edge-case behaviour, probably used in cases where folks didn't want to rename the trace or something? Sure, let's carve something out for that.

**Comment by archmoj** [comment]
> Looking particularly at the [histogram-offsetgroups](https://github.com/plotly/plotly.js/pull/5638/files?short_path=ce2891e#diff-ce2891e99e98be02836d427be1dae8d852c6d8ef55c34f2d04db1ddf85c2f388) mock, I'm wondering if we shouldn't be a little more nuanced about this: if `text` is an array, default `textposition='auto'`. But if `text` is a string, that was probably meant only to show in hover so default to `textposition='none'`.
> 
> We have no such logic for scatter, but in that case it's fairly common to want all markers in a trace to get the same text - the text may even BE the marker.
> 
> I could could go either way on this, just wanted to throw it out there. The "always auto" logic is nice for its simplicity, and I'd do it this way if starting fresh, it just may break more graphs than we would need to with the v2 upgrade. @nicolaskruchten @archmoj thoughts?

`Bar` and `histogram` do not have `textinfo` at the moment; but `waterfall` has.
BTW using `textinfo` or `texttemplate` people could include additional info such as values in the text.
I think depending on the type of text to be an array to enable so called `auto` behaviour is rather confusing.
Concerning the histogram baseline change, it seems to me the labels actually helped improve the graph.
Sure there might be cases that this may not be desirable; but then it would be as easy as using the `none` option.

**Review by alexcjohnson — APPROVED** [review]
Right, thinking about this more, especially with all the other work we're doing to simplify defaults for v2, making this conditional default seems like a step backward.

So to me this is good to go 💃  unless @nicolaskruchten wants to argue for sticking with my previous suggestion 😅

**Comment by nicolaskruchten** [comment]
I'm good, please merge :)

**Pull request merged**
