### PR TITLE
Bump jasmine 3 to 4

### PR DESCRIPTION
**Pull request by birkskyum**
Update Jasmine to v4 ( v5.1 is the latest, but that's too large a step )

[Changelog](https://github.com/karma-runner/karma-jasmine/blob/master/CHANGELOG.md)

[Migration guide](https://jasmine.github.io/upgrade-guides/4.0)

In order to make the bundle test suite work, I had to find/replace `.then(done)` with `.then(()=>{done()})`

### CODE REVIEW

**Comment by birkskyum** [comment]
4 jasmine tests left that still break, all with `  Unhandled promise rejection: undefined thrown`

**Comment by archmoj** [comment]
I see more failing tests in 8 containers:
Screenshot_20240819-174145

**Comment by birkskyum** [comment]
hit a bit of a wall with the last ones. the stacktraces from webpack doesn't appear to have sourcemaps so the line numbers doesn't match source code

**Comment by archmoj** [comment]
I don't know if any of these commits from my previous attempt might be useful?
https://github.com/plotly/plotly.js/tree/upgrade-d3-to-v4

**Comment by birkskyum** [comment]
No, that's for bumping d3. This pr is for bumping Jasmine

**Comment by archmoj** [comment]
Also if I recall there should be a webpack config for webpack to match line numbers.

**Comment by archmoj** [comment]
Correct old branch:
https://github.com/plotly/plotly.js/tree/jasmine-v4

**Pull request closed without merging**
