### PR TITLE
ensure newRng stays in bounds

### PR DESCRIPTION
**Pull request by jay-bis**
Created a few checks to make sure the slider's range doesn't go out of its normal bounds. This is an attempt to fix the bug outlined by this [gif](https://aws1.discourse-cdn.com/business7/uploads/plot/original/2X/2/28399259ce54005c63f46e4c2920a887593aa3c2.gif).

I'm not sure what the preferred behavior would be when you do drag the slider to the max/min bounds, but what this solution does is snap the slider back to the graph's corresponding max/min x value when the slider is dragged past the max/min.

### CODE REVIEW

**Comment by etpinard** [comment]
Hi @jay-bis - are you attempting to fix the same bug as presented in https://github.com/plotly/plotly.js/issues/4417#issuecomment-569348207 here?

**Comment by jay-bis** [comment]
Yes, I am! My first commit caused some of the tests to fail and was still a bit buggy; my newest commit passed all the tests and seems to work a bit more smoothly, and gets rid of the bug as far as I've tested it.

**Comment by etpinard** [comment]
Ok great - thanks!

Your second commit looks good. Would you be interested in trying to write a few test cases to lock down your fix?

If so, the new tests should be similar to 

https://github.com/plotly/plotly.js/blob/e778644e1182e13126db6b801af6dd0a386372ba/test/jasmine/tests/range_slider_test.js#L152-L202

**Comment by jay-bis** [comment]
For sure! I'll get started on that.

**Comment by klausbreyer** [comment]
@etpinard I just stumbled upon #4417  and wanted kindly ask if there is any chance, that this will be merged in soon?

**Comment by YMNNs** [comment]
@archmoj It really works, please consider merging #4448.

**Comment by archmoj** [comment]
We somehow missed the updates on this PR. 
Thanks very much for the PR.
:dancer:
I am going to release a patch right after.

**Comment by markchagers** [comment]
As of today, this is still an issue even in v2.27
Any chance of this getting fixed for real?

**Pull request merged**
