### PR TITLE
Add way for `toImage` to export images with current graph width/height

### PR DESCRIPTION
**Pull request by etpinard**
resolves https://github.com/plotly/plotly.js/issues/3743 ... in a slightly more general way than proposed in that issue. 

This PR adds special logic to `Plotly.toImage` (which is called by `Plotly.downloadImage`, which is itself called when clicking on the `toImage` modebar button) for options `width:null` and `height:null`.

In brief, `Plotly.toImage(gd, {width:null, height:null})` will use the width/height values found in `gd._fullLayout` to generate its output image. Equivalently, 

```js
Plotly.react(gd, data, layout, {
  toImageButtonOptions: {width: null, height: null}
})
```

and clicking on the `toImage` modebar button will generate an image using the current `gd._fullLayout.width` and `gd._fullLayout.height` values - which (should at least) always store the current graph width/height values.

@plotly/plotly_js @nicolaskruchten - let me know what you think!

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Hah that’s actually what I had initially tried and thought might work so I’m totally down with that approach. /cc @chriddyp

**Comment by chriddyp** [comment]
lgtm!

**Comment by antoinerg** [comment]
Beautiful feature @etpinard !

Could config options `toImageButtonOptions: {width: null, height: null}` be the default when `responsive: true`?

**Comment by etpinard** [comment]
> Could config options `toImageButtonOptions: {width: null, height: null}` be the default when `responsive: true`?

I'd call that a breaking change. For sure in v2 though.

**Comment by antoinerg** [comment]
> I'd call that a breaking change. For sure in v2 though.

Ok, then the only request I have is to add it to the v2 wishlist!

:dancer:

**Comment by etpinard** [comment]
> Ok, then the only request I have is to add it to the v2 wishlist!

:pencil2: in https://github.com/plotly/plotly.js/issues/1576#issuecomment-481015960 - for better context info.

**Pull request merged**
