### PR TITLE
Update bar graph animation PR

### PR DESCRIPTION
**Pull request by rreusser**
This is an updated version of #1143 

To do:
- fix barmode: relative
- test
- object constancy for bar text

### CODE REVIEW

**Comment by jackparmer** [comment]
Nice, is this going in 1.28.0?

**Comment by etpinard** [comment]
Probably not. Those conflicts looks rough and @rreusser is driving coast to coast at the moment.

**Comment by rreusser** [comment]
Aah. Want this in so badly… Not sure I can have it ready for 1.28.0, but I can push and try to get this ready. I'll give this another shot this evening.

**Comment by etpinard** [comment]
Dropping from `1.28.0`. We have more than 300 new commits on master since `1.27.1`; we need to release something ASAP.

**Comment by ajeet007** [comment]
any multi line animation graph example in plotly.js,

thanks,

**Comment by etpinard** [comment]
@ajeet007 please ask you're questions on https://community.plot.ly/ , not on semi-relevant PRs. Thank you.

**Comment by tomhaskins** [comment]
Are animated bar charts still likely to appear in the Master branch? Is this the best place to watch for progress on this?

**Comment by etpinard** [comment]
From that todo list above, looks like this thing was really close to being mergable. Unfortunately, time has passed, and this branch is now way behind master. Closing.

Please refer to https://github.com/plotly/plotly.js/issues/1019 for future development.

**Comment by vanthome** [comment]
Is there no chance this will get merged eventually? I mean this is an essential feature and the second try to get it merged.

**Comment by etpinard** [comment]
@vanthome Closing this PR doesn't mean we'll never implement animating bars. It just won't happen with this PR.

Subscribe to https://github.com/plotly/plotly.js/issues/1019 for the latest development info.

**Pull request closed without merging**
