### PR TITLE
Distribute minified files in own packages

### PR DESCRIPTION
**Pull request by cjwainwright**
The "dist" bundle packages (e.g. https://www.npmjs.com/package/plotly.js-dist) currently only include un-minified JavaScript. This PR is to create a separate package (e.g. `plotly.js-dist-min`) for each of the minified versions of the "dist" files.

### CODE REVIEW

**Comment by cjwainwright** [comment]
@etpinard @archmoj Here are the changes as discussed. Thanks for the feedback :-)

**Comment by cjwainwright** [comment]
Argh, broken tests :-( Haven't got time to decipher that now. Will have to look another day.

**Comment by etpinard** [comment]
image

You just need to remove a trailing white space.

**Comment by etpinard** [comment]
Thanks very much. Merging!

**Pull request merged**
