### PR TITLE
Update gl-shader version

### PR DESCRIPTION
**Pull request by dfcreative**
Fixes https://github.com/plotly/streambed/issues/6307

### CODE REVIEW

**Comment by etpinard** [comment]
That will break some of our 3D plots unfortunately. See https://github.com/plotly/plotly.js/pull/931

**Comment by dfcreative** [comment]
Ok, I can set `^4.2.1` for gl-scatter-fancy, that is more local fix

**Comment by dfcreative** [comment]
Ok https://github.com/gl-vis/gl-scatter2d-fancy/pull/1

**Comment by etpinard** [comment]
> Ok, I can set ^4.2.1 for gl-scatter-fancy, that is more local fix

Sounds like a good solution for now.

**Pull request closed without merging**
