### PR TITLE
Drop deprecated `pointcloud` and `heatmapgl` traces and `gl2d` subplots

### LINKED ISSUE #7175: Drop `heatmapgl` for Plotly.js v3

### LINKED ISSUE #7176: Drop `pointcloud` for Plotly.js v3

### PR DESCRIPTION
**Pull request by archmoj**
Closes #7176 and closes #7175.
Users could use `scattergl` and `heatmap` traces instead to draw similar graphs.
@plotly/plotly_js

### CODE REVIEW

**Review by emilykl — APPROVED** [review]
LGTM @archmoj , I don't see any red flags as long as tests are passing

**Comment by archmoj** [comment]
> @archmoj Are `scattergl` and `image` direct drop-in replacements for `pointcloud` and `heatmapgl`? Or are some of the props different?
> 
> Is there a replacement for `gl2d` subplots?

@emilykl No they are not direct drop-in replacements. 
gl2d subplots are only only used for these these two traces and other 2-D WebGL-based traces e.g. scattergl, splom and parcoords do not use it.

**Comment by archmoj** [comment]
@alexcjohnson Would you accept these changes?

**Review by alexcjohnson — APPROVED** [review]
To my understanding it’s actually `heatmap` that replaces `heatmapgl`, ie just “downgrading” to the SVG version gives you the same or better performance with many more features. `pointcloud` is different, `scattergl` is not a drop-in replacement, but it solves the same use cases and many more.

this is great, I highly support these changes 💃

**Pull request merged**
