### PR TITLE
Tickformat "p" fix

### PR DESCRIPTION
**Pull request by etpinard**
fixes https://github.com/plotly/plotly.js/issues/3814 and fixes a bad commit from https://github.com/plotly/plotly.js/pull/3867

before: https://codepen.io/jonmmease/pen/vMMNXJ?editors=1010
after: <strike>https://codepen.io/etpinard/pen/NVpNEV?editors=1010</strike> https://codepen.io/etpinard/pen/yWbVqd?editors=1010

cc @plotly/plotly_js

### CODE REVIEW

**Comment by archmoj** [comment]
@etpinard Thanks for the fix. 
Unfortunately there is another issue with small ranges. See [codepen](https://codepen.io/MojtabaSamimi/pen/OYpjPN?editors=0010) where the Y-axis range is printed as 0 to 100% whereas it should be 0 to 0.01%. 
Could we possibly address that in this PR?

**Comment by etpinard** [comment]
> Y-axis range is printed as 0 to 100% whereas it should be 0 to 0.01%.

Oh boy. Thanks for noticing that!

**Comment by archmoj** [comment]
> > Y-axis range is printed as 0 to 100% whereas it should be 0 to 0.01%.
> 
> Oh boy. Thanks for noticing that!

For the `funnelarea` I would add the following function to the `Lib`. Thought it may be of interest.
<pre>
lib.formatPercent = function(ratio, n) {
    n = n || 0;
    var str = (Math.round(100 * ratio * Math.pow(10, n)) * Math.pow(0.1, n)).toFixed(n) + '%';
    for(var i = 0; i < n; i++) {
        if(str.indexOf('.') !== -1) {
            str = str.replace('0%', '%');
            str = str.replace('.%', '%');
        }
    }
    return str;
};
</pre>

**Comment by etpinard** [comment]
@archmoj how do you compute the `n` passed to your `formatPercent` function?

**Comment by archmoj** [comment]
> @archmoj how do you compute the `n` passed to your `formatPercent` function?
That's the desired precision which in the case of financial traces is 0 or 1. 
But one may pass that after calculating what precision needed or simply by using a higher default e.g. 6.

**Comment by etpinard** [comment]
I'm having second thoughts about my attempt at fixing this bug.

Closing for now.

**Pull request closed without merging**
