### PR TITLE
Fix colorbar of reversescale colorbars of heatmap-coloring contours

### PR DESCRIPTION
**Pull request by etpinard**
fixes https://github.com/plotly/plotly.js/issues/4430

before: https://codepen.io/etpinard/pen/ZEYePxW 
after: https://codepen.io/etpinard/pen/JjoWzYb

cc @archmoj

### CODE REVIEW

**Comment by archmoj** [comment]
Great! Could you please add a test for the case of using coloraxis as well?

**Comment by etpinard** [comment]
Ok I'll add a subplot on the new mock.

But in my opinion, we don't need that as the trace-colorscale vs coloraxis logic is inside `Colorscale.extractOpts` which is already tested elsewhere.

**Comment by archmoj** [comment]
If so, just testing in a codepen is enough.
Thank you!

**Comment by archmoj** [comment]
Concerning `before` codepen it is better to use v.1.51.3 not the latest.

**Comment by etpinard** [comment]
> Concerning `before` codepen it is better to use v.1.51.3 not the latest.

Sure, edited above.

> Great! Could you please add a test for the case of using coloraxis as well?

done in https://github.com/plotly/plotly.js/pull/4437/commits/af025a2a0bc3aaa5c99283e5d8df6f78a1bd52e5

**Comment by archmoj** [comment]
:dancer: :dancer: after all green light on the CI.

**Pull request merged**
