### PR TITLE
Add slider events

### PR DESCRIPTION
**Pull request by rreusser**
Due to a lack of events, sliders that execute custom code in pure JS are very difficult. This PR adds events to sliders:

- `plotly_sliderstart`: emitted when the slider receives a mousedown event
- `plotly_sliderchange`: emitted when the slider receives interaction that changes the selected value. Data contains `interaction: true | false` in order to indicate whether the change was the result of user interaction of some other state change like bindings.
- `plotly_sliderend`: emitted on mouseup

### CODE REVIEW

**Comment by etpinard** [comment]
@rreusser can you give a real world example of these events in action?

**Comment by rreusser** [comment]
`change` would be useful for hooking into a play button. Like performing external updates as an animation progresses. It's more of a notification that the slider moved.

`dragmove` is similar except restricts this to *only* events that were the result of direct input, like for actually performing changes that don't fit into an API command (like computing live data and updating the plot)

`dragstart` and `dragend` are two that I use frequently to do something like pausing a simulation or lowering the resolution while the component is being interacted with.

[here](http://rickyreusser.com/schrodinger-equation-1d-demo) is an example where the simulation pauses during interaction.

[here](http://codepen.io/rsreusser/pen/GjZwYb) is an example that would greatly benefit from the ability to lower resolution while the component is being dragged for a quick preview.

**Comment by rreusser** [comment]
@etpinard what do you think of `sliderstart`, `sliderend`, and `sliderchange`, where `sliderchange` has an `interaction: true | false` flag that notes whether it was the result of interaction or just a more general state change (e.g. bindings)

**Comment by etpinard** [comment]
> what do you think of sliderstart, sliderend, and sliderchange, where sliderchange has an interaction: true | false flag that notes whether it was the result of interaction or just a more general state change (e.g. bindings)?

love it :+1:

**Comment by rreusser** [comment]
This PR has been updated as discussed. The initial description now specifies the *three* events implemented.

**Comment by rreusser** [comment]
@etpinard the individual commits are a little messy since I accidentally committed the linter changes, but the end result is correct (pending circle-ci).

**Comment by rreusser** [comment]
For live example, see: http://rickyreusser.com/animation-experiments/#gapminder

**Comment by etpinard** [comment]
nicely done :dancer:

**Pull request merged**
