### PR TITLE
Align hover label text content with *hoverlabel.align*

### PR DESCRIPTION
**Pull request by etpinard**
resolves https://github.com/plotly/plotly.js/issues/3726 by adding a new attribute under the `hoverlabel` trace and layout containers.

See demo: https://codepen.io/etpinard/pen/MRJvLr?editors=1010

I picked _align_ as its behavior reminded me of `align` in the annotations attributes:

https://github.com/plotly/plotly.js/blob/1dcee933ec8ac0648d6e5fc3476d923d19cb8eb7/src/components/annotations/attributes.js#L87-L99

Let me know if you can think of a better name.

cc @plotly/plotly_js @nicolaskruchten

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
The default is center? I would have thought the default would be “auto” to describe the current behaviour

**Comment by nicolaskruchten** [comment]
Also re the description: this doesn’t just apply to “texts right? It applies to the entire contents of the hoverlabel, even if it’s built with hovertemplate etc?

**Comment by antoinerg** [comment]
> Also re the description: this doesn’t just apply to “texts right? It applies to the entire contents of the hoverlabel, even if it’s built with hovertemplate etc?

`hovertemplate` was implemented so that it reuses all the existing logic. So yes the `hoverlabel.align` does apply to the entire content of the hoverlabel even if it's built with `hovertemplate`! 

I think we could replace \`text\` by text in the description.

> The default is center? I would have thought the default would be “auto” to describe the current behaviour

The default is actually auto. However, `center` is not yet implemented in this PR. @nicolaskruchten is this a requirement?

**Comment by etpinard** [comment]
> The default is center? I would have thought the default would be “auto” to describe the current behaviou

The default is `'auto'`.

**Comment by etpinard** [comment]
Wow. Sorry I made things confusing. The block I pasted in the PR description is in `annotations/attributes.js` not the new `hoverlabel.align` attribute declaration which is:

```js
        align: {
            valType: 'enumerated',
            values: ['left', 'right', 'auto'],
            dflt: 'auto',
            role: 'style',
            editType: 'none',
            description: [
                'Sets the horizontal alignment of the text content within hover label box.',
                'Has an effect only if the hover label text spans more two or more lines'
            ].join(' ')
        },
```

as found in `fx/layout_attributes.js`.

**Comment by antoinerg** [comment]
@etpinard about your https://github.com/plotly/plotly.js/issues/3726#issuecomment-481017727 . Since there are two different things we may want to align, wouldn't it be safer to call this new attribute `textalign` instead of `align`. I could see `align` being used to align with respect to the data points as you pointed out whereas in the current PR we deal with text alignment.

**Comment by etpinard** [comment]
> Since there are two different things we may want to align, wouldn't it be safer to call this new attribute `textalign` instead of `align`

Fair. But you could say the same thing about annotations.

**Comment by nicolaskruchten** [comment]
`center` is not important to me BTW :)

**Comment by etpinard** [comment]
> `center` is not important to me BTW :)

:tada: that's what I thought.

**Comment by nicolaskruchten** [comment]
✨ from me :)

**Comment by antoinerg** [comment]
:dancer: once the tests pass!

**Comment by etpinard** [comment]
Going with `hoverlabel.align` for consistency with annotations.

**Comment by ScottGledhill** [comment]
Screenshot 2019-05-28 at 16 40 05
When no room issues with data it will display in the middle

Screenshot 2019-05-28 at 16 44 14
If the data is on the left itll show an arrow leftwards and text will align this way also

Screenshot 2019-05-28 at 16 40 37
If the data is on the right hand side itll show an arrow right and text will also align this way.

Plotly makes it really really hard to change this default behaviour, and i'm not sure if we should want to, forcing it right on the first screen shot would look weird, and having the arrow pointing left but the text aligned right would also look strange in my opinion.

After discussing with Ameer and Pete, I recommend keeping the default behaviour, if it does need to be done, someone with much more css skills than me will have to pick it up :)

**Comment by nicolaromano** [comment]
Would it be possible to allow center-aligning text as well?

**Pull request merged**
