### PR TITLE
Update Croatian translation with messages and numeric format

### PR DESCRIPTION
**Pull request by Mkranj**
Translated several options in Plotly modebar, as well as popup messages, into Croatian (hr) locale.

## Review
I'd like to ask @krisbak1 as a native speaker to check the translation.

### CODE REVIEW

**Comment by Mkranj** [comment]
Improved translation of certain terms after @krisbak1 's comments.

**Comment by krisbak1** [comment]
Looks good now!

**Comment by Mkranj** [comment]
@archmoj Hi, could you please help me with the failing checks, or direct me to someone who can?  
From what I'm seeing, `flaky-no-gl-jasmine` and `webgl-jasmine` are failing. The first one fails tests such as "@flaky should transition layout when one or more axis auto-ranged value changed", and the second one fails tests such as "@gl should fetch GeoJSON using URLs found in the traces".  
This PR only updates a single localization file, so I wouldn't expect it to influence base Plotly behavior. Could there be an issue with CI/CD? Or somehow a more complex interaction between the localization file and the way Plotly processes charts?

**Comment by archmoj** [comment]
:dancer:
Thanks very much for the PR :trophy: 
This will be included in v2.25.2 patch shortly.

**Pull request merged**
