### PR TITLE
Mock validation utility

### PR DESCRIPTION
**Pull request by archmoj**
Followup of #4762. 
Addressing #4733.
Thanks to #5411, now we could `node.js` for our mock validation :tada:
It is now feasible to run validation tests both locally namely when contributors add new mocks/features to the library, as well as on CircleCI.
While new script does not depend on `browserify` and `jasmine` to resolve and load multiple files all at once, it is more robust now and could remove potential side effects of the previous `mock_test` on parallel runs.

Plus after adding a new mock, it would automatically be tested by this system when there is no need to add its name to the list.

Since we used to run this in `noci_test` right before publishing (and sometimes fail at final moments), the current setup should help reduce all the noise too.

@plotly/plotly_js

### CODE REVIEW

**Comment by alexcjohnson** [comment]
LGTM! Have you seen this fail on CI? ie just push a branch off this one with a purposely invalid addition to a mock, just to make sure it will properly flag failures for us.

**Comment by archmoj** [comment]
> LGTM! Have you seen this fail on CI? ie just push a branch off this one with a purposely invalid addition to a mock, just to make sure it will properly flag failures for us.

Good call. Tested locally and on the CI.
I also added the option to simply test only the mock(s) needed in  https://github.com/plotly/plotly.js/pull/5653/commits/2e8ce24430a7fa8d7ecb0251ddb0fe263e77e326.

**Comment by archmoj** [comment]
Here the CI failing example:
https://app.circleci.com/pipelines/github/plotly/plotly.js/3826/workflows/b8864a65-0b2a-4382-8f02-0743146be98e/jobs/112705/parallel-runs/0/steps/0-103

**Review by alexcjohnson — APPROVED** [review]
Love it. Especially that we can switch from a whitelist to a blacklist (and hopefully over time cut that list down). 💃

**Pull request merged**
