### PR TITLE
Shared canvases

### PR DESCRIPTION
**Pull request by dfcreative**
Comes after https://github.com/plotly/plotly.js/pull/1989.

Makes use of pre-created 3-canvas strategy, so that no new canvases created.

### CODE REVIEW

**Comment by etpinard** [comment]
Hmm. Looks like a bunch of tests are failing after 8915392. By the looks of [it](https://circleci.com/gh/plotly/plotly.js/4958?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), gl contexts aren't getting cleaned up properly, which makes me concerned about the strategy proposed in https://github.com/plotly/plotly.js/pull/1989.

@dfcreative have you tried running `npm run test-jasmine` locally?

**Comment by dfcreative** [comment]
@etpinard I see that there is only one image diff, that is https://4958-45646037-gh.circle-artifacts.com/0/home/ubuntu/plotly.js/build/test_images_diff/diff-gl3d_mirror-ticks.png, and the diff is in antialias.
Although karma cannot run tests in some reason, gotta figure out why.

**Comment by etpinard** [comment]
> I see that there is only one image diff

image


Nop, actually about the image test blow up after ~200 of ~400 mocks to test. So something very problematic is happening.

**Comment by dfcreative** [comment]
@etpinard to run jasmine I had to do this fix: https://github.com/plotly/plotly.js/pull/1994, please check.
Gotta figure out the rest.

**Comment by dfcreative** [comment]
@etpinard now tests pass fine. Should I create a separate PR for just shared canvases, skipping parcoords changes, or just cherry-pick changes into `regl-` components?

**Comment by etpinard** [comment]
Superseded by https://github.com/plotly/plotly.js/pull/2159

**Pull request closed without merging**
