### PR TITLE
Configurable doubleclick

### PR DESCRIPTION
**Pull request by pynklu**
Add an option 'doubleClickDelay' to the layout object (0 - 1000ms), to optionally overwrite the default 300ms doubleclick delay
https://github.com/plotly/plotly.js/issues/2206

first time making a PR (and don't really work with git), so sorry in advance if i did something wrong :-)

### CODE REVIEW

**Comment by etpinard** [comment]
Thanks very much for the PR!

I think `doubleClickDelay` would be better off as [config](https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.js) option, unless @plotly/plotly_js opposes.

We'll also need to make all subplots including the ones that don't use `dragElement` (e.g. [geo](https://github.com/plotly/plotly.js/blob/3d383b796d5738b9f93356db2cc5b4b51570e4a5/src/plots/geo/geo.js#L436) and [mapbox](https://github.com/plotly/plotly.js/blob/3d383b796d5738b9f93356db2cc5b4b51570e4a5/src/plots/mapbox/mapbox.js#L193-L211)), use the set double-click value.

Thanks again, let me know if you any other questions.

**Comment by pynklu** [comment]
Ah yes, that makes more sense. Can I add extra commits to this PR, or?

**Comment by pynklu** [comment]
Alright, I changed it to use the config object. I went through the geo & mapbox code & couldn't find anything doublclick related that doesn't come from dragelem/ or legend/
Couldn't find any double-click behaviour that didn't use the adjusted delay either through manual testing

**Comment by etpinard** [comment]
> I went through the geo & mapbox code & couldn't find anything doublclick related that doesn't come from dragelem/ or legend/

See

 https://github.com/plotly/plotly.js/blob/3d383b796d5738b9f93356db2cc5b4b51570e4a5/src/plots/geo/geo.js#L436

which uses the d3 double click handler

https://github.com/plotly/plotly.js/blob/3d383b796d5738b9f93356db2cc5b4b51570e4a5/src/plots/mapbox/mapbox.js#L193-L211

which uses mapbox-gl's double click handler

---

There might be a way to make those two handlers adhere to `gd._context.doubleClickDelay`, but I'd be ok punting these to https://github.com/plotly/plotly.js/issues/2057

**Comment by etpinard** [comment]
Now @pynklu would you be interested in trying to:

- make `npm run test-jasmine --bundleTest=requirejs_test.js --nowatch` pass
- add a new test similar to this [one](https://github.com/plotly/plotly.js/blob/44633a13a3e022a4565d7b230b9db3e1e1ac83aa/test/jasmine/tests/click_test.js#L874-L893) in the `click_test.js` suite

**Comment by pynklu** [comment]
afbeelding
doesn't this imply that test passes?

**Comment by etpinard** [comment]
this here

image

is the failing test (ref: https://circleci.com/gh/plotly/plotly.js/43400?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by pynklu** [comment]
@etpinard sorry, but I can't get the tests to run properly on my end + really don't know how to properly write them. Would you mind taking this up? :-)

**Comment by etpinard** [comment]
TODO (that hopefully I'll have time to do before 1.49.0 is ready):

- [ ] add 1 test in `config_test.js`
- [ ] add a few `dragelement_test.js` tests
- [ ] add a few legend tests
- [ ] add note in `doubleClickDelay` `plot_config.js` description about limitations i.e. it has no effect on geo and mapbox subplot double-click delays for now.

**Comment by etpinard** [comment]
cc @plotly/plotly_js this PR is now `rewiewable` and tagged under 1.49.0 (why not right?) - I'm looking for a review today. Thanks!

**Comment by archmoj** [comment]
Thanks @pynklu & @etpinard.
Nicely done.
:dancer:

**Pull request merged**
