### PR TITLE
Angular cli readme instructions

### PR DESCRIPTION
**Pull request by TomDemulierChevret**
### Features, Bug fixes, and others:

This pull request add instructions on how to use plotly.js in an Angular application built with Angular CLI.

### CODE REVIEW

**Comment by etpinard** [comment]
Thanks for the info.

My only concern is this might make the README too long. Perhaps we could wrap this info in a [`<details>`](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) block?

**Comment by etpinard** [comment]
I also would prefer leaving this new piece of document out of `dist/README.md`. 

Personally, I'd vote for putting in the root `REAMDE.md` under a new section called _Building_ or _Bundling_ possibly using `<details>`.

**Comment by fhurta** [comment]
Just a note to the sample - as `scatter` is included in `core`, maybe there could be some other sample (or the extra line removed).

    "compilerOptions": {
        "paths": {
            "plotly.js": [
                "../node_modules/plotly.js/lib/core.js",
                "../node_modules/plotly.js/lib/scatter.js"
            ]
        }
    }

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/pull/2654

**Pull request closed without merging**
