### PR TITLE
DRY loneHover routine

### PR DESCRIPTION
**Pull request by antoinerg**
`Fx.loneHover` logic is already contained in `Fx.multiHover` so I remove the duplication here.

### CODE REVIEW

**Comment by etpinard** [comment]
Brilliant!

I'm a little worried about this block:

https://github.com/plotly/plotly.js/blob/26bc2bf4701efb7b7df0357fe065896c19c41661/src/components/fx/hover.js#L168-L189

affecting traces the use `Fx.loneHover` in bad ways. Could you manually check that `pie`, `gl3d`, `sunburst` and `sankey` traces look the same?

----

Moreover, maybe we could go one step further by merging `multiHovers` with `loneHover` completely. Looks like all you need is something like:

```js
return Array.isArray(hoverItems) ? hoverLabel : hoverLabel.node(); 
```

at the end.

**Comment by antoinerg** [comment]
> Could you manually check that `pie`, `gl3d`, `sunburst` and `sankey` traces look the same?

I added a `console.log(d.offset)` after L188 and made sure `d.offset` is zero for all the traces you mentioned. In the future, if we support different alignment schemes for hover labels, we should definitely add test this in jasmine.

> Moreover, maybe we could go one step further by merging multiHovers with loneHover completely. 

Do you mean that I should remove all occurrences of `Fx.loneHover` in our codebase? I guess it would make sense to do so.

**Comment by etpinard** [comment]
> Do you mean that I should remove all occurrences of `Fx.loneHover` in our codebase?

I would do opposite. Keep `loneHover` and merge `multiHovers` into `loneHover`. `loneHover` has more history in the repo (it's been there ever since `gl3d` got its hover labels).

**Comment by etpinard** [comment]
Awesome :dancer:

**Pull request merged**
