### PR TITLE
Updatemenus toggle buttons via args2

### PR DESCRIPTION
**Pull request by etpinard**
resolves https://github.com/plotly/plotly.js/issues/4042

example: https://codepen.io/etpinard/pen/WNNOQoj

cc @archmoj - this is the last feature required for `v1.51.0`

### CODE REVIEW

**Comment by etpinard** [comment]
... and cc @alexcjohnson who asked for this feature.

**Comment by archmoj** [comment]
Looking pretty good to me.
I am not sure about 'args2' naming though.
What about using arglist or extraargs?

**Comment by etpinard** [comment]
> I am not sure about 'args2' naming though.

Why not, we have `axis`, `axis2`?

**Comment by archmoj** [comment]
OK. Resolved.

**Comment by archmoj** [comment]
Nicely done.
:dancer:

**Pull request merged**
