### PR TITLE
Fix exporting patterns with transparent color 

### PR DESCRIPTION
**Pull request by archmoj**
@plotly/plotly_js

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Looks like pattern `.` needs the same applied to `fill` (ie create `fill-opacity`) instead of `stroke`

https://github.com/plotly/plotly.js/blob/adcb081a09fec15e7af2d70210e01a525b83cacd/src/components/drawing/index.js#L530

But I wonder: is there any difference in effect between `opacity` and `stroke-opacity` (or `fill-opacity`) in this case? ie could we just multiply `fgopacity` and `fgStrokeOpacity` together into a single `opacity` value?

Also: looks like the `bgcolor` part may need to be split into `fill` and `fill-opacity`, since we aren't setting it with `Color.fill`:

https://github.com/plotly/plotly.js/blob/adcb081a09fec15e7af2d70210e01a525b83cacd/src/components/drawing/index.js#L571

**Comment by archmoj** [comment]
> Looks like pattern `.` needs the same applied to `fill` (ie create `fill-opacity`) instead of `stroke`
> 
> https://github.com/plotly/plotly.js/blob/adcb081a09fec15e7af2d70210e01a525b83cacd/src/components/drawing/index.js#L530
> 
> But I wonder: is there any difference in effect between `opacity` and `stroke-opacity` (or `fill-opacity`) in this case? ie could we just multiply `fgopacity` and `fgStrokeOpacity` together into a single `opacity` value?
> 
> Also: looks like the `bgcolor` part may need to be split into `fill` and `fill-opacity`, since we aren't setting it with `Color.fill`:
> 
> https://github.com/plotly/plotly.js/blob/adcb081a09fec15e7af2d70210e01a525b83cacd/src/components/drawing/index.js#L571

Browser compatibility of [`stroke-opacity`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-opacity) and [`fill-opacity`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-opacity) is unknown. 
So good call. Please review [22dbf02](https://github.com/plotly/plotly.js/pull/6318/commits/22dbf024483ddc68a71ad00b71d81545e0be6b3d) and [35f7e95](https://github.com/plotly/plotly.js/pull/6318/commits/35f7e95ea35509441f9548fe36584ec43f5f83fd).

**Comment by alexcjohnson** [comment]
> Browser compatibility of [stroke-opacity](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-opacity) and [fill-opacity](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-opacity) is unknown.

We've been using those attributes all over the place for years, I think we can conclude they're safe :) But simpler is better as long as the effect is the same. Did anything actually change in the images you regenerated? They look identical to me.

We still want to separate out [`bgcolor`](https://github.com/plotly/plotly.js/blob/adcb081a09fec15e7af2d70210e01a525b83cacd/src/components/drawing/index.js#L571) per the last part of my comment https://github.com/plotly/plotly.js/pull/6318#issuecomment-1251242102

**Comment by archmoj** [comment]
> Did anything actually change in the images you regenerated? They look identical to me.

Please see the diffs below:

diff-pattern_bars
diff-scatter_fill_pattern

BTW, they look identical to my eyes too.

**Comment by archmoj** [comment]
> > Browser compatibility of [stroke-opacity](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-opacity) and [fill-opacity](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-opacity) is unknown.
> 
> We've been using those attributes all over the place for years, I think we can conclude they're safe :) But simpler is better as long as the effect is the same. 

With that said, do you think it would be better (& more specific) to use `stroke-opacity` and `fill-opacity` instead of general `opacity`?

**Comment by alexcjohnson** [comment]
> With that said, do you think it would be better (& more specific) to use stroke-opacity and fill-opacity instead of general opacity?

You could also say `opacity` is better because it's the same attribute for both types of pattern. I don't think it matters. Let's just fix the bgcolor part and call it done.

**Comment by archmoj** [comment]
> We still want to separate out [`bgcolor`](https://github.com/plotly/plotly.js/blob/adcb081a09fec15e7af2d70210e01a525b83cacd/src/components/drawing/index.js#L571) per the last part of my comment [#6318 (comment)](https://github.com/plotly/plotly.js/pull/6318#issuecomment-1251242102)

Good call. Addressed in [4cd8011](https://github.com/plotly/plotly.js/pull/6318/commits/4cd801148adb4e3c8541941db9c6044cc669f742).

**Comment by archmoj** [comment]
@alexcjohnson Let's merge this PR so I possibly open another one for few other components & traces.
Thanks!

**Review by alexcjohnson — APPROVED** [review]
💃 Yep, looks great!

**Pull request merged**
