### PR TITLE
Fix modebar not recreated when makePlotFramework called

### LINKED ISSUE #4974: Using `restyle` method in `updatemenus` button removes the modebar
This is very similar to #3824, and this bug was first reported in [this comment](https://github.com/plotly/plotly.js/issues/3824#issuecomment-643620847) by @sermeor, but I thought it made sense to open a new issue.

The issue can be reproduced on the Plotly website in [the "Restyle Button Single Attribute" example](https://plotly.com/javascript/custom-buttons/#restyle-button-single-attribute).

On initial load, hovering over the plot brings up the modebar.
Screen Shot 2020-06-30 at 2 12 29 PM

However, after clicking the "Heatmap" button, the modebar no longer appears.
Screen Shot 2020-06-30 at 2 13 19 PM

The same thing happens when changing the trace type in other examples on this page. 
This issue can also be reproduced in [this Plotly Python example](https://plotly.com/python/dropdowns/#update-one-data-attribute). Please let me know if I should open a separate issue on [plotly.py](https://github.com/plotly/plotly.py).

Thank you for your time and for making Plotly so awesome!

### PR DESCRIPTION
**Pull request by Yook74**
Fixes #4974

If [makePlotFramework](https://github.com/plotly/plotly.js/blob/b572b87f97b6e09dc3b5bce784a1f32b399c15ad/src/plot_api/plot_api.js#L3714) was called when updating an existing plot, the modebar div would be cleared, but `gd._fullLayout._modeBar` which tracks the modebar's state would not be changed. If `gd._fullLayout._modeBar` was not changed, [this conditional](https://github.com/plotly/plotly.js/blob/aea633067471f00cce3db4e87f77868ac8a35c9a/src/components/modebar/manage.js#L66)
would update the modebar instead of creating it. Updating the modebar in this context does not work though, since the modebar div has been cleared.

My extremely simple fix is to clear the modebar's state stored in `gd._fullLayout._modeBar` when clearing the modebar div in `makePlotFramework`.

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Thanks @Yook74! this indeed looks like exactly the right fix 🎉 

The only thing we need now is a test - ideally this would be something like the [modebar styling tests](https://github.com/plotly/plotly.js/blob/3a7f28e6e891429aa75d0d2b4d376c2d2f0bd531/test/jasmine/tests/modebar_test.js#L1453) - `createGraphDiv` before, `destroyGraphDiv` after, and the test itself would be
```js
Plotly.plot(gd, data, layout).then(function() {
    // test that the initial modebar is present
    var modeBar = gd._fullLayout._modeBar;
    expect(countGroups(modeBar)).toEqual(6); // whatever buttons should be there

    // some modification that would have broken the modebar before your fix:
    // react, restyle, click a button... whatever's easiest
    return Plotly.react(gd, newData, newLayout);
}).then(function() {
    // test that the new modebar is present
    var modeBar = gd._fullLayout._modeBar;
    expect(countGroups(modeBar)).toEqual(12); // different (nonzero) number of buttons
})
.catch(failTest)
.then(done)
```

**Comment by Yook74** [comment]
I wrote tests to catch the particular problem I was having (#4974).

**Comment by archmoj** [comment]
> I wrote tests to catch the particular problem I was having (#4974).

Thanks for the tests. They pass on my machine. I also re-run the CI tests so that they pass.

**Comment by archmoj** [comment]
Nicely done. :dancer:

**Pull request merged**
