### PR TITLE
Take into account inside labels of overlaid axes in when hiding labels on the counter axis

### PR DESCRIPTION
**Pull request by archmoj**
Addressing #5402.

The autorange padding part was addressed in #5586.
This PR fixes the hiding part.

[Demo](https://codepen.io/MojtabaSamimi/pen/gOgzeMK)

@plotly/plotly_js

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Playing with the codepen, I found that panning the x-axis didn't hide the x-ticklabels when they were below the y-ticklabels... ? I thought we'd fixed this in #5582  ?

**Comment by archmoj** [comment]
> Playing with the codepen, I found that panning the x-axis didn't hide the x-ticklabels when they were below the y-ticklabels... ? I thought we'd fixed this in #5582 ?

Good catch. We did fix it and it is now working as expected without overlaid axis. 
So this one appears to be a another piece which I am going to address in this PR.
Thanks!

**Comment by archmoj** [comment]
This PR is ready for review.

**Comment by alexcjohnson** [comment]
@archmoj a few issues when I'm playing with this, using the `ticklabelposition-overlay2` mock:
- Why is there so much padding? Both sides of the axes with inside labels get way more padding than they need.
- Autorange gets confused with this mock: if I doubleclick one of the subplots it autoranges as if there were no labels inside, then doubleclicking again puts it back to mega-padding.
- `relayout` doesn't work: eg `Plotly.relayout(gd,'xaxis2.ticklabelposition',null)` moves the tick labels but does not update `yaxis3.range`. I suspect this is related to the autorange confusion

None of these behaviors happen with only one set of inside labels on a given subplot; in fact if I remake this mock with either `xaxis2` or `xaxis3` having outside labels, the padding is correct, autorange works correctly, and relayout to move the other xaxis inside and out (toggling between zero and one set of inside labels on the top subplot) correctly updates `yaxis3.range`.

**Comment by archmoj** [comment]
> @archmoj a few issues when I'm playing with this, using the `ticklabelposition-overlay2` mock:
> 
> * Why is there so much padding? Both sides of the axes with inside labels get way more padding than they need.

Please note that the axes have specific ranges and they are not `autoranged`.

**Comment by archmoj** [comment]
> * Autorange gets confused with this mock: if I doubleclick one of the subplots it autoranges as if there were no labels inside, then doubleclicking again puts it back to mega-padding.

The `mega-padding` question here is related to the initial view which is controlled by a use-defined range not `autorange`.

**Comment by alexcjohnson** [comment]
> they are not autoranged

What's the point of that mock then? Anyway the second point stands, I can't get it to autorange correctly via GUI interactions no matter what I do.

**Comment by archmoj** [comment]
> > they are not autoranged
> 
> What's the point of that mock then? 

To lock the bug. Without that the labels (namely -1 and 1) won't hide under inside ticklabels of the counter axis.

should_hide_ticks_below_inside_labels

**Comment by archmoj** [comment]
> > they are not autoranged
> 
> Anyway the second point stands, I can't get it to autorange correctly via GUI interactions no matter what I do.

I agree. That looks like a separate bug outside the scope of this PR.

**Comment by alexcjohnson** [comment]
> Without that the labels (namely -1 and 1) won't hide under inside ticklabels

Ah, got it! Sorry, I misunderstood the purpose here. Yes, please consider autorange a separate bug, which indeed is independent of how many inside-labeled axes are drawn on the subplot: if you start out autoranged everything is fine, but if you start with defined ranges or if you start autoranged and then zoom, doubleclicking will do strange things (and will toggle between two states even if you started out autoranged)

**Review by alexcjohnson — APPROVED** [review]
💃 This looks good re: label visibility, apologies for the confusion.

**Pull request merged**
