### PR TITLE
Compute histogram bin positions beyond length 5000

### PR DESCRIPTION
**Pull request by etpinard**
Fixes https://github.com/plotly/plotly.js/issues/1682

@alexcjohnson does this look acceptable?

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Makes sense, the fix for #484 is going to be very similar. But, like my comment there https://github.com/plotly/plotly.js/issues/484#issuecomment-315094312 I wonder if we still want to have some hard-coded upper bound on the total number, even if it's super high like 1e6?

**Comment by etpinard** [comment]
> though I do think we need some sort of upper bound to prevent locking the browser - this can happen easily for example if you specify an explicit tick spacing and then zoom out a lot.

Yeah, a super high upper bound would make sense. Maybe we could put that upper bound somewhere in a constants file and reuse it in all our `while` loops? Though, locking the browser is less concerning here as this `while` loop is called in the calc step as opposed to #484 which is called in the plot step.

**Comment by etpinard** [comment]
> wonder if we still want to have some hard-coded upper bound on the total number, even if it's super high like 1e6?

done in eef9158d82c1d307b479721b391d074415af46c7

**Comment by alexcjohnson** [comment]
💃

**Pull request merged**
