### PR TITLE
Use derequire browserify plugin to bundle dist files [fixes #90] 

### LINKED ISSUE #90: qgrid - plotly conflict
I'm using plotly offline in a jupyter notebook.  I'm coming across an error that i can't seem to debug.  

Here is my code:

import qgrid
import Quandl
import plotly
from plotly.offline import download_plotlyjs, init_notebook_mode, iplot

aapl = Quandl.get('yahoo/aapl')
qgrid.nbinstall(overwrite=True)

#works ok
qgrid.show_grid(aapl)

init_notebook_mode()
#no longer works ok
qgrid.show_grid(aapl)

The error message is
"
Javascript error adding output!
TypeError: Cannot read property 's' of undefined
See your browser Javascript console for more details.
"

### PR DESCRIPTION
**Pull request by etpinard**
@mdtusz would you mind trying this out in a jupyter notebook?

### CODE REVIEW

**Comment by etpinard** [comment]
for reference: https://github.com/calvinmetcalf/derequire

**Comment by etpinard** [comment]
To note, `derequire` adds significant delays in-between watchify builds, so I decided to not include it in watched builds.

**Comment by etpinard** [comment]
@mdtusz On second thought, importing plotly.js using the requirejs `require` in a notebook cell looks like is doing exactly what we want without having to *derequire* our bundle.

image

**Comment by mdtusz** [comment]
Innnnteresting. I'll try that out in Jupyter. I'm not sure that it will work in Tonicdev however, so we'll need to think of a clever way to check which environment it's in.

**Comment by mdtusz** [comment]
:arrow_up: Or I could not be a goof and just check if `require` is defined...

**Comment by etpinard** [comment]
> Or I could just not be a goof and just check if require is defined...

checking for `window.requirejs && window.define && window.require` should do the trick.

**Pull request closed without merging**
