### PR TITLE
Fix disappearing legend entries

### PR DESCRIPTION
**Pull request by fredrikw**
This should be a fix to plotly#4986 with an added mock to show the problem. Basically, there was a mismatch between when calculating whether a legend fits in one row and when calculating whether to add a new row, leading to a "itemGap" width difference in the row lengths. This PR addresses this by changing the calculation of row breaks.

### CODE REVIEW

**Comment by fredrikw** [comment]
The test-image failure I believe is due to that I opted to change the calculation when breaking rows instead of when calculating if the legend is "one row only". I actually think it looks better with my changes, but I can switch if you would like me to. That way I think the test error would go away. (I'll address the missing line at the same time)

**Comment by archmoj** [comment]
@fredrikw Could you pick the commit which adds the baseline for your new mock?
https://github.com/plotly/plotly.js/commit/51265e53668f9d197094204199edd75608dd2f1b

And here is more info on how to generate new baselines: https://github.com/plotly/plotly.js/blob/master/test/image/README.md

**Comment by archmoj** [comment]
> The test-image failure I believe is due to that I opted to change the calculation when breaking rows instead of when calculating if the legend is "one row only". I actually think it looks better with my changes, but I can switch if you would like me to. That way I think the test error would go away. 

I also like this new baseline:
legend_small_horizontal

Please also commit the changes to this baseline so that the test image could pass.

**Comment by archmoj** [comment]
Thanks very much for the PR.
:dancer:

**Pull request merged**
