### PR TITLE
Call dragElement.getCursor(), not cursor()

### PR DESCRIPTION
**Pull request by coopy**
Fixes https://github.com/plotly/streambed/issues/6262.

Ready for review, @etpinard.

### CODE REVIEW

**Comment by etpinard** [comment]
Great. Thanks for doing this :beers: 

It would be nice to a test case before merging this in.

@mdtusz just added an `editable: 'true'` test for legends [here](https://github.com/plotly/plotly.js/blob/d8e27dd33270aa7e4bb01a612cc99c51fa3cb68a/test/jasmine/tests/config_test.js#L45), @coopy would you mind adding a similar test for dragging editable annotations?

**Comment by coopy** [comment]
Sure!
It's worth noting that this does not solve the issue (I think this is a 🐛 ) with the note position updating while the mouse is dragging. It only gets rid of the exception.

kw6kl3ks3s

**Comment by mdtusz** [comment]
I'll tackle this tomorrow. When we removed the last bits of nested svg, parts of annotation changed. It now uses a transform instead of x/y positioning so just needs a quick update to change that instead.

**Comment by coopy** [comment]
Closing - replaced by https://github.com/plotly/plotly.js/pull/505!

**Pull request closed without merging**
