### PR TITLE
RGBA colorscale support for surface traces

### PR DESCRIPTION
**Pull request by lucapinello**

### CODE REVIEW

**Comment by archmoj** [comment]
cc: https://github.com/plotly/plotly.js/issues/4331

**Comment by etpinard** [comment]
@archmoj What's your take on this?

Sounds like we could both honour the alpha channel in `colorscale[i] = [255, 0, 0, alpha]` items AND implement `opacityscale` in surface traces? I worry about poor rendering performance, but it sounds like we _could_ enable both.

**Comment by etpinard** [comment]
@lucapinello could you share the `data` and `layout` settings you used to generate this graph

image


from https://github.com/plotly/plotly.js/issues/4331#issuecomment-549080974

**Comment by etpinard** [comment]
This PR essentially implements https://github.com/plotly/plotly.js/issues/4120

**Comment by archmoj** [comment]
Ranges needed for opacity can be very from those of color channels.
I'd vote for investing time on implementing `opaityscale` and possibly `opacitybar`.

**Comment by etpinard** [comment]
@archmoj ok if we rename this PR _RGBA colorscale support for surface traces_? 

This implementation isn't _per-element_, it's _per colorscale step item_.

**Comment by archmoj** [comment]
> @archmoj ok if we rename this PR _RGBA colorscale support for surface traces_?
> 
> This implementation isn't _per-element_, it's _per colorscale step item_.

Renamed. Thanks!

**Comment by lucapinello** [comment]
@etpinard sure thing: https://github.com/plotly/plotly.py/issues/1859

**Comment by archmoj** [comment]
Closing this PR in regard to implementation of `opacityscale` in #4480.

**Comment by etpinard** [comment]
@archmoj I don't understand why you closed this PR.

To me it is a nice complement to `opacityscale` and it makes surface colorscale more on-par with other (mainly used for SVG traces) colorscales in the library.

**Comment by archmoj** [comment]
@etpinard you are right.
1st - I thought colorbar won't be rendered with transparent colors. But it looks OK e.g. this `treemap` [demo](https://codepen.io/MojtabaSamimi/pen/KKwYZpa?editors=0010) appear to work!
2nd - We need to patch `gl-surface` and other gl-vis modules to enable transparency without alpha 0.99 hack.
I re-open this PR for now; but I suggest continue working on it after https://github.com/plotly/plotly.js/pull/4480 is merged.

**Comment by etpinard** [comment]
> I re-open this PR for now; but I suggest continue working on it after #4480 is merged.

Yes, that's fine!

**Comment by archmoj** [comment]
Closing not that #5166 is open.

**Pull request closed without merging**
