### PR TITLE
append coverSlip to fullscreen element instead of body

### LINKED ISSUE #4259: Rangeslider not working in fullscreen
I have a graph with multiple traces, that uses rangeslider and rangeselector to navigate.

The rangeslider works fine on normal window size, even when it is resized, but when it goes in fullscreen mode it stop working.

Looks like there is some issue with the mouse events.

When I exit the fullscreen mode it works again, just looks in some cases bound to the mouse move, but one or 2 clicks and it start working again perfectly.

In fullscreen the graph zoom works, and the range selector works too.

Here there is an example of the issue:

https://codepen.io/alexmario74/pen/yLLyGgB?editors=0010

### PR DESCRIPTION
**Pull request by FlorianMaak**
Resolves #4259 

This PR checks if there is a fullscreen element and appends dragelements coverSlip to this element instead of documents body.

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Thanks @FlorianMaak! But it looks to me as though the unprefixed `fullscreenElement` is not yet available everywhere - [perhaps only 45%](https://caniuse.com/#feat=fullscreen)? In some of our other packages we use [`fscreen`](https://www.npmjs.com/package/fscreen) to normalize this.

**Comment by etpinard** [comment]
Thanks very much for the PR @FlorianMaak - beyond browser support, it would be nice to write a test in the [`dragelement_test.js`](https://github.com/plotly/plotly.js/blob/master/test/jasmine/tests/dragelement_test.js) suite to lock down your fix. Would be interested in attempting to write a test?

**Comment by FlorianMaak** [comment]
Sure. Going to migrate to fscreen and add tests as soon, as I'm at office tomorrow.

**Comment by FlorianMaak** [comment]
**Relating Tests:** I think, we need to edit the karma config to work with fullscreen. Per default karma does not support fullscreen mode :/

https://github.com/karma-runner/karma/issues/2292

**Comment by archmoj** [comment]
@FlorianMaak could you please merge master into this branch and resolve the conflict?

**Comment by gvwilson** [comment]
This pull request has been sitting for a while, so I would like to close it as part of our effort to tidy up our public repositories. I've assigned it to myself to keep track of it; I'll wait until 2024-06-17 for someone to say it's still relevant and they'll to take it on, and otherwise I will close it then. Thanks - @gvwilson

**Pull request closed without merging**
