### PR TITLE
Update zh-tw.js

### PR DESCRIPTION
**Pull request by sec2**
Completed the dictionary part.
Used ja.js as template.

Thanks for your interest in plotly.js!

### Translations:

- Please @ mention a few other speakers of this language who can help review your translations.
- If you've omitted any keys from [dist/translation_keys.txt](https://github.com/plotly/plotly.js/blob/master/dist/translation-keys.txt) - which means they will fall back on the US English text - just make a short comment about why in the PR description: the English text works fine in your language, or you would like someone else to help translating those, or whatever the reason.
- You should only update files in `lib/locales/`, not those in `dist/`

### Features, Bug fixes, and others:

Before opening a pull request, developer should:
1. make sure they are not on the `master` branch of their fork as using `master` for a pull request would make it difficult to fetch `upstream` changes.
2. fetch latest changes from `upstream/master` into your fork i.e. `origin/master` then pull `origin/master` from you local `master`.
3. then `git rebase master` their local dev branch off the latest `master` which should be sync with `upstream/master` at this time.
4. make sure to **not** `git add` the `dist/` folder (the `dist/` is updated only on version bumps).
5. make sure to commit changes to the `package-lock.json` file (if any new dependency required).
6. provide a title and write an overview of what the PR attempts to do with a link to the issue they are trying to address.
7. select the _Allow edits from maintainers_ option (see this [article](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for more details).

After opening a pull request, developer:
 - should create a new small markdown log file using the PR number e.g. `1010_fix.md` or `1010_add.md` inside `draftlogs` folder as described in this [README](https://github.com/plotly/plotly.js/blob/master/draftlogs/README.md), commit it and push.
 - should **not** force push (i.e. `git push -f`) to remote branches associated with opened pull requests. Force pushes make it hard for maintainers to keep track of updates. Therefore, if required, please fetch `upstream/master` and "merge" with master instead of "rebase".

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Thanks @sec2! It looks like there are 6 new keys in [translation-keys.txt](https://github.com/plotly/plotly.js/blob/master/dist/translation-keys.txt) since ja.js was created:
- Click to enter radial axis title
- Draw circle
- Draw closed freeform
- Draw line
- Draw open freeform
- Draw rectangle

Would you be able to add these?

Can you please also tag another native zh-tw speaker to review?

Lastly, the date localization also changed, I just want to confirm that this was intentional?

**Comment by sec2** [comment]
Hi Alex,

Sure I'll update the missing keys tomorrow.

I can tag one of my friend (also programmer) but he has no records on
github though.

In Taiwan (as well as Hong Kong and Macau) we use 週X formally for weekdays,
周X usually considered as lazy or simplified ones, similar to "because" and
"b'coz" in English.

You can also find this rule on Wikipedia.
Monday Article in zh-TW
https://zh.wikipedia.org/zh-tw/%E6%98%9F%E6%9C%9F%E4%B8%80
[image: image.png]

Monday Article in zh-CN
https://zh.wikipedia.org/zh-cn/%E6%98%9F%E6%9C%9F%E4%B8%80
[image: image.png]

For "shortMonths", the original translation contains only numbers in
Chinese, numbers-only expression cause confusing renders on charts (since
we also use numbers on weekdays and date), so I followed ja.js, only
slightly shorter (on width) than "months" but explicit.
FYI, 一月 = January, 二月 = February...
一 = one
二 = two
In Chinese and Japanese the months are just numbers :D.

Alex Johnson ***@***.***> 於 2022年7月1日 週五 凌晨12:11寫道：

**Comment by sec2** [comment]
@vvrr please help reviewing the translations, many thanks!

**Review by alexcjohnson — APPROVED** [review]
💃 Excellent, thank you @sec2 and @vvrr!

@sec2 the final thing we'll need is a draftlog entry, as described in [draftlogs/README.md](https://github.com/plotly/plotly.js/blob/master/draftlogs/README.md), then we can merge 🎉

**Comment by sec2** [comment]
@alexcjohnson draftlog added, thanks!

**Comment by alexcjohnson** [comment]
@sec2 I didn't see it pushed, but I needed to fix the entry I just made for Sinhala so I made one myself. Will merge once tests pass. Thanks again!

**Pull request merged**
