### PR TITLE
Fix missing gl2d lines

### PR DESCRIPTION
**Pull request by dy**
Addresses #2397

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Can you add a baseline image that would have failed before, and works now?

**Comment by etpinard** [comment]
Yep. I'll do that now!

**Comment by alexcjohnson** [comment]
Thanks! LGTM 💃

**Comment by etpinard** [comment]
:dancer: @dy please merge this in once you published a new version of `regl-line2d` to npm and updated the package.json and package-lock.json files here.

**Pull request merged**
