### PR TITLE
better default order for multiple hovers

### LINKED ISSUE #3050: Misalignment of horizontal box/violin hover labels
Split out of @alexcjohnson 's  https://github.com/plotly/plotly.js/issues/2970#issuecomment-424499773

----------

The misalignment in the original multi-plot codepen https://codepen.io/kotwgarnku/pen/gdxaPN when you set the first plot to `closest` is still there (and yes, the codepen is now using 1.41.3). To be clear, I'm talking about how eg the "min" label is not pointing to the "min" value, but to where that value would be according to the bottom plot. There also seems to be a problem with the overlap avoidance algorithm when one of the labels is too long and gets flipped to the top - it's putting them out of order and then stretching them across each other.
screen shot 2018-09-25 at 4 52 23 pm

### LINKED ISSUE #3389: Horizontal box hover labels out of order
This is pretty rough... median to the left of min and max to the left of upper:

image

Can we enforce an order here?

### PR DESCRIPTION
**Pull request by nicolaskruchten**
Closes #3389 AND closes #3050 :)

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Note that this makes #2970 a bit worse, because it'll show only 'min' and not 'median' any longer, because that's now the first hover.

**Comment by nicolaskruchten** [comment]
LMK if you like the fix and I'll fix the tests

**Comment by etpinard** [comment]
Thanks for the PR!

Going from:

peek 2019-01-04 15-30

to:

peek 2019-01-04 15-31

is amazing :tada: 

I'm a little confused about _why_ your patch works though. 

`Fx.hover` doesn't seem to care about the ordering of the labels of vertical box/violin traces and  of horizontal box/violin traces under `hovermode:'y'`. I'll try to dig a little deeper. Maybe `Fx.hover` is just missing a `.sort()` for horizontal labels.

**Comment by nicolaskruchten** [comment]
Hehehe like I said, I just looked at it and thought "seems like they're laying out in order and jamming each other up" ... I didn't dig into the root cause at all, but if there's a deeper/more elegant fix I'm all for it.

**Comment by etpinard** [comment]
My attempt in -> https://github.com/plotly/plotly.js/pull/3401

**Pull request closed without merging**
