### PR TITLE
fix hover bug

### PR DESCRIPTION
**Pull request by dimin**

### CODE REVIEW

**Comment by etpinard** [comment]
Thanks for the PR. Would you mind sharing a reproducible example of bug you're trying to fix?

**Comment by etpinard** [comment]
ping @dimin can you help us figuring what's causing this bug?

**Comment by etpinard** [comment]
Closing until someone someone can reproduce this _bug_.

**Comment by dimin** [comment]
Sorry Etienne for such a delay, I finally found the reason for the problem and it was in the third-party library that was messing with D3. Sorry for bugging you so stupidly!

**Pull request closed without merging**
