### PR TITLE
Improve compress_attributes browserify transform and fixup unexpected characters in bundles

### LINKED ISSUE #5382: Unexpected character in some bundles
After merging #5359, there is a problem with `finance` bundle in

Screenshot from 2021-01-06 16-35-58

At
```js
function d3_geo_clipAntimeridianIntersect
```
Strangely enough it is only happening in `finance` and not `geo` and others!

Screenshot from 2021-01-06 16-42-38

### PR DESCRIPTION
**Pull request by archmoj**
Fixes #5382.

@plotly/plotly_js

### CODE REVIEW

**Comment by archmoj** [comment]
At first the publish test passed. Now it fails.

**Comment by archmoj** [comment]
Publish tests pass on `d3-geo` pull #5112 after merging master.
So maybe that's what we should consider?

**Comment by nicolaskruchten** [comment]
what's the relationship between the d3-geo PR and these weird characters?

**Comment by alexcjohnson** [comment]
@nicolaskruchten d3's geo functions are where these weird characters come from, it uses greek letters in its source code for angles in the projections. d3v4 [converts all its source code to ASCII](https://github.com/d3/d3/blob/master/CHANGES.md#other-global-changes):

> To the consternation of some users, 3.x employed Unicode variable names such as λ, φ, τ and π for a concise representation of mathematical operations. A downside of this approach was that a SyntaxError would occur if you loaded the non-minified D3 using ISO-8859-1 instead of UTF-8. 3.x also used Unicode string literals, such as the SI-prefix µ for 1e-6. 4.0 uses only ASCII variable names and ASCII string literals (see rollup-plugin-ascii), avoiding encoding problems.

It seems like this PR, while a very good hypothesis, doesn't solve whatever the underlying problem is. Let me take a look at #5112 again, that seems to me a more promising approach to get rid of this randomly-recurring issue permanently.

**Comment by archmoj** [comment]
Thanks @alexcjohnson for reviewing #5112.
I refactored the compress task in https://github.com/plotly/plotly.js/pull/5426/commits/ed0195b44ce3d06ede6cdb940c467f5dd4f7e3d6 so that debugging would be easier now & in future.
With that on a dev branch I also tried single replacements and other encoding options. Despite various attempts, no solution is found there.
In the end in order to complete this PR, I reverted the changes here https://github.com/plotly/plotly.js/pull/5426/commits/f68214bf7aafac12e64fbec4f8e9b95f4e247fb6.

Returning `Plotly` object from `register_extra` function seems like a good idea to me (unless we hit this problem again).
Obviously we could revert that commit again once we were able to get #5112 in.

To conclude this PR
 - let `no-bad-char` test catch the error instead of `no-new-func` test;
 - refactored and slightly improved `tasks/compress_attributes.js`;
 - fixed the issue on master by changing the way how we make and export the `Plotly` object.

**Review by alexcjohnson — APPROVED** [review]
OK, we can do it this way for now if it lets us avoid the error.

FWIW I think the reason the `module.exports = require('./register_extra')(Plotly);` bothers me is that it makes it unclear what exactly you're exporting. A specific consequence is it may be unclear to people making their own bundles what to do if they don't want these extras. But anyway I suspect we'll be toggling that commit until we get a real solution 😅 
💃

**Pull request merged**
