### PR TITLE
Enabling transparent webgl draws for scatter3d trace when colors are transparent

### LINKED ISSUE #3492: 3D Scatter transparency not activated by marker.color or marker.line.color as well as line.color and errorbars alpha channel
Originally reported in https://github.com/plotly/plotly.py/issues/1416.

The alpha channel of rgba colors seems to be respected by `scatter3d`, but only if the `opacity` property is set to something less than 1.

CodePen: https://codepen.io/jonmmease/pen/OdRbdL

```javascript
var trace1 = {
  x: [0, 1.1, 2.2], 
  y: [0, 1, 2], 
  z: [0, 1, 2], 
  mode: 'markers',
  marker: {
    size: 20,
    color: ['rgba(255, 0, 0, 0.9)',
            'rgba(255, 0, 0, 0.5)',
            'rgba(217, 0, 0, 0.1)'],
    line: {
    },
    opacity: 1.0
    // opacity: 0.99
  },
  type: 'scatter3d'
};

var data = [trace1];
var layout = {
      margin: {
        l: 0,
        r: 0,
        b: 0,
        t: 0
  }};
Plotly.newPlot('myDiv', data, layout, {showSendToCloud: true});
```
With `trace1.opacity: 1.0`
newplot-3

With `trace1.opacity: 0.99`
newplot-4

Could the `opacity<1` logic be activated automatically if `marker.color` includes rgba colors with alpha < 255?  Or maybe just if there are any colors specified as rgba period.

### PR DESCRIPTION
**Pull request by archmoj**
Fix #3492
3D Scatter transparency not activated by marker.color or marker.line.color as well as line.color and errorbars alpha channel.
This is fixed here by patching gl-vis modules.
@plotly/plotly_js

### CODE REVIEW

**Comment by archmoj** [comment]
> Hmm. How does this relate to #3138 ?
Good call.
This PR does not touch `gl-mesh3d` opacity issues. There is actually another PR on `gl-mesh3d` repository related to `volume` trace.
But yeah as discussed we may improve opacity in gl-vis modules in other PRs next.

**Comment by archmoj** [comment]
@etpinard are you interested to include this in 1.44.3?

**Comment by etpinard** [comment]
I'm confused by your answer in https://github.com/plotly/plotly.js/pull/3496#issuecomment-459427754

Have you done any before/after benchmarking?

**Comment by archmoj** [comment]
OK. In this PR we only activated the alpha rendering channels for those 3 gl-vis modules in case of colors being in rgba format with any alpha less than 1.
If the colors were passed in rgb or they all have alpha equal 1 the alpha channel won't be activated.
Yes I could do a bench-marking next.

**Comment by archmoj** [comment]
[Before codepen](https://codepen.io/MojtabaSamimi/pen/rPGyZW).
[After codepen](https://codepen.io/MojtabaSamimi/pen/aXLJWp).
Both gave me around 1025ms for 10K points.
However; the improvements in the quality of graphs are notable when rotating or zooming in.
Hope it may help.

**Comment by archmoj** [comment]
I think some of them are transparent.
[Here](https://codepen.io/MojtabaSamimi/pen/ZwXaYj) is the same codepen with fewer points and large markers.

**Comment by etpinard** [comment]
Ha I see, this is "opacity" from the "a" in rgba. So we're not talking about "true" opacity but "whitening" opacity (see https://github.com/plotly/phoenix-integration/issues/10#issuecomment-164824843 for a past discussion on the topic).

This PR seems like an ok fix for https://github.com/plotly/plotly.js/issues/3492 :taco: 

I do have one question for @archmoj in -> https://github.com/gl-vis/gl-scatter3d/pull/16#discussion_r254294014

**Comment by etpinard** [comment]
Cool. :dancer: 

Let's get this in for 1.44.3 !

**Pull request merged**
