### PR TITLE
[EXPERIMENTAL] Run standard --fix

### PR DESCRIPTION
**Pull request by rreusser**
This is a test PR, mainly to get the ball rolling and see what *would* happen if we simply applied [standard](https://github.com/feross/standard) formatting. There are lots of rules that will require manual rewriting.

In particular, the vast majority look like

```
convert.js:219:72: ':' should be placed at the beginning of the line.
index.js:34:3: Split initialized 'var' declarations into multiple statements.
```

It's probably a couple hour pass to go through and fix those, then a bit more work to figure out maybe a few more subtle issues.

See: #950 ping @etpinard

### CODE REVIEW

**Comment by etpinard** [comment]
Hey, at least at the `;` is gone!

**Comment by rreusser** [comment]
Of note:`eslint` is the only phase of the tests this PR broke.

**Comment by rreusser** [comment]
Common sentiment overheard: "OMG eslint is just horrible to have to run all the time. [`prettier`](https://github.com/jlongster/prettier) solves this whole problem in a way that makes fundamentally so much more sense. So over eslint." Paraphrasing, of course. People seem very excited about dumping eslint for prettier though.

**Comment by rreusser** [comment]
Holding off until some large PRs have been merged.

**Comment by rreusser** [comment]
FWIW: 

screen shot 2017-02-14 at 14 23 25

**Comment by rreusser** [comment]
Closing for now. Can revisit if changing the linting seems like the right move.

**Pull request closed without merging**
