### PR TITLE
Fixes #464 (shapes not deleted when clearing all shapes)

### LINKED ISSUE #464: Shapes not deleted when clearing all shapes
Hi,

I've come across an issue in the recent version whereby calling Plotly.relayout to remove all shapes (i.e shapes: []) does not remove the shape svg elements. Is there a check somewhere that is bailing out when shapes.length == 0, without first checking if there are elements to remove?

In this example, the red shape should be removed by the call to relayout with an empty shapes array: http://codepen.io/anon/pen/pyZPxX

In this example, using a non-empty shapes array in relayout results in the expected behavior (red removed, blue added): http://codepen.io/anon/pen/XdBRym

This worked in prior versions, so has there been a change in the advised method of removing all shapes? The current workaround I'm having to use is to add a tiny invisible shape when I want to remove all other shapes, which is a bit of a bodge.

Edit: As as addition: shapes that are present when calling Plotly.relayout with shapes: [] appear to be orphaned and never cleaned up in subsequent calls to relayout, even when the shapes array is non-empty. Meaning the chart ends up covered in old shapes.

### PR DESCRIPTION
**Pull request by n-riesco**
- Reverted f67ff4d1dcbd4a0a9e5d460ed10020861a8abcae
- Added comment to the code
- Added test

Fixes #464

### CODE REVIEW

**Comment by etpinard** [comment]
@n-riesco Thanks for taking this on!

Looks your patch broke all non-cartesian plots. Let me know if you need help debugging this.

**Comment by n-riesco** [comment]
@etpinard Oh! I see what the problem is `fullLayout._subplotShapeLayer` is undefined for non-cartesian plots. I'll fix it.

**Comment by n-riesco** [comment]
This time I run all the tests locally. The only one that fails is, also fails in master:
```
user@host:~/github/plotly.js$ npm run test-jasmine

> plotly.js@1.9.0 test-jasmine /home/user/github/plotly.js
> karma start test/jasmine/karma.conf.js

22 04 2016 15:09:20.658:INFO [framework.browserify]: registering rebuild (autoWatch=true)
22 04 2016 15:09:29.664:INFO [framework.browserify]: 9097683 bytes written (8.21 seconds)
22 04 2016 15:09:29.825:INFO [framework.browserify]: bundle built
22 04 2016 15:09:29.847:WARN [karma]: No captured browser, open http://localhost:9876/
22 04 2016 15:09:29.852:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
22 04 2016 15:09:29.857:INFO [launcher]: Starting browser Chrome
22 04 2016 15:09:32.121:INFO [Chromium 49.0.2623 (Ubuntu 0.0.0)]: Connected on socket /#mKEDUObYOHij-U8oAAAA with id 963508
Chromium 49.0.2623 (Ubuntu 0.0.0) Test gl plot interactions gl3d plots scatter3d click events should have FAILED
	TypeError: Cannot convert undefined or null to object
	    at Object.<anonymous> (/tmp/875c384a1d041134119e6fd6cbe578ab.browserify:104549:31 <- tests/gl_plot_interact_test.js:141:0)
LOG: 'lost context'
LOG: 'lost context'
LOG: 'lost context'
LOG: 'lost context'
LOG: 'restyle fail', undefined, '', undefined
LOG: 'relayout fail', undefined, false
LOG: 'type newtype already registered'
LOG: 'Oops, tried to put a polar trace on an incompatible graph of cartesian data. Ignoring this dataset.', Object{type: 'newtype', r: 'this is polar'}
Chromium 49.0.2623 (Ubuntu 0.0.0): Executed 773 of 773 (1 FAILED) (1 min 6.717 secs / 1 min 6.225 secs)
```

**Comment by n-riesco** [comment]
Using #467 all jasmine tests pass.

**Comment by etpinard** [comment]
Thanks!

**Pull request merged**
