### PR TITLE
Fixup cartesian dragbox module

### PR DESCRIPTION
**Pull request by etpinard**
I forget about that module during PRs https://github.com/plotly/plotly.js/pull/833 and https://github.com/plotly/plotly.js/pull/845

 cc @rreusser

### CODE REVIEW

**Comment by rreusser** [comment]
Ah, the `.drawOne` issue? Do you want to fix it up since you know this better, then I'll mirror the changes to axis transitions?

**Comment by etpinard** [comment]
> Do you want to fix it up since you know this better, 

It is fixed here (unless I'm going bling).

**Comment by rreusser** [comment]
Ohhh, this is a PR, not an issue. Yeah. got it.

**Comment by etpinard** [comment]
Haha. Ok I'm merging this so that you can mirror it in your animation PR.

**Pull request merged**
