### PR TITLE
Fix hover filter to display close period points

### PR DESCRIPTION
**Pull request by archmoj**
Fix for #5292 the hover part.
Please note that the spikeline part was addressed in #5542.

@plotly/plotly_js

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Some high-level feedback on the behaviour here:

1. we would like to keep the invariant we currently have that "whatever points show up in the one `x unified` hoverlabel are the same points that get a hoverlabel in `x` mode", which I don't believe is uniformly true with this PR
2. when the scatter points are in `period` mode with `periodalignment = end` we would like the hover calculation to be made based on the data coordinate of the point rather than the pixel coordinate.
3. I could see a case for saying that if I have bars in period=m3 mode, and scatter points (in any mode) on the first of the month, then I should _not_ be able to see a hoverlabel with a Jan 1 point *and* a bar that represents Q4 i.e. the last three months of the previous year: Jan 1 is not in Q4.

**Comment by nicolaskruchten** [comment]
We should also remember to test this against grouped bars.

**Comment by archmoj** [comment]
> 1. we would like to keep the invariant we currently have that "whatever points show up in the one `x unified` hoverlabel are the same points that get a hoverlabel in `x` mode", which I don't believe is uniformly true with this PR

*x* `hovermode` does not appear to be perfect IMHO. See this [codepen](https://codepen.io/MojtabaSamimi/pen/qBqvGze?editors=0010). Should we log a bug for "bars and scatters don't show together in x hovermode when hovering over middle or right side of the bars"?

**Comment by archmoj** [comment]
> > 1. we would like to keep the invariant we currently have that "whatever points show up in the one `x unified` hoverlabel are the same points that get a hoverlabel in `x` mode", which I don't believe is uniformly true with this PR
> 
> _x_ `hovermode` does not appear to be perfect IMHO. See this [codepen](https://codepen.io/MojtabaSamimi/pen/qBqvGze?editors=0010). Should we log a bug for "bars and scatters don't show together in x hovermode when hovering over middle or right side of the bars"?

In addition this [codepen](https://codepen.io/MojtabaSamimi/pen/vYyPqZg?editors=0010) may illustrate another bug concerning *x* `hovermode` and *period* alignements.

**Comment by nicolaskruchten** [comment]
Re compare mode (aka `hovermode='x'`) please see #5553 and #5554 for a description of the desired behaviours, which could be implemented either in this PR or a different one.

**Comment by archmoj** [comment]
> 1. we would like to keep the invariant we currently have that "whatever points show up in the one `x unified` hoverlabel are the same points that get a hoverlabel in `x` mode", which I don't believe is uniformly true with this PR

Good call. Addressed in https://github.com/plotly/plotly.js/pull/5543/commits/1e59d895fb6cf0da6853d18c76d116f40776a8db.

**Comment by alexcjohnson** [comment]
I see one bit of problematic behavior: If I make the plot from your test and zoom in a bit, it's possible to get the spikelines and hover labels out of sync. Oddly enough the behavior is somewhat reversed between `x` and `x unified` but both are problematic:

Screen Shot 2021-04-06 at 10 32 01 AM

Screen Shot 2021-04-06 at 10 57 47 AM

**Comment by archmoj** [comment]
> I see one bit of problematic behavior: If I make the plot from your test and zoom in a bit, it's possible to get the spikelines and hover labels out of sync. Oddly enough the behavior is somewhat reversed between `x` and `x unified` but both are problematic:
> 

Thanks for the comment. It seems like the different bug fixed by the other PR #5542.
So I merged master into this branch in https://github.com/plotly/plotly.js/pull/5543/commits/4d831e29bfccbb5f30bfe85bf598efde9e8297e5.

**Review by alexcjohnson — APPROVED** [review]
Excellent! Good catch that the problem I mentioned was just another flavor of the one you already solved 🎉 
💃

**Pull request merged**
