### PR TITLE
Fix axis automargin push offset

### PR DESCRIPTION
**Pull request by etpinard**
fixes https://github.com/plotly/plotly.js/issues/2985 

I attempted to fix this bug by addressing https://github.com/plotly/plotly.js/issues/1988 and by association https://github.com/plotly/plotly.js/issues/2434, but that turned out to be too much of an endeavour. The DDK folks seems to really not like #2985, so here's a quick(er) fix.

In brief, we were previously assuming that the ticks + tick labels started right on the edge of the axis line when computing the auto-margin push value. This is incorrect, there's a slight pad between tick labels and ticks that must be taken into account to get the correct push.

See updated bug report codepens:

- https://codepen.io/anon/pen/XPzEeN -> https://codepen.io/etpinard/pen/GzvjoX
- https://codepen.io/anon/pen/GzrjxN -> https://codepen.io/etpinard/pen/gqxwPB

cc @plotly/plotly_js

### CODE REVIEW

**Comment by antoinerg** [comment]
Very nice PR @etpinard ! Thanks for fixing this issue :dancer:

**Comment by etpinard** [comment]
Thanks for the review @antoinerg !

It might be nice to have some of the DDK folks try out 

https://25536-45646037-gh.circle-artifacts.com/0/plotly.min.js

before merging this cc @cldougl @wbrgss

**Comment by wbrgss** [comment]
> This is incorrect, there's a slight pad between tick labels and ticks that must be taken into account to get the correct push.

Yeah, that's what it looked like to me as well. I've tested the above `plotly.min.js` with DDK, and can confirm this PR appears to fix #2985. This will be a great help; thank you @etpinard!

**Comment by etpinard** [comment]
Thanks @wbrgss for checking! Merging :rocket: 

I'll release 1.44.3 tomorrow with this patch included.

**Pull request merged**
