### PR TITLE
do not delete hoverlabel when hovertemplate is defined

### LINKED ISSUE #3478: No hover boxes appear when `hovertemplate` is defined and trace's name is empty
Traces known to be affected: `scatterternary`, `scatterpolar`, `barpolar`, `scattermapbox`, `scattergeo`, `choropleth`, `pie`.

Codepen showing the issue: https://codepen.io/anon/pen/NoGXrK?editors=0010

### PR DESCRIPTION
**Pull request by antoinerg**
Closes #3478

### CODE REVIEW

**Comment by etpinard** [comment]
Nice!

It might be nice to add a few more test cases :lock: ing down this fix. Maybe one for `scattergeo`, one for `scatterpolar`, one for `scatterternary` and one `scattermapbox`? That is, one test for each subtype type supported by `hovertemplate`.

**Comment by antoinerg** [comment]
Just for future reference, problem #3418 fixed by the current PR will arise for any trace types that do not append anything to variable `text` after going through:
https://github.com/plotly/plotly.js/blob/58bf5bb60d09ee29d3cad19d4f16e4fd64abee13/src/components/fx/hover.js#L934-L965

**Comment by etpinard** [comment]
@antoinerg can you try to add tests for `scatterternary` and `scattermapbox` at some point today? I'd like to include this PR in today's (or tomorrow's :smirk: ) `v1.44.2`. Thanks!

**Comment by antoinerg** [comment]
> @antoinerg can you try to add tests for `scatterternary` and `scattermapbox` at some point today? I'd like to include this PR in today's (or tomorrow's  ) `v1.44.2`. Thanks!

This is now done in 7bff254. Sorry for the slow reply: I initially struggled to reproduce the issue for `scatterternary` and `scattermapbox` before realizing the existing tests wouldn't actually check the content or the existence of hover labels on the page.

**Comment by etpinard** [comment]
Thanks :dancer: !

**Pull request merged**
