### PR TITLE
introduce group scatter attributes

### LINKED ISSUE #4913: scattermode = group
We need to be able to position `scatter` markers (not `scattergl`!) on top of bars even when `barmode=group`.  Note: the ability to position scatter markers on top of [grouped, stacked bars](https://github.com/plotly/plotly.js/issues/4914) is out of scope.

This means we will need to port the following attributes from `bar` to `scatter`:

* `alignmentgroup`
* `offsetgroup`

We will also need to create new layout attributes for `scatter`, with behaviour ported from `bar`:

* `scattermode` (accepting only group and overlay, which is the current default) 
* `scattergap`

### PR DESCRIPTION
**Pull request by archmoj**
Resolves #4913.
@plotly/plotly_js

### CODE REVIEW

**Comment by LiamConnors** [comment]
@archmoj, I know we talked about group legend items that would avoid this, but I wonder if the scatter group going back to the centre when you click it on the legend is the right behaviour here and why it would differ to the behaviour for bar.

image

image

image

**Comment by archmoj** [comment]
@LiamConnors now with the implementation of the `alignmentgroup` & `offsetgroup` for `scatter` trace, you could maintain initial positions. See [918068d](https://github.com/plotly/plotly.js/pull/6381/commits/918068dcbee0bb2a9e867f07be9fdb5230e99360) as an example.

**Comment by alexcjohnson** [comment]
@archmoj this looks great! There's one piece I don't understand: if I load `zz-scatter-grouping-vs-defaults`, then clear all the `alignmentgroup` attrs - `Plotly.restyle(gd,'alignmentgroup',null)` - then the traces in the upper right subplot disappear. They also disappear if I set the `alignmentgroup` for just those two traces to `'bottom'` to match the ones below - `Plotly.restyle(gd,'alignmentgroup','bottom', [3,9])`.

If I also clear `offsetgroup` they come back, and if I set the `offsetgroup` for those two to something explicit they get their own group.

So I guess the odd case is when `alignmentgroup` is either all `null` or all the same but one trace, in a different subplot from the others, doesn't have an `offsetgroup`.

There's a related case that's clearly broken: in the same mock, if I just clear `offsetgroup` for the last trace it stays where it was. But if I first give it a new `offsetgroup` (so it correctly gets new space) and THEN clear it, it gets pushed into the next group!
```js
Plotly.restyle(gd, 'offsetgroup', null, 11) // clear the group for the last trace, this is OK
```
Screenshot 2022-12-20 at 19 24 03

```js
Plotly.restyle(gd, 'offsetgroup', '3', 11) // put it in a new group
Plotly.restyle(gd, 'offsetgroup', null, 11) // clear its group
```
Screenshot 2022-12-20 at 19 18 43

I don't think this is unique to scatter, I can get a similar history-dependent errors from bars from setting / clearing the `offsetgroup` of the FIRST bar in the bottom right subplot (ie replace the 11 with 4 in those commands). Maybe we just treat `null` as its own `offsetgroup` if there are other traces with an `offsetgroup` on the same axis?

**Review by alexcjohnson — APPROVED** [review]
💃 Actually, since the bug I identified - when there are some traces with `offsetgroup` and others without it - was already there with bars, I guess it's fine if we merge as is, and just make an issue to come back to this behavior later. Great work!

**Comment by Braintelligence** [comment]
In case anyone stumbles upon this change and wonders why it doesn't work for them in a horizontal barchart: Make sure your scatter traces also have `orientation: "h"` or else it won't work. I only found this out while looking through all the comments surrounding this change; I believe it is not mentioned in the documentation at `offsetgroup` and there is also no example with horizontal orientation within the example made for the Python news article.

**Comment by LiamConnors** [comment]
Thanks for the feedback @Braintelligence - just to clarify, is the following demonstrating the type of behaviour you are talking about?

I'll add an example to the docs to clarify using with  `orientation: "h"`

```
import plotly.graph_objects as go
from plotly import data

df = data.tips()[data.tips()["day"] == "Sun"]

mean_values_df = df.groupby(by=["sex", "smoker"], as_index=False).mean(
    numeric_only=True
)

smoker_mean = mean_values_df[mean_values_df.smoker == "Yes"].sort_values(
    by="tip", ascending=False
)
non_smoker_mean = mean_values_df[mean_values_df.smoker == "No"].sort_values(
    by="tip", ascending=False
)

smoker = df[df.smoker == "Yes"].sort_values(by="tip", ascending=False)
non_smoker = df[df.smoker == "No"].sort_values(by="tip", ascending=False)

fig = go.Figure(
    layout=dict(
        xaxis=dict(categoryorder="category descending"),
        scattermode="group",
        legend=dict(groupclick="toggleitem"),
    )
)

fig.add_trace(
    go.Bar(
        orientation='h',
        x=smoker_mean.tip,
        y=smoker_mean.sex,
        name="Average",
        marker_color="IndianRed",
        offsetgroup="smoker",
        legendgroup="smoker",
        legendgrouptitle_text="Smoker",
    )
)


fig.add_trace(
    go.Scatter(
        orientation='h',
        x=smoker.tip,
        y=smoker.sex,
        mode="markers",
        name="Individual tips",
        marker=dict(color="LightSlateGrey", size=5),
        offsetgroup="smoker",
        legendgroup="smoker",
    )
)

fig.add_trace(
    go.Bar(
        orientation='h',
        x=non_smoker_mean.tip,
        y=non_smoker_mean.sex,
        name="Average",
        marker_color="LightSalmon",
        offsetgroup="non-smoker",
        legendgroup="non-smoker",
        legendgrouptitle_text="Non-Smoker",
    )
)


fig.add_trace(
    go.Scatter(
        orientation='h',
        x=non_smoker.tip,
        y=non_smoker.sex,
        mode="markers",
        name="Individual tips",
        marker=dict(color="LightSteelBlue", size=5),
        offsetgroup="non-smoker",
        legendgroup="non-smoker",
    )
)

fig.show()
```

**Pull request merged**
