### PR TITLE
Update "Save and edit plot in cloud" text

### PR DESCRIPTION
**Pull request by chriddyp**

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Or maybe `'Edit in Chart Studio'`? That gives you some indication of *why* you'd want to send it there.

**Comment by jackparmer** [comment]
We might want to eventually  think about adding another `/external` endpoint and modebar button for `Add to Plot.ly dashboard` (not in this PR obviously, but while on the subject :) ).

**Comment by chriddyp** [comment]
Alright, I updated to `Edit in Chart Studio`. Good to 💃 @alexcjohnson ?

**Comment by alexcjohnson** [comment]
💃

**Pull request merged**
