### PR TITLE
Use URLs directly for layout images

### PR DESCRIPTION
**Pull request by alexcjohnson**
The data uri is necessary for export only, which should always use staticPlot - so if we're not in staticPlot mode, skip this conversion. Hoping this will improve the experience for plots that make heavy & dynamic use of layout images, by keeping the plotting process synchronous - which I'm calling a bug because we've seen the display become glitchy during pan/zoom in these cases.

I'll have a couple of tests to adapt as well as a changelog entry to add... but first I'm going to use the circleci build for testing in our application.

### CODE REVIEW

**Comment by archmoj** [comment]
@alexcjohnson Thanks for the PR. LGTM.
Please add a draftlog.
Also possibly investigate these failures: https://app.circleci.com/pipelines/github/plotly/plotly.js/11406/workflows/ea736858-eed0-4644-bbac-f80d66624105/jobs/252337/parallel-runs/9/steps/9-105

Concerning the image test failures we did address the problem on master in #7178; so you could skip them.

**Comment by archmoj** [comment]
Please fetch upstream/release-v2.35.3 branch and merge it into this branch. 
That would fix the image tests.
Thank you!

**Comment by alexcjohnson** [comment]
@archmoj one of the tests that fails with my change is `should remove the image tag if an invalid source`. Instead we see the browser's "broken image" icon if it fails to load. I think this is useful behavior for chart creators so I'm inclined to leave it this way and adapt the test (run as-is in `staticPlot` mode but verify that the image points to the source unchanged in interactive mode), do you agree or do you want to call this a breaking change that I should fix?

Here's me intentionally breaking the first image of the `layout-images` mock:
Screenshot 2024-10-07 at 16 06 18

FYI we've demonstrated that this greatly improves the experience for our tile-server-in-a-graph app - using `relayout` data to decide which images to show, so overall it's definitely a win!

**Review by archmoj — APPROVED** [review]
:dancer:

**Pull request merged**
