### PR TITLE
Polar plots defaults when mapped would create addtional overflow vari…

### PR DESCRIPTION
**Pull request by oligee**
…able in the legend

Thanks for your interest in plotly.js!

Developers are strongly encouraged to first make a PR to their own plotly.js fork and ask one of the maintainers to review the modifications there. Once the pull request is deemed satisfactory, the developer will be asked to make a pull request to the main plotly.js repo and may be asked to squash some commits before doing so.

Before opening a pull request, developer should: 

- `git rebase` their local branch off the latest `master`,
- make sure to **not** `git add` the `dist/` folder (the `dist/` is updated only on verion bumps),
- write an overview of what the PR attempts to do,
- select the _Allow edits from maintainers_ option (see this [article](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for more details).

Note that it is forbidden to force push (i.e. `git push -f`) to remote branches associated with opened pull requests. Force pushes make it hard for maintainers to keep track of updates. Therefore, if required, please `git merge master` into your PR branch instead of `git rebase master`.

### CODE REVIEW

**Comment by oligee** [comment]
On it

**Comment by etpinard** [comment]
Can you share before/after screenshots of the bug(s) you fixed in this PR?

**Comment by oligee** [comment]
Before 
before added working name tag
After -: Added Name tag display
added working name tag
Before
before fixed false additions to legend
After :- Legend Fixed
fixed false additions to legend

**Comment by oligee** [comment]
Legend hide function
legend onoff

Ability to alter the title independently

altered title on polar

**Comment by oligee** [comment]
Failed on histogram image ? Very confused i've not touched that

**Comment by etpinard** [comment]
Thanks for you hard work @oligee, some sort of polar refectoring was long overdue, but I have some bad news for you.

We're on the verge of completely rewriting our polar code, so I don't think it's worth our time to review your (impressive) PR. 

That said, we'll gladly accept a (small) PR fixing that legend bug you're referring in https://github.com/plotly/plotly.js/pull/2147#issuecomment-344190905

**Comment by oligee** [comment]
@etpinard No worries, if there are any issues just let me know!

**Comment by oligee** [comment]
@etpinard Do you know how long this will take to take your rework ?

**Comment by etpinard** [comment]
> @etpinard Do you know how long this will take to take your rework ?

About 2 months.

**Comment by oligee** [comment]
Cheers

**Comment by oligee** [comment]
Tests fail if a try catch is used !

**Comment by etpinard** [comment]
Closing this PR as no plotly.js team member will dedicate time to review this polar overhaul.

@oligee like I said https://github.com/plotly/plotly.js/pull/2147#issuecomment-344285201, we'll gladly accept a (small) PR fixing that legend bug.

**Pull request closed without merging**
