### PR TITLE
Geo grid fixes

### PR DESCRIPTION
**Pull request by etpinard**
fixes https://github.com/plotly/plotly.js/issues/2896 (finally) making `geo.(lon|lat)axis.tick0` work by computing grid values using `Axes.calcTicks`.

cc @plotly/plotly_js - I'd like to slip this one in 1.46.0.

### CODE REVIEW

**Comment by archmoj** [comment]
Great! 
Concerning the baselines changes, 
@etpinard could you please elaborate why longitudes are changed on polar stereographic projection:
https://github.com/plotly/plotly.js/pull/3706/files?short_path=2b60c83#diff-2b60c83395ec0c848268b4c720e7d73b
Thanks.

**Comment by etpinard** [comment]
> could you please elaborate why longitudes are changed on polar stereographic projection:

We have a slightly different tick algo than `d3.geo.graticule`.

**Comment by archmoj** [comment]
I think the new longitude lines displayed on the polar stereographic projection may be off by one/half pixel or a distance.
For example 20N should cross Hilo island https://www.mapsofworld.com/usa/states/hawaii/lat-long.html.

<b>Old:</b>
old
<b>New:</b>
new

**Comment by etpinard** [comment]
Sure, there's a diff. Now, is the old baseline correct, or is the new baseline better?

Oh well, I guess I hold this one out of 1.46.0

**Comment by archmoj** [comment]
> Sure, there's a diff. Now, is the old baseline correct, or is the new baseline better?

Hard to tell. To my eyes the old baseline appear to be slightly more accurate if we compare against Hawaii.

**Comment by etpinard** [comment]
@archmoj please have a look at https://github.com/plotly/plotly.js/pull/3706/commits/fdfca3be78530b3e5411d94ae3537a7e287a3e12 where by changing the `tick0` dflt, we retrieve something almost identical to the baselines on `master`.

**Comment by archmoj** [comment]
Excellent.
@etpinard could you please increase the width and the height of this mock: test/image/baselines/geo_tick0.png

**Comment by archmoj** [comment]
Looks great!
:dancer: when you wanted to start 1.47.0.

**Comment by etpinard** [comment]
> when you wanted to start 1.47.0.

I'll wait for Monday.

**Comment by etpinard** [comment]
Ok, no new bug reports from 1.46.0 today, so let's start merging stuff for next week's 1.47.0

**Pull request merged**
