### PR TITLE
Exposing Button functions publicly on ModeBar class

### PR DESCRIPTION
**Pull request by alexander-alvarez**
Wanted to expose access to zoom, reset, etc functions.
I noticed that the functions didn't really need the ev.target since we already have the context of the button.

Then if you wanted to you can do:
```
// trigger autoscale without pressing button
gd._fullLayout._modeBar.getModeBarButtonFunction('autoScale2d')(gd)
```

Not sure how this fits into the longer term vision for modebar.

### CODE REVIEW

**Comment by etpinard** [comment]
@alexander-alvarez Thanks for the PR :beers: 


> I noticed that the functions didn't really need the ev.target since we already have the context of the button.

Good :eyes: , thanks!

About

```js
// trigger autoscale without pressing button
gd._fullLayout._modeBar.getModeBarButtonFunction('autoScale2d')(gd);
```

Diving into the `gd._` internal structure is far from recommended. In other words, your `getModeBarButtonFunction` won't be part of the official plotly.js API. 

Before finding ways to make it accessible from to the public, can I ask in what context would you want to retrieve a mode bar button function?

**Comment by alexander-alvarez** [comment]
> Diving into the gd._ internal structure is far from recommended. In other words, your getModeBarButtonFunction won't be part of the official plotly.js API.

Yes that is understood. It's public now within the context of the ModeBar but not Plotly, but ideally maybe we'd be able to hook into it pubically?

For me, I'm building a wrapper around Plotly and this was the only way I found to export hooks to the `autoscale` function, retaining the correct scope.

**Comment by etpinard** [comment]
@alexander-alvarez I think the best short-term solution would be add an `getState` function to the exposed `Plotly` object, where:

```js
var state = Plotly.getState(/* graph div element OR graph id string */);
``` 

where `state` would be an object with `data`, `layout`, `config` along with their 'full' counterpart (which include their default values) `fullData`, `fullLayout` and `fullConfig`.

Then, the default mode bar functions could be retrieved via:

```js
state.fullConfig.modeBarButtons[1][2].click;
```

What do you think?

**Comment by alexander-alvarez** [comment]
would this just be the backing data? or will it have access to the Plotly objects and their methods?

**Comment by etpinard** [comment]
[`click`](https://github.com/plotly/plotly.js/blob/master/src/components/modebar/buttons.js#L166) would be a function in this case.

**Comment by alexander-alvarez** [comment]
It's a good enough short term.

I guess in general I'm having a little more difficulty than I'd like accessing some functions that access data without 'breaking' scope. :cry: 

**Another example I just came across**
If I want to map colors out of the d3 scope to what's being shown in the chart (as in a scatter plot), ideally I'd have access to the [get_trace_color](https://github.com/plotly/plotly.js/blob/master/src/traces/scatter/get_trace_color.js) function on the scatter object. 

Currently it's only used to get to the `color` value and not assigned to the [Scatter namespace](https://github.com/plotly/plotly.js/blob/master/src/traces/scatter/index.js), and even then in order to access it I'd have to access it through 
```js
Plotly.Plots.modules.scatter._module.getTraceColor // _module breaks scope
```

Then I could call this for all my traces, and get the colors associated with them.

**Comment by booleanbetrayal** [comment]
I've found myself needing to modify modeBar buttons for localization support. Seems like there are some pretty viable use cases for a more general public accessibility.

**Pull request closed without merging**
