### PR TITLE
Disable dark highlights from Mesh3d

### LINKED ISSUE #3462: Black highlights on mesh3d on some devices
Areas of the `mesh3d` & `isosurface` that are opposite to the light source may be rendered in black on some devices e.g. Android.
This is a regression from #3415. 
newplot 18

### PR DESCRIPTION
**Pull request by archmoj**
Fixes #3462 using newly published `gl-mesh3d` module by not allowing negative highlights.
Example below illustrate a desirable result after using `gl-mesh3d` v.2.0.6
@etpinard cc: @plotly/plotly_js 
newplot 1 1

### CODE REVIEW

**Comment by etpinard** [comment]
Nice fix. Is there any way to test this fix?

**Comment by archmoj** [comment]
I used a mobile with [this codepen](https://codepen.io/MojtabaSamimi/pen/zexNbP).
Unfortunately I don't see a way to write a test for it.

**Comment by etpinard** [comment]
Ok, sounds good :dancer:

**Comment by etpinard** [comment]
Thanks for the quick fix @archmoj !

This thing will be out today, but I'll wait a couple more hours before releasing 1.44.1 in case other regression are detected.

**Comment by archmoj** [comment]
It would be great if we could follow up with #3380.

**Pull request merged**
