### PR TITLE
Provide computed margins in full-json export

### LINKED ISSUE #5185: fullJSON access to computed values
We need to expose *computed* `layout.margin` values in fullJSON somewhere, as well as the computed tickangle and other computed automargin-impacting values.

I propose that we either add a new "read only" `layout.computed` attribute that has sub-attributes `margin.{r,t,l,b}` and `x[2,3,4].{tickangle, etc}`.

Alternatively, we could overwrite these when doing the fullJSON export in `downloadImage` so these values are available via Python's new `full_figure_for_development` mechanism without new attributes.

### PR DESCRIPTION
**Pull request by archmoj**
Resolves #5185.

@plotly/plotly_js

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
I'd like this key to be called `computed` rather than `_computed` please, as leading underscores mean "private" in Python.

Also, we need an entry in the schema for this new key, so that the Python codegen adds the property accessors and so it appears in the reference documentation etc etc.

**Comment by nicolaskruchten** [comment]
Overall this looks good, but I'm seeing some odd behaviour with a figure like this one: https://codepen.io/nicolaskruchten/pen/wvWBmyQ

here the long x label is causing some automargin edge case: the right margin is increased because of the slanted label, but the bottom margin would exceed the cutoff so it resets. This is a known problem with automargins, and we don't need to tackle it now BUT the computed margin still shows `r: 80` for me, which is incorrect in this case.

**Comment by archmoj** [comment]
> Overall this looks good, but I'm seeing some odd behaviour with a figure like this one: https://codepen.io/nicolaskruchten/pen/wvWBmyQ
> 
> here the long x label is causing some automargin edge case: the right margin is increased because of the slanted label, but the bottom margin would exceed the cutoff so it resets. This is a known problem with automargins, and we don't need to tackle it now BUT the computed margin still shows `r: 80` for me, which is incorrect in this case.

Here is [a minimal codepen](https://codepen.io/MojtabaSamimi/pen/XWKJBJv?editors=0010) to illustrate the bug you mentioned.
@nicolaskruchten could you please confirm that it "sometimes" happening depending on the length of the long tick label?

**Comment by nicolaskruchten** [comment]
I haven't poked too much at when exactly it happens, sorry. Can we fix it in the case that I identified?

**Comment by alexcjohnson** [comment]
Given that the issue already exists in `fullLayout._size` I'd be happy to consider that an independent bug and merge this PR as is, for its own part this PR looks great. But @nicolaskruchten I'd understand if you want to delay merging this until we solve that, since the bug isn't currently exposed to users.

**Comment by nicolaskruchten** [comment]
Let's merge this as-is for release in 1.57 for our sponsor, and then open a separate issue for the `_size` and prioritize fixing that one, as now some internal things are external ;)

**Comment by archmoj** [comment]
:dancer: merging then...

**Pull request merged**
