### PR TITLE
Added cividis, a new colormap mathematically optimized while consider…

### PR DESCRIPTION
**Pull request by jamienunez**
…ing those with a color vision deficiency. Paper going through the review process: Nuñez J, Anderton C, and Renslow R. Optimizing colormaps with consideration for color vision deficiency to enable accurate interpretation of scientific data. 2018.

Thanks for your interest in plotly.js!

Developers are strongly encouraged to first make a PR to their own plotly.js fork and ask one of the maintainers to review the modifications there. Once the pull request is deemed satisfactory, the developer will be asked to make a pull request to the main plotly.js repo and may be asked to squash some commits before doing so.

Before opening a pull request, developer should: 

- `git rebase` their local branch off the latest `master`,
- make sure to **not** `git add` the `dist/` folder (the `dist/` is updated only on verion bumps),
- write an overview of what the PR attempts to do,
- select the _Allow edits from maintainers_ option (see this [article](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for more details).

Note that it is forbidden to force push (i.e. `git push -f`) to remote branches associated with opened pull requests. Force pushes make it hard for maintainers to keep track of updates. Therefore, if required, please `git merge master` into your PR branch instead of `git rebase master`.

### CODE REVIEW

**Comment by etpinard** [comment]
Can you share a screenshot of what that new colorscale looks like?

**Comment by alexcjohnson** [comment]
The test failure is just from using hard tabs - I'm surprised that this is breaking at the build step rather than syntax checking, but whatever, we use 4 spaces as a tab.

I guess `Cividis` is this: http://forum.imagej.net/t/new-lut-for-fiji-cividis/7467 - looks useful, I'd be happy to have it in plotly.js. We'll need a test image for it, ala https://github.com/plotly/plotly.js/blob/master/test/image/mocks/viridis_heatmap.json and baseline image https://github.com/plotly/plotly.js/blob/master/test/image/baselines/viridis_heatmap.png

**Comment by jamienunez** [comment]
Do you need the png itself or is it generated from the .json file? I created a similar figure but it doesn't look exactly the same as all the other heatmap mockups.

plotly_cividis

**Comment by etpinard** [comment]
> Do you need the png itself 

Yep, you'll need to the generate the png baseline (see [docs](https://github.com/plotly/plotly.js/tree/master/test/image#c-generate-or-update-existing-baseline-image)) in order to get the test to pass.

**Comment by jamienunez** [comment]
It looks like I'm unable to do this from my work computer since docker isn't too friendly with Windows 7. Is this an image that can be generated by your team? I can also try using the Linux VM set up on my home computer tonight if that is the easier route.

**Comment by alexcjohnson** [comment]
@jamienunez right, the docker setup is a bit finicky even on *nix systems. Anyway I've fixed the syntax and added the baseline image, will merge when tests pass. Thanks for adding cividis!

**Comment by chriddyp** [comment]
Hey @jamienunez - I included this feature in our release notes blog post: https://medium.com/@plotlygraphs/notes-from-the-latest-plotly-js-release-b035a5b43e21. Let me know if you'd like anything changed (chris[at]plot.ly) and thanks again for your contribution!

**Pull request merged**
