### PR TITLE
Added promise returns to Plotly.plot

### PR DESCRIPTION
**Pull request by tchandler**
Added promise rejections missed in https://github.com/plotly/plotly.js/pull/77 meant to resolve part of https://github.com/plotly/plotly.js/issues/76

All tests pass.

### CODE REVIEW

**Comment by etpinard** [comment]
@tchandler This looks good. Thank very much for doing this :beers: 

We should add to test cases in https://github.com/plotly/plotly.js/blob/master/test/jasmine/tests/plot_promise_test.js before merging.

I hope that you'll be up for the challenge :smirk: 

But, if you don't feel like it (which totally understandable), me or @mdtusz will gladly add the test cases for you. Cheers.

**Comment by tchandler** [comment]
@etpinard I'm working through the unit tests and I noticed something, in https://github.com/plotly/plotly.js/pull/77 the Promise returns that were added are implemented like this:
```javascript
new Promise.resolve(gd);
//or
new Promise.reject();
```

But you can't use `new` to construct immediate resolved/rejected promises, it throws a TypeError:

```
> new Promise.reject()
TypeError: function reject() { [native code] } is not a constructor
    at repl:1:1
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
```

I suspect the reason this doesn't break in production is because either the build fixes the error or the polyfill for Promises is implemented as a JS constructor function, which works just fine with that syntax:

```
> Promise = function() {}
[Function]
> Promise.resolve = function() {}
[Function]
> new Promise()
{}
> new Promise.resolve()
{}
```

I should have another commit for this in an hour or 2 that fixes the my and the other uses of `new Promise.reject/resolve`  and includes some unit tests to verify.

**Comment by mdtusz** [comment]
Good catch! Those were meant to be fixed in a PR that's been put on the backburner https://github.com/plotly/plotly.js/pull/149/files#diff-2941ab69a12080c0633ff4ac8ea3aa83R2176

We'll review what you've got once you've pushed up the next changes!

**Comment by mdtusz** [comment]
Changes and tests look good to me so I'll merge it in.

Thanks for the contribution!

**Pull request merged**
