### PR TITLE
Replace es6-promise module with native-promise-only module

### PR DESCRIPTION
**Pull request by archmoj**
As mentioned in https://github.com/plotly/plotly.js/issues/897#issuecomment-744512711 the `es6-promise@4.2.8` module uses function constructor in two places:
1. https://github.com/stefanpenner/es6-promise/blob/f97e2666e6928745c450752e74213d2438b48b4c/lib/es6-promise/polyfill.js#L13
2. https://github.com/stefanpenner/es6-promise/blob/f97e2666e6928745c450752e74213d2438b48b4c/lib/es6-promise/asap.js#L99

i.e. to global object.
See https://developer.mozilla.org/en-US/docs/Glossary/Global_object

While we only need promise polyfill in IE11, this PR suggests replacing [es6-promise module](https://www.npmjs.com/package/es6-promise) with [native-promise-only module](https://www.npmjs.com/package/native-promise-only) which listed second [here](https://ourcodeworld.com/articles/read/316/top-5-best-javascript-promises-polyfills) and also reduces the bundle sizes.

@plotly/plotly_js

### CODE REVIEW

**Review by alexcjohnson — APPROVED** [review]
If you've tested IE11 with an async plot (MathJax perhaps) and it works, then this is great! 💃

**Comment by nicolaskruchten** [comment]
From the readme of `native-promise-only` it's not clear to me if this supports IE11...?

**Comment by archmoj** [comment]
> native-promise-only

It does support IE11.
Have you noticed any particular problem?

**Comment by nicolaskruchten** [comment]
No, I just read the documentation looking for a clear assertion of IE11 support and didn't find one, but if you're confident about your IE11 testing, this seems like a great solution :)

**Pull request merged**
