### PR TITLE
new testbed docker image

### PR DESCRIPTION
**Pull request by perigee**
This is a part of issue https://github.com/plotly/streambed/issues/6226

1. add copying `index.html` file to remove MathJ font warning
2. remove no need ssh port expose
2. using candidate for this branch testing on circleci.

The new image version will be `1.1.0`

@etpinard  @mdtusz

### CODE REVIEW

**Comment by mdtusz** [comment]
Change the max-retries to something a bit greater than 8 (seems to work on the 9th try for me, so maybe 10?) And it's got my 💃 

I'll finally be able to test images!

**Comment by perigee** [comment]
@mdtusz  in case the nw fails in the middle of your image testing, then change retries to 10 will have no affect. :(

**Comment by mdtusz** [comment]
@perigee - with 8 retries, it always fails because the server takes so long to start on my machine. Setting the retries to 10 allows for it to connect and all the tests will run.

**Comment by mdtusz** [comment]
💃  from me. Will be great to get some image testing done locally 🎉

**Comment by etpinard** [comment]
:dancer: once you switched back those `candidate` tags for `latest`

**Pull request merged**
