### PR TITLE
Fix resizing `pie` like traces when `textinfo` is set to "none"

### PR DESCRIPTION
**Pull request by robbtraister**
If `textinfo==="none"`, the `textposition` coercion is skipped for both funnelarea and pie traces. However, there is a place in the plot render logic that assumes `textposition` is defined and is skipped iff `textposition==="none"` (https://github.com/plotly/plotly.js/blob/master/src/traces/pie/plot.js#L136).

Since the coercion is not enforced and `textposition` is undefined (not `"none"`), related text objects which have not been initialized are attempted to be accessed resulting in a null pointer exception (https://github.com/plotly/plotly.js/blob/master/src/traces/pie/plot.js#L511).

I am open to alternative solutions that may include a `textinfo==="none"` check in the plot render logic, but this approach seemed to be the most comprehensive.

Reproduction example: https://github.com/robbtraister/plotly-npe

### CODE REVIEW

**Comment by archmoj** [comment]
I was not able able to replicate the bug on this [codepen](https://codepen.io/MojtabaSamimi/pen/JjVYpbw?editors=0010).
Please feel free to open a bug report or reopen this pull request, in case you hit it again.
Thank you!

**Comment by robbtraister** [comment]
@archmoj as I described in the repro repo, you have to mouseover the plot first, then attempt to resize.

Kapture 2024-03-06 at 13 49 49

**Comment by robbtraister** [comment]
I do not have permissions to reopen this pull request

**Comment by archmoj** [comment]
> @archmoj as I described in the repro repo, you have to mouseover the plot first, then attempt to resize.
> 
> Kapture 2024-03-06 at 13 49 49 [ Kapture 2024-03-06 at 13 49 49 ](https://private-user-images.githubusercontent.com/5815296/310618757-938e3d85-5b88-4e74-abae-f7e47c34b4d7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NTIwNzgsIm5iZiI6MTcwOTc1MTc3OCwicGF0aCI6Ii81ODE1Mjk2LzMxMDYxODc1Ny05MzhlM2Q4NS01Yjg4LTRlNzQtYWJhZS1mN2U0N2MzNGI0ZDcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMTkwMjU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQyYjYxZGQzMTY1NjFmOWMyNzRjYjk5MjBmZjQyOTJiOTM0MDA0NjFkOGE3N2YwNTY5NmZjOTA1ZTk2YjI2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0w7_oBkLGsenDunQfVDDvFCz-5jq4JROdJblKLxhsuM) [ ](https://private-user-images.githubusercontent.com/5815296/310618757-938e3d85-5b88-4e74-abae-f7e47c34b4d7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NTIwNzgsIm5iZiI6MTcwOTc1MTc3OCwicGF0aCI6Ii81ODE1Mjk2LzMxMDYxODc1Ny05MzhlM2Q4NS01Yjg4LTRlNzQtYWJhZS1mN2U0N2MzNGI0ZDcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMTkwMjU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQyYjYxZGQzMTY1NjFmOWMyNzRjYjk5MjBmZjQyOTJiOTM0MDA0NjFkOGE3N2YwNTY5NmZjOTA1ZTk2YjI2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0w7_oBkLGsenDunQfVDDvFCz-5jq4JROdJblKLxhsuM)

Thanks very much for clear bug report. :pray:
Let me have a second look. I would try to include the fix in the next plotly.js minor possibly today.

**Comment by archmoj** [comment]
Thanks very much for this PR.
:dancer:

**Pull request merged**
