### PR TITLE
Fix for openmaptiles open sans extrabold

### PR DESCRIPTION
**Pull request by birkskyum**
Openmaptiles call the Open Sans Extrabold for Open Sans Extra Bold
- https://github.com/openmaptiles/fonts/issues/24

Affecting the scattermapbox trace

### CODE REVIEW

**Comment by archmoj** [comment]
Some carto mapbox baseline failures are fixed in https://github.com/plotly/plotly.js/pull/7019 today.
Please fetch upstream/master and then merge master into this pull request as well as into other PRs you have open.
Thank you!

**Comment by archmoj** [comment]
The extra bold does not render properly on this branch if you view `mapbox_fonts-supported-open-sans-weight` mock.

**Comment by birkskyum** [comment]
Hmm, so it's not broken in the first place? Strange, i had that impression.

**Comment by birkskyum** [comment]
Ah, it's because this is a problem only after moving to maplibre, where the Extra Bold font appear completely missing, and adding this patch does render text, but it's not bold.

**Comment by archmoj** [comment]
> Ah, it's because this is a problem only after moving to maplibre, where the Extra Bold font appear completely missing, and adding this patch does render text, but it's not bold, so there is a fix needed for that in the MapLibre branch.

OK. Let's keep the patch inside the `maplibre` PR.
Thank you.

**Pull request closed without merging**
