### PR TITLE
More hovertemplates!

### PR DESCRIPTION
**Pull request by etpinard**
checking out a few boxes off https://github.com/plotly/plotly.js/issues/3437

cc @plotly/plotly_js @nicolaskruchten I'll push a commit for hovertemplate + parcats at some point next week. I might even try adding support for `hovertemplate` for a few traces before 1.45.0 is ready.

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Awesome! These are the missing few for `px` :D

**Comment by etpinard** [comment]
I put `parcats` + `hovertemplate` on hold until https://github.com/plotly/plotly.js/issues/3437#issuecomment-462183771 is resolved:

> Hmm well, I guess for `parcats` we could use the `line` container and then maybe coerce a `hovertemplate` inside each `dimensions` item? Or maybe have the root `hovertemplate` apply to all the dimensions/nodes and be ignored when hovering on links?

but now `heatmap`, `contour`, `histogram2d`, `histogram2dcontour` and `scattercarpet` have support for `hovertemplate`.

**Comment by etpinard** [comment]
`parcats` has now hover-template support, making this thing `status: reviewable`.

@antoinerg would you mind reviewing this one?

**Comment by antoinerg** [comment]
Thank you @etpinard for adding support for `hovertemplate` to that many traces :muscle: . The addition of `arrayOk` to `hovertemplate` is also very welcome :fire: 

In summary, this PR adds support to the following traces:
- cone            (with new test)
- contour
- heatmap
- histogram
- histogram2d
- histogram2dcontour
- isosurface      (with new test)
- mesh3d
- parcats         (with new test)
- scatter3d
- scattercarpet   (with new test)
- splom           (with new test)
- streamtube      (with new test)
- surface

We don't have `hovertemplate` tests for every single trace but that was probably overkill anyway since most of them reuse the same code pathway.

I say this is ready to :dancer:

**Comment by etpinard** [comment]
> We don't have `hovertemplate` tests for every single trac

Yes I think we do, at least I tried. See the `hover_label_test.js` and `gl3d_plot_interact.js` suites.

**Comment by antoinerg** [comment]
@etpinard I confirm that you added tests to all the traces fro which `hovertempate` support was added in this PR! Amazing :smile: 

:dancer:

**Pull request merged**
