### PR TITLE
Fixup hover on period positioned points

### LINKED ISSUE #5553: Hover rules for period-positioned traces
These invariants should hold for period-positioned traces (the word "point" below should be taken to mean scatter marker or bar or whatever other kind of period-positioned mark we have) in both compare and unified hovermodes:
* a period-positioned point *must not* "win the hover" if the cursor is not within the period that the point represents (i.e. a scatter point with x='2010-02-15', xperiod='M1', xperiodalignment='start' must not win the hover even if the cursor is extremely close to it on the left side)
* a period-positioned point *must* be in the "hover set" (for compare or unified hover modes) if the point that wins the hover is within the period that the point represents (i.e. a scatter point with x='2010-02-15', xperiod='M1', xperiodalignment='start' must be in the hover set if the cursor is positioned at March 2 and the non-period-positioned point that won the hover is at Feb 28)

cc @alexcjohnson 

See also https://github.com/plotly/plotly.js/issues/5292

### PR DESCRIPTION
**Pull request by archmoj**
Closes #5553.

[demo](https://codepen.io/MojtabaSamimi/pen/VwPOqgN?editors=0010)

TODOs: 
 - [x] add jasmine test
 - [x] test traces other than bars
 
@plotly/plotly_js

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
This does seem like an improvement, yes!

**Comment by alexcjohnson** [comment]
If I give the scatter trace in your demo a period of its own, we again get multiple labels for that one trace.

Screen Shot 2021-05-06 at 9 20 13 AM


https://codepen.io/alexcjohnson/pen/NWpWOdQ?editors=0010

**Comment by nicolaskruchten** [comment]
I think there's another invariant here that we could maybe implement fairly easily, which should be implicit but let's make explicit:
* there should never be more than one point from the same trace in the same hoverset
 
no? Seems like a straightforward filter operation?

**Comment by alexcjohnson** [comment]
> Seems like a straightforward filter operation?

Yes, though there may be cases where we lose track of which is the "best" point by the time we're ready to do this filter.

Fixes like this PR may be the best route in the short term, but I think all of this does point to a need eventually to take a step back and reconceptualize our hover/spike picking framework in order to satisfy the invariants @nicolaskruchten has stated, among others that are already assumed, at an architectural level rather than by layering on more tweaks.

**Comment by archmoj** [comment]
> If I give the scatter trace in your demo a period of its own, we again get multiple labels for that one trace.
> 
> Screen Shot 2021-05-06 at 9 20 13 AM
> 
> https://codepen.io/alexcjohnson/pen/NWpWOdQ?editors=0010

Good catch. Fixed by https://github.com/plotly/plotly.js/pull/5618/commits/543698a8b097f576f326f8964227e2c620bcac6c.

**Comment by archmoj** [comment]
> I think there's another invariant here that we could maybe implement fairly easily, which should be implicit but let's make explicit:
> 
> * there should never be more than one point from the same trace in the same hoverset
> 
> no? Seems like a straightforward filter operation?

Noting that some trace types produce multiple hover points; so we cannot perform that in general.
But in the case of this particular problem noticed above (i.e. when a period positioned point wins) such an operation is helpful and was missing. 
See: https://github.com/plotly/plotly.js/pull/5618/commits/543698a8b097f576f326f8964227e2c620bcac6c

**Comment by nicolaskruchten** [comment]
@alexcjohnson can we please get this reviewed and landed, ideally this week? :)

**Comment by alexcjohnson** [comment]
Clear improvement. There are three funny cases I want to point out, though we may choose not to do anything about them:

(1) the only place I can put the mouse and NOT get a label for any bar is slightly to the left of a first-of-month scatter point:
Screen Shot 2021-05-12 at 11 27 01 AM
If I put the mouse to the right of this point I do get a bar hover:
Screen Shot 2021-05-12 at 11 27 09 AM
This is presumably because the mouse is not over the range of the bar that matches the winning scatter point - so we include the previous bar in our original set of hovered points but then disqualify it because it's inconsistent with the scatter point.
This happens at all month boundaries in `x` mode, but if I switch to `x unified` mode, I see this behavior on the Dec/Jan boundary:
Screen Shot 2021-05-13 at 8 57 09 AM
but not on the Jan/Feb boundary, there I always get the Feb bar no matter where my mouse is:
Screen Shot 2021-05-13 at 8 57 24 AM

(2) When I zoom in enough, there are gaps between scatter points so that none of them are hovered, and only a bar is shown in the hover info. But if I set `xperiod` to 5 days on the scatter trace, I would have expected that no matter how much I zoom in there would be a winning scatter point, because I'm always over the period of one of them. That doesn't happen, in either `x` or `x unified` hovermode. In both modes there's still a gap where I only see the bar's hover.

(3) Except in a very narrow set of conditions, when no matter which scatter gap my mouse is in, the middle scatter point is included in hover data with the bar. I only see this with an `xperiod` on the scatter and in `x` hovermode - not with instant-positioned scatter points and not with `x unified`, and at least in the codepen given there's a very narrow zoom range where this happens, immediately after gaps in the scatter have opened up but before they get too big. Here my mouse is on about Jan 27:
Screen Shot 2021-05-13 at 8 48 02 AM
(This third point may become moot if we choose to address the second point)

**Comment by archmoj** [comment]
> Clear improvement. There are three funny cases I want to point out, though we may choose not to do anything about them:
> 
@alexcjohnson thanks very much for the review.
I suggest we attempt addressing those edge cases in separate PRs to have this improvement as the baseline, also to unblock other development/testing around hover.

**Comment by nicolaskruchten** [comment]
Thanks for the dive-in Alex! I'll take a close look at them early next week but I don't think any of them break the invariants in https://github.com/plotly/plotly.js/issues/5553 which this PR is meant to enforce, so I think I agree with Mojtaba that if the implementation looks good we should merge this PR.

**Review by alexcjohnson — APPROVED** [review]
Works for me. Looks good! 💃

**Pull request merged**
