### PR TITLE
using a more recent nodejs v12 and Chrome verisions on the CircleCI

### PR DESCRIPTION
**Pull request by archmoj**
The version of node.js used on CircleCI is set to `v12.13.0`.
The most recent node v12 is at `v12.22.1`. 

Browsers used in jasmine tests:

Before: Chrome 78.0.3904.108
After: Chrome 90.0.4430.72

Before: Firefox 70.0
After Firefox 87.0

@plotly/plotly_js

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Why do the tests fail with higher versions?

**Comment by archmoj** [comment]
> Why do the tests fail with higher versions?

Good question.
For example with `v12.16.3` there is this kind of failure: 
node12 16 3

**Comment by nicolaskruchten** [comment]
Seems like our tests are a little too exacting ... we're talking about a 1e-5 change here, totally imperceptible :)

**Comment by alexcjohnson** [comment]
Right, if these test failures are all just rounding errors let's loosen the tests and upgrade to the latest node.

**Pull request merged**
