### PR TITLE
 Use correct parent document when necessary: fixes 702 #2 

### PR DESCRIPTION
**Pull request by nielsenb-jf**
This pull request fixes the issues noted in [issue 702](https://github.com/plotly/plotly.js/issues/702). Essentially, if Plotly was provided an element in a different window or tab, the plot would not be styled correctly and interactivity (hovers, drag zoom, etc.) would not work.

The following are the big changes to fix this issue:

- Graph divs now keep a reference to their 'parent' document in the `_document' property.
- Styles are now injected to the parent document on the first call to `Plotly.plot`.
- Anything that draws over a document for interactivity purposes (eg. dragcovers), now uses the `_document` reference to ensure it is drawn in the correct document.
- Notifiers now require a graph div as the first argument so that notifications are rendered in the correct place

### CODE REVIEW

**Comment by etpinard** [comment]
Hmm. Something went wrong with your `git rebase`. I'll pull down your branch and rebase the commits when I get the time this week.

**Comment by nielsenb-jf** [comment]
Is it griping about "Commit 212d5f... being a merge, but no -m option given"?

If you figure out how I broke that, I'd love to hear it so I can avoid this again.

**Comment by etpinard** [comment]
@nielsenb-jf I squashed together all commits in your `child_window_fixes` branch and push to a new branch [`squash-child-window`](https://github.com/plotly/plotly.js/compare/squash-child-window). I proposed closing this PR and opening a new one off my `squash-child-window` branch. This would lead to some good and bad news:

Good news: you'll get one authoring commit
Bad news: you'll only get one authoring commit

But one thing is sure: merging 115 commits of git frustration :arrow_double_up:  won't happen.

Alternatively, you can also try:

- fetching the `squash-child-window` branch unto your fork
- run `git reset HEAD^` to reset the BIG squashing commit 4cb2c7c43f6d0004d53d3be61fcedcec2176191c
- `git add` and `git commit` your work into multiple commits
- and then `git push -f` unto your `child_window_fixes` branch

Thanks again for your hard work!

**Comment by nielsenb-jf** [comment]
I'm on board for one "BIG ASS CHILD WINDOW COMMIT". Thanks for your help!

[New PR](https://github.com/plotly/plotly.js/pull/763)

**Pull request closed without merging**
