### PR TITLE
Bump madge 6 -> 8

### PR DESCRIPTION
**Pull request by birkskyum**
Adds support for node 20, min. supported version is node 18.

[Changelog](https://github.com/pahen/madge/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by archmoj** [comment]
In which file it is required?

**Comment by birkskyum** [comment]
Only in test_syntax.js

**Comment by archmoj** [comment]
Is test_syntax.js still used after biome changes?

**Comment by birkskyum** [comment]
I don't know if it's needed, but it's still executed from the .circleci/test.sh -> test-syntax -> `node tasks/test_syntax.js`

**Pull request merged**
