### PR TITLE
Hoverlabel.zformat

### PR DESCRIPTION
**Pull request by jdugge**
Add a `zhoverformat` option to `heatmap` and `contour` traces which specifies the number format to use for displaying `z` values.

### CODE REVIEW

**Comment by etpinard** [comment]
@jdugge would you mind fixing the conflict in `fx/hover.js`?

**Comment by jdugge** [comment]
The conflict is resolved, as is a formatting error that caused lint to complain. The failure of `select_test` seems to be unrelated to this PR, as other currently open PR's have the same error?

**Comment by jdugge** [comment]
Alright, I think that's it :crossed_fingers:

**Comment by etpinard** [comment]
Ooh, I forget to merge this thing. Big shoutout to @jdugge for this solid PR! 

This will be part of the `1.32.0` release (set for mid-week next-week).

**Pull request merged**
