### PR TITLE
Disable text selection

### LINKED ISSUE #5021: Disable text selection
It always bugs me that dragging sometimes selects text on our figures in a way that makes it hard to unselect... Should we use https://css-tricks.com/almanac/properties/u/user-select/ for stuff like ticklabels and legends and such? Maybe not annotations or trace data text.

### PR DESCRIPTION
**Pull request by archmoj**
Fixes #5021.

@plotly/plotly_js

### CODE REVIEW

**Comment by alexcjohnson** [comment]
@nicolaskruchten mentioned leaving annotations and scatter text selectable, but ATM these elements already can't be selected normally, due to the way we capture pointer events.

That in mind, would it cause any problems to just put `user-select: none` at the [top level](https://github.com/plotly/plotly.js/blob/86f5e2d02d56a94fcf2c26b30d3539fd54211c40/src/css/_base.scss#L1-L6) and drop it everywhere else?

Note that ATM we specifically prevent selection on several specific elements, though a few of them (sankey and parcoords) use the simple version without vendor prefixes, which should be fixed if we don't switch to the top level.
```
 ~/plotly/plotly.js/src> ag user-select
traces/sankey/render.js
1029:        .style('user-select', 'none')

traces/parcoords/parcoords.js
354:        .style('user-select', 'none');
659:        .style('user-select', 'none');
676:        .style('user-select', 'none')

traces/carpet/plot.js
242:            .classed('user-select-none', true)

css/_base.scss
26:.user-select-none {
27:    @include vendor('user-select', none);

components/legend/draw.js
92:            .classed('user-select-none', true)
413:        .classed('user-select-none', true)

components/updatemenus/draw.js
198:        s.classed('user-select-none', true)
438:        s.classed('user-select-none', true)

components/rangeselector/draw.js
147:        s.classed('user-select-none', true)

components/sliders/draw.js
305:        s.classed('user-select-none', true)
360:        s.classed('user-select-none', true)

plots/gl2d/scene2d.js
151:    canvas.className += ' user-select-none';
```

**Comment by archmoj** [comment]
One could select annotations and data text on master at the moment. So if we want to keep them as they are, I could make the adjustments?

**Review by alexcjohnson — APPROVED** [review]
Very nice! Let's also remove the `.style('user-select', 'none')` in [sankey](https://github.com/plotly/plotly.js/blob/cab62647f4c0bd29db24cadb48154b8459e7d045/src/traces/sankey/render.js#L1029) and [par](https://github.com/plotly/plotly.js/blob/cab62647f4c0bd29db24cadb48154b8459e7d045/src/traces/parcoords/parcoords.js#L354) [co](https://github.com/plotly/plotly.js/blob/cab62647f4c0bd29db24cadb48154b8459e7d045/src/traces/parcoords/parcoords.js#L659) [ords](https://github.com/plotly/plotly.js/blob/cab62647f4c0bd29db24cadb48154b8459e7d045/src/traces/parcoords/parcoords.js#L676), but then this looks good to go! 💃

**Comment by archmoj** [comment]
@alexcjohnson 
Seems we cannot remove `user-select` calls is `sankey` and `parcoords` as tried in https://github.com/plotly/plotly.js/pull/5165/commits/89e1342af0b2288652e97b8bd3fe4e96aafe4461.
So I reverted that commit.

**Comment by alexcjohnson** [comment]
> @alexcjohnson
> Seems we cannot remove `user-select` calls is `sankey` and `parcoords` as tried in [89e1342](https://github.com/plotly/plotly.js/commit/89e1342af0b2288652e97b8bd3fe4e96aafe4461).
> So I reverted that commit.

That commit also removes the `user-select-none` class from the main div

**Comment by bharatkrishna** [comment]
Is there a way to override this when using dash so that I can select axis values. This is with reference to [this post](https://community.plotly.com/t/selecting-copying-axis-label-text-and-table-cell-contents/47805) on plotly forums.

**Comment by archmoj** [comment]
> Is there a way to override this when using dash so that I can select axis values. This is with reference to [this post](https://community.plotly.com/t/selecting-copying-axis-label-text-and-table-cell-contents/47805) on plotly forums.

Not at the moment. But you could try removing  'user-select-none': true CSS from the svg container.

**Comment by bharatkrishna** [comment]
@archmoj how do I do that? In Dash, [graph_objects.Scatter](https://plotly.com/python-api-reference/generated/plotly.graph_objects.Scatter.html) doesn't seem to have any argument to override the CSS. Or do I set 'user-select-none': false as the style of the Div which contains the plot svg?

**Comment by archmoj** [comment]
> @archmoj how do I do that? In Dash, [graph_objects.Scatter](https://plotly.com/python-api-reference/generated/plotly.graph_objects.Scatter.html) doesn't seem to have any argument to override the CSS. Or do I set 'user-select-none': false as the style of the Div which contains the plot svg?

Hmm that may not be going to work.
Curious to know how selecting text is useful in your app. You can open a feature request.

**Comment by bharatkrishna** [comment]
> Hmm that may not be going to work.
> Curious to know how selecting text is useful in your app. You can open a feature request.

Yes it was important in my app. The x-axis items contained timestamps or serial numbers I copy-past into another application to get more details. I.e when I see certain upswings or downswings in the line plot, I take copy x-axis labels to examine them further. In case of items like timestamps, it is not easy to re-type them but rather copy-paste them is.

**Pull request merged**
