### PR TITLE
Bump `maplibre-gl` v4.5.2

### PR DESCRIPTION
**Pull request by archmoj**
@birkskyum Please review the baseline changes.
Thank you!

cc: @plotly/plotly_js s

### CODE REVIEW

**Comment by birkskyum** [comment]
I don't see a diff anywhere.

**Comment by archmoj** [comment]
There is a slight change there if you use the **swipe** option.

Screenshot from 2024-08-13 10-36-53

Here is the location of the diff from image comparison test on CircleCI.
diff-map_layers

As well as for `diff-map_predefined-styles2` we have:
diff-map_predefined-styles2

**Comment by archmoj** [comment]
@birkskyum This might be fine. 
Just wanted to double check with you if this is alarming in respect to some changes between `maplibre-gl` versions.

**Comment by birkskyum** [comment]
Hmm, It could be a tile that didn't manage to load the expected zoom level and used a blurred tile from the zoom level above, if it didn't have time enough.

**Comment by archmoj** [comment]
@birkskyum I'll move forward and merge this PR.
Please feel free to open a PR in case needed.
Thank you!

**Pull request merged**
