### PR TITLE
issue #1160 fix

### PR DESCRIPTION
**Pull request by adamborowski**
If we play with timestamps, we have to leave range bounds integers

### CODE REVIEW

**Comment by etpinard** [comment]
Thanks for submitting a PR!

Looking like your patch unfortunately breaks zoom for non-date axes. 

I'll look for a better solution. This bug is most likely a side-effect of https://github.com/plotly/plotly.js/pull/1078

**Comment by adamborowski** [comment]
Yes, we can check if ax.type === 'date' then round the range

**Comment by etpinard** [comment]
@adamborowski @alexcjohnson I think https://github.com/plotly/plotly.js/commit/683d38a4395cf2f1a584c9e89892baf9ec41643c would be the most robust way to fix this issue.

@adamborowski to make sure your work is rewarded, I'll apply the above commit on top of your https://github.com/plotly/plotly.js/pull/1161/commits/d7de2ae6b0d11fe0d47af7c6a08d028d72b761ab commit, add a few tests and make another PR. Thanks very much for your efforts :beers:

**Comment by etpinard** [comment]
replaced by https://github.com/plotly/plotly.js/pull/1162

**Pull request closed without merging**
