### PR TITLE
Minor fixes to allow null frames internally

### PR DESCRIPTION
**Pull request by rreusser**
This PR adds a small test and a couple fixes to prevent plotly from breaking on null frames. This is necessary for transforms that directly add or remove frames. If they remove frames, they should avoid compressing the array so that indices don't change. This means `null` or `undefined` entries in the frame array should simply be ignored.

### CODE REVIEW

**Comment by etpinard** [comment]
fyi @rreusser you'll need to merge master to make

image

pass again.

**Comment by etpinard** [comment]
Making `Plotly.animate` and friends skip over blank frames makes sense. Thanks for cleaning that up :beers:

I wonder though, if we could expose a way through `Plotly.animate` to make a graph _go back_ to its original `"data"` / "layout"` settings?

**Comment by rreusser** [comment]
Short answer… no. I don't see any way to accomplish this without structural changes to animation. As discussed previously, I think the solution would be frames that you would toggle on/off. On each data -> fullData step, it would merge any 'on' frames. Turning the frames off would restore it to the original state.

**Comment by etpinard** [comment]
Thanks for the reply @rreusser 

> Turning the frames off would restore it to the original state.

This would certainly make `layout.breakpoints` frames easier to deal with. 

Perhaps (or not) this could as easy as adding a `type` key to the frame attributes. `type` would be an enumerated with possible values: `'sequencial'` and `'toggle'`.

**Comment by rreusser** [comment]
Yeah, I think with all the other machinery in place and with a much better understanding of what we're after that this might actually not be so difficult. The reason this wasn't done to begin with is that one solution _cannot_ handle both ephemeral update-and-forget-about-it updates _and_ stateless toggle updates. I think it would be worthwhile though.

**Comment by etpinard** [comment]
:dancer:

**Pull request merged**
