### PR TITLE
Don't try to draw spikeline if the axis isn't on the chart.

### PR DESCRIPTION
**Pull request by rpaskowitz**
Noticed the line wasn't being drawn and errors were being logged to console on the last chart at https://plot.ly/javascript/line-charts/. This should clean that up.

### CODE REVIEW

**Comment by etpinard** [comment]
Hmm. I'm not convinced this is the desired behavior (even though this patch clears some console errors). I can see spikes on invisible axes being somewhat useful (?)

**Comment by etpinard** [comment]
cc @alexcjohnson

**Comment by alexcjohnson** [comment]
Nice catch @rpaskowitz! But I think @etpinard is right, we should find a way to still show the spikes. Particularly in `across` mode the spike can be useful without pointing to a labeled value on an axis.

I propose that if the axis is invisible, we act as though it would have been at the farthest left/bottom of all subplots it's used in. Sound reasonable?

**Comment by rpaskowitz** [comment]
Yeah, given the use of comparing data points, still drawing the line makes sense.

**Comment by etpinard** [comment]
Will be fixed in https://github.com/plotly/plotly.js/pull/1980

**Pull request closed without merging**
