### PR TITLE
Clear parcoords canvas specially if no panels exist

### PR DESCRIPTION
**Pull request by monfera**
Reason: if there's no panel, then the panel redaw loop will not enter the loop body that also clears the canvas, causing uncleared lines when only 0 or 1 dimension exists (as visible dimensions) after rendering, then making other dimensions go invisible with `Plotly.restyle`.

### CODE REVIEW

**Comment by etpinard** [comment]
Great! Can you add a test case to :lock: this down?

**Comment by etpinard** [comment]
This fix would be nice addition to the next patch release `1.24.1`. @monfera have you had the time to think about a way to add a test case?

**Comment by monfera** [comment]
@etienne my conclusion from our chat is that we'll need to persist the regl object on the <canvas> element; it'll make it possible to have access to it for testing. I can go ahead with it today.

**Comment by monfera** [comment]
@etpinard specifically, we already bind (with D3) the lineLayer object that has a readPixel method for picking - I'll just make a similar method for reading all pixels in a rectangle, so no need for the entire regl object.

**Comment by etpinard** [comment]
> specifically, we already bind (with D3) the lineLayer object that has a readPixel method for picking - I'll just make a similar method for reading all pixels in a rectangle, so no need for the entire regl object.

Sounds good. Thanks!

**Pull request merged**
