### PR TITLE
Use jasmine-core 3.4.0

### LINKED ISSUE #3368: Adapt jasmine tests for jasmine-core@3
```
npm i jasmine-core@3.3.0 karma.jasmine@2.0.1
npm run test-jasmine -- --nowatch
```

make numerous tests fail, spits out deprecation warnings:

image

and doesn't get along with our `negateIf` custom matcher

https://github.com/plotly/plotly.js/blob/cbaae9a41e95161a839d2084ac984863f427f10d/test/jasmine/assets/custom_matchers.js#L212-L215

image

----

More info about jasmine@3:

https://github.com/jasmine/jasmine/blob/master/release_notes/3.0.md

More info about karma-jasmine@2:

https://github.com/karma-runner/karma-jasmine/blob/master/CHANGELOG.md#200-2018-11-15

### PR DESCRIPTION
**Pull request by etpinard**
resolves #3368 - getting up-to-speed with the latest version of our test framework, which has two new CLI configs: 

- `random`, which randomises the test ordering (N.B. jasmine turns this on by default, but we set it to false by default as this would make many of our tests fail)
- `failFast`, so we don't need that `karma-fail-fast-reporter` plugin

About the `negateIf` commit, see https://github.com/plotly/plotly.js/issues/3368#issuecomment-501347522 for more info.

### CODE REVIEW

**Comment by archmoj** [comment]
Excellent.
:dancer: :dancer: :dancer:

On another note, I am wondering about the root of this warning (happening on master/here, both locally & using CI)?
Screenshot from 2019-06-17 20-40-05

**Comment by alexcjohnson** [comment]
> I am wondering about the root of this warning

this is intentional and has been there forever - though it would be nice to silence it! Pretty sure it's this:

https://github.com/plotly/plotly.js/blob/56f3bb7aed1ccb9848c31622b833a25c848d4519/test/jasmine/tests/layout_images_test.js#L324-L327

**Comment by etpinard** [comment]
> Pretty sure it's this [that `layout_images_test.js` test]

Yes, that's the one. But the `404: /invalidUrl` message comes from 

https://github.com/plotly/plotly.js/blob/2b4de3ebe45657eddf29fcf72dc58b96cb5f672b/src/components/images/draw.js#L111

which is tricky to mock while still testing this handler:

https://github.com/plotly/plotly.js/blob/2b4de3ebe45657eddf29fcf72dc58b96cb5f672b/src/components/images/draw.js#L113-L116

----

So, I'll pass. I hope you don't find the `404: /invalidUrl` message that annoying.

**Comment by etpinard** [comment]
Fun fact, during the merge commit, all shards in `test-jasmine2` and `test-jasmine3` passed on the first attempt:

image

:tada:

**Pull request merged**
