### PR TITLE
Match Cartesian axes with identical invisible reference

### LINKED ISSUE #4501: Axis matching limitation
This is a pretty problematic case for Plotly.py: https://codepen.io/nicolaskruchten/pen/ExaOMRr?editable=true

In this case, all axes have `matches` set to the first axis (`x` or `y`) but those axes have no traces, so no information is being shared among the axes that *do* have traces.

I'd be tempted to call this a bug... thoughts @alexcjohnson @archmoj ?

This is a problem for Plotly.py because `make_subplots` creates subplots and sets `matches` *before* knowing which subplots have traces.

### PR DESCRIPTION
**Pull request by archmoj**
Fixes #4501.

Demos:
- [Before](https://codepen.io/MojtabaSamimi/pen/mdyvRJo?editors=0010)
-  [After](https://codepen.io/MojtabaSamimi/pen/gObqgaJ?editors=1000)

@alexcjohnson 
cc: @nicolaskruchten @plotly/plotly_js

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Does this PR check to make sure that the new `matches` target is a valid one with traces? Or if not, do all references get cleaned up? For example if x2, x3, x4, x5 are all matching x and x is invalid and we make them all point to x2 but then x2 is invalid also do we then match them all to x3?

**Comment by archmoj** [comment]
> Does this PR check to make sure that the new `matches` target is a valid one with traces? Or if not, do all references get cleaned up? For example if x2, x3, x4, x5 are all matching x and x is invalid and we make them all point to x2 but then x2 is invalid also do we then match them all to x3?

It does only search within valid axes. So this should not be a problem.
BTW it would be great to test the demo posted on the PR description with more combinations.

**Comment by alexcjohnson** [comment]
One thing this approach misses is if the lost axis sets an explicit `range` or `rangemode` https://codepen.io/alexcjohnson/pen/wvBNXgY?editors=0010
That seems like something we want to support, right?

**Comment by nicolaskruchten** [comment]
Ah drat. Also `categoryarray` and any other axis-related option I would guess. That is a drawback to this approach: you need to copy everything over basically

**Comment by archmoj** [comment]
Then, should x.range override x2.range if both specified?

**Comment by alexcjohnson** [comment]
> should x.range override x2.range if both specified?

The answer to that is "exactly whatever would have happened if there was data on the xy subplot" - I don't know how we handle that though I'd guess that `xaxis.range` wins.

**Comment by archmoj** [comment]
Closing in respect to #4529.

**Pull request closed without merging**
