### PR TITLE
Mock additions for persistent point selection

### PR DESCRIPTION
**Pull request by monfera**
New mocks as part of reviewing https://github.com/plotly/plotly.js/pull/2135 to see it with various traces, and also also because of Étienne's travel.

### CODE REVIEW

**Comment by etpinard** [comment]
Can you please make a PR to https://github.com/plotly/plotly.js/pull/2135 instead of `master`?

**Comment by monfera** [comment]
Ah indeed, thanks, changed!

**Comment by monfera** [comment]
The bar looks good on initial render except where I have a small question:
image
The `selectedpoints` is `[0, 1, 4]` but the last highlighted orange bar is of index 5. The reason is that the `]3.5, 4.5[` filter transform eliminates one point. So I just wanted to make sure it's OK that post-filter point indices are used rather than pre-filter.

In the second bar trace, ie. last trace, both `selected` and `unselected` are specified as orange. When clearing the selection, it'll be all green but iirc there's some todo item for bars, perhaps this.
tmp
That the legend also shows both traces in green is probably the same thing.

**Comment by etpinard** [comment]
Superseded by https://github.com/plotly/plotly.js/pull/2135/commits/3d2049c0c6ada1c741da27184704e1c477227a6b in https://github.com/plotly/plotly.js/pull/2135

**Pull request closed without merging**
