### PR TITLE
removed colorscale attribute from mesh3d

### PR DESCRIPTION
**Pull request by VeraZab**
that attribute shouldn't exist for that trace

### CODE REVIEW

**Comment by etpinard** [comment]
Looks like a lot code downstream of `mesh3d/attributes.js `relies on `colorscale`. For example,

- in default.js [here](https://github.com/plotly/plotly.js/blob/5dc63d573b40b6863faf7c3e2001ed05b7f91c69/src/traces/mesh3d/defaults.js#L66)
- convert.js [here](https://github.com/plotly/plotly.js/blob/5dc63d573b40b6863faf7c3e2001ed05b7f91c69/src/traces/mesh3d/convert.js#L127)

causing a few image tests to fail.

But, looks like `gl-mesh3d` does handle color maps [here](https://github.com/gl-vis/gl-mesh3d/blob/7bbbb5ea76185b8be5403b679abd80a996ce4b9e/mesh.js#L267). Maybe we just got lazy and never added a test and docs for them?

@VeraZab this block [here](https://github.com/plotly/plotly.js/blob/5dc63d573b40b6863faf7c3e2001ed05b7f91c69/src/traces/mesh3d/convert.js#L124-L128) suggest that `colorscale` is used only when the mesh3d trace `intensity` is set. Could you confirm or infirm. Thanks!

**Comment by mdtusz** [comment]
@VeraZab @etpinard @cldougl 

We'll want to update the docs to be _much_ more clear regarding colorscale on meshes like this.

**To clarify**

`colorscale` only has an effect if `intensity` is set as well for the surface, where `intensity` is an array of normalized values for each vertex of the mesh corresponding to an interpolated color value based on the colorscale. E.g in extreme pseudocode (vertices isn't an actual plotly attribute).

```
vertices: [A, B, C]
intensity: [0, 0.5, 1]
colorscale: [[0, rgb(255, 0, 0)], [0.5, rgb(0, 255, 0)], [1, rgb(0, 0, 255)]]
```

This will create a surface where vertex `A` will be pure red, `B` will be green, and `C` will be blue, and a smooth gradient will be interpolated inbetween the vertices.

[Here's a tetrahedron example on jsbin](http://jsbin.com/jaxare/edit?js,output).

**Comment by etpinard** [comment]
@mdtusz ... and we should add an image test for that case too.

**Comment by etpinard** [comment]
closed in favour of https://github.com/plotly/plotly.js/pull/643

**Pull request closed without merging**
