### PR TITLE
More zoomed-in box/violin hover labels fixes 

### PR DESCRIPTION
**Pull request by etpinard**
@plotly/plotly_js This presents a few commits that alters (mostly fixes :smirk: ) the box/violin hover behaviour when their corresponding value axis range is within the box/violin q1/q3 values. This PR is essentially generalises https://github.com/plotly/plotly.js/pull/3889

Consider,

```js
Plotly.newPlot(gd, [{
  type: 'box',
  y: [1,2,2,3]
}], {
  yaxis: {range: [1.6, 2.4]},
  hovermode: 'x'
})
```

Currently on master (ever since #3645, released in `v1.45.3`), hovering over the box gets us an exception on this line

https://github.com/plotly/plotly.js/blob/06901623e988b7ad036207a905a4a032da186357/src/components/fx/hover.js#L1187

as reported in https://github.com/plotly/plotly.js/issues/3962

---

Commit https://github.com/plotly/plotly.js/commit/a4b771c6cbb4f17319e35dcaca78d6a71bd9aed1 is enough to _fix_ the problem and matches the pre-`1.45.3` behaviour:

Peek 2019-06-14 17-02

but notice that `min` and `q3` are shown and `q1` and `max` are not, which looked odd to me.

---

Commit https://github.com/plotly/plotly.js/commit/1634ec80148d8c5d26933dd48a966ff21b298473 made `q1` and `q3` show instead:

Peek 2019-06-14 17-05

which I think is better as we show both "innermost" values, but maybe we could do even better.

---

Commit https://github.com/plotly/plotly.js/commit/ce5e5f96d58e8f8b9a1f8947e7b38344d5507977 made all box labels show i.e. `min`, `q1`, `median`, `q3` and `max` while avoiding overlaps on the y-axis bounds:

Peek 2019-06-14 17-08

which I feel matches similar scenarios (e.g zoomed-in stack bars [codepen](https://codepen.io/etpinard/pen/bPEqQL)) better, but please let me know if you disagree.

### CODE REVIEW

**Comment by antoinerg** [comment]
Thank you for fixing #3962 @etpinard !

As far as I'm concerned, this PR deserves a dancer as it improves things. However, I'll let @nicolaskruchten and/or @alexcjohnson comment on the decision of showing all boxes (ie. https://github.com/plotly/plotly.js/commit/ce5e5f96d58e8f8b9a1f8947e7b38344d5507977).

**Comment by alexcjohnson** [comment]
Yep, much better! 💃

Does look a little weird to have the arrows pointing right at the edge of the plot area, but of course this is what we do in other contexts where you're hovering on something off-plot. So maybe at some point we can alter that somehow to make it clearer they're not actually right there. Maybe as simple as getting rid of the arrow altogether, so these ones only have the box?

**Comment by etpinard** [comment]
> Maybe as simple as getting rid of the arrow altogether, so these ones only have the box?

Follow-up in https://github.com/plotly/plotly.js/issues/3985

**Comment by etpinard** [comment]
Ok, let's start merging things for `1.49.0`

**Pull request merged**
