### PR TITLE
Add horizontal alignment for legend title

### PR DESCRIPTION
**Pull request by 28raining**
To help solve https://github.com/plotly/plotly.js/issues/6668

Added more options to 'side' inside layout -> legend so that when legend is in horizontal orientation the title can be aligned [left, center, right]

One strange thing is that 'top center' and 'top right' work as expected, but to get 'top left' you need to use 'top'.
Because 'top left' is already being used to move the title to the outside-left-side of the legend.
IMO it's a weird behavior but it's been purposely coded, so I didn't touch it

### CODE REVIEW

**Comment by 28raining** [comment]
mapbox is failing because this domain is down / gone

https://img.nj.gov

which is used in this baseline:
plotly.js/test/image/mocks/mapbox_layers.json

**Comment by archmoj** [comment]
Thanks for the PR.
FYI - The baseline tests were now passed.

**Comment by archmoj** [comment]
Great PR.
1 - Let's modify one of the mocks so that it has the *top right* option.
2 - What does happen if you have these options on a legend with the `orientation` set to *v*?

**Comment by 28raining** [comment]
Thank you.
1 - Top right test added to existing mock. This highlighted need to account for right-side-border
2 - Added top center to a vertical legend mock. Top, top center and top right do work with vertical too, I believe it's orientation agnostic.

**Comment by archmoj** [comment]
Nicely done.
Thanks very much for the PR.
:dancer:

**Pull request merged**
