### PR TITLE
Bump package-lockfile to v3

### PR DESCRIPTION
**Pull request by birkskyum**

### CODE REVIEW

**Comment by archmoj** [comment]
What are the benefits of a lock file v3?

**Comment by birkskyum** [comment]
Mainly that it's half the size, which makes it faster to read/modify

**Comment by archmoj** [comment]
What are the minimum npm & node required versions that support lock file v3?

**Comment by birkskyum** [comment]
I believe it's minimum npm v9. It comes bundled with node 18

**Comment by archmoj** [comment]
I'm afraid this could be considered a breaking change.
But that's definitely something to think about for plotly.js v3.
cc: @ndrezn @gvwilson

**Comment by birkskyum** [comment]
Okay. It'll not change the bundle one byte though, so I don't see how it can break for any users.

**Comment by archmoj** [comment]
> Okay. It'll not change the bundle one byte though, so I don't see how it can break for any users.

We have users that use this [custom bundle script](https://github.com/plotly/plotly.js/blob/master/CUSTOM_BUNDLE.md) to generate custom bundles. If they still use node.js v16 in their system I think we should allow them to continue for a bit longer. No? 

@alexcjohnson What do you think?

**Comment by birkskyum** [comment]
Related
- https://github.com/plotly/plotly.js/pull/7101

**Comment by alexcjohnson** [comment]
Given that we can support users back to npm v7 (older node 16 versions) I think it's reasonable to make this switch now and not consider it a breaking change. It'll require _contributors_ to be on later node/npm versions at least if they're touching dependencies, but that's fine, we've never considered contributor requirement changes as breaking. Also I'll note we already describe later node/npm as a requirement for custom bundling:

https://github.com/plotly/plotly.js/blob/74dedd4888748083da45cdc0548dafaae9784bcd/CUSTOM_BUNDLE.md?plain=1#L4-L7

**Comment by birkskyum** [comment]
Rebase, after the addition of biome.

**Review by archmoj — APPROVED** [review]
:dancer:

**Pull request merged**
