### PR TITLE
Replacing 2018 Copyright years with 2019

### PR DESCRIPTION
**Pull request by archmoj**
Failed the syntax test for the moment;  but that may be passed in 2019!
Happy new year @plotly/plotly_js

### CODE REVIEW

**Comment by archmoj** [comment]
OK. The tests are passed now.
I move forward and merge this thing!

**Comment by etpinard** [comment]
Thanks. I hope you didn't do this by hand and used

```
(plotly.js) $ node tasks/header.js
```

**Comment by archmoj** [comment]
Lovely script! Though I didn't used that for this year.
Should we also change the copyright on the files on the dist folder?
Running the script on master only show me that difference.

**Comment by etpinard** [comment]
> Should we also change the copyright on the files on the dist folder?

No need. We'll do that during the next release 1.43.2.

**Pull request merged**
